// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: document_processing.proto

package shared_protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentProcessingService_ChunkDocument_FullMethodName = "/document.processing.v1.DocumentProcessingService/ChunkDocument"
)

// DocumentProcessingServiceClient is the client API for DocumentProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentProcessingServiceClient interface {
	ChunkDocument(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChunkDocumentRequest, ChunkDocumentResponse], error)
}

type documentProcessingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentProcessingServiceClient(cc grpc.ClientConnInterface) DocumentProcessingServiceClient {
	return &documentProcessingServiceClient{cc}
}

func (c *documentProcessingServiceClient) ChunkDocument(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChunkDocumentRequest, ChunkDocumentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentProcessingService_ServiceDesc.Streams[0], DocumentProcessingService_ChunkDocument_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChunkDocumentRequest, ChunkDocumentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentProcessingService_ChunkDocumentClient = grpc.BidiStreamingClient[ChunkDocumentRequest, ChunkDocumentResponse]

// DocumentProcessingServiceServer is the server API for DocumentProcessingService service.
// All implementations must embed UnimplementedDocumentProcessingServiceServer
// for forward compatibility.
type DocumentProcessingServiceServer interface {
	ChunkDocument(grpc.BidiStreamingServer[ChunkDocumentRequest, ChunkDocumentResponse]) error
	mustEmbedUnimplementedDocumentProcessingServiceServer()
}

// UnimplementedDocumentProcessingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentProcessingServiceServer struct{}

func (UnimplementedDocumentProcessingServiceServer) ChunkDocument(grpc.BidiStreamingServer[ChunkDocumentRequest, ChunkDocumentResponse]) error {
	return status.Error(codes.Unimplemented, "method ChunkDocument not implemented")
}
func (UnimplementedDocumentProcessingServiceServer) mustEmbedUnimplementedDocumentProcessingServiceServer() {
}
func (UnimplementedDocumentProcessingServiceServer) testEmbeddedByValue() {}

// UnsafeDocumentProcessingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentProcessingServiceServer will
// result in compilation errors.
type UnsafeDocumentProcessingServiceServer interface {
	mustEmbedUnimplementedDocumentProcessingServiceServer()
}

func RegisterDocumentProcessingServiceServer(s grpc.ServiceRegistrar, srv DocumentProcessingServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentProcessingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentProcessingService_ServiceDesc, srv)
}

func _DocumentProcessingService_ChunkDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocumentProcessingServiceServer).ChunkDocument(&grpc.GenericServerStream[ChunkDocumentRequest, ChunkDocumentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentProcessingService_ChunkDocumentServer = grpc.BidiStreamingServer[ChunkDocumentRequest, ChunkDocumentResponse]

// DocumentProcessingService_ServiceDesc is the grpc.ServiceDesc for DocumentProcessingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentProcessingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "document.processing.v1.DocumentProcessingService",
	HandlerType: (*DocumentProcessingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChunkDocument",
			Handler:       _DocumentProcessingService_ChunkDocument_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "document_processing.proto",
}
