syntax = "proto3";

package document.processing.v1;

option go_package = "github.com/AndrewK4758/shared_protos";
option csharp_namespace = "Document.Processing.V1";

import "orchestrator.proto";
import "models.proto";
import "ml_worker.proto";

service DocumentProcessingService {
  rpc ChunkDocument(stream ChunkDocumentRequest) returns (stream ChunkDocumentResponse);
  rpc ProcessDocument(ProcessDocRequest) returns (ProcessDocResponse);
}

message ProcessDocRequest {
  string document_uri = 1;
  document.models.v1.InfrastructureIdentity identity = 2;
  repeated ml.worker.v1.PiiType target_pii_types = 3;
}

message ProcessDocResponse {
  bool success = 1;
  string error_message = 2;
}

message ChunkDocumentRequest {
  document.models.v1.InfrastructureIdentity identity = 1;
  string step_id = 2;
  document.models.v1.DocumentProcessorContract document_processor = 3;
  document.orchestrator.v1.ExecuteTaskRequest original_request = 4;
  bytes raw_file_bytes = 5;
}

message ProcessedDocument {
  string document_type = 1;
  string relative_file_path = 2;
  int32 page_count = 3;
  bytes raw_file_bytes = 4;
  bool is_scanned = 5;
}

message ChunkingTraceEvent {
  string timestamp = 1;
  string message = 2;
  string event_type = 3; // e.g. "INFO", "WARN", "ERROR"
}

message ChunkDocumentResponse {
  bool success = 1;
  string error_message = 2;
  repeated ProcessedDocument processed_documents = 3;
  repeated ChunkingTraceEvent trace_events = 4;
}
