// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: human_validation.proto

package shared_protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HumanValidationService_CreateValidationTask_FullMethodName = "/document.validation.v1.HumanValidationService/CreateValidationTask"
	HumanValidationService_GetPendingTasks_FullMethodName      = "/document.validation.v1.HumanValidationService/GetPendingTasks"
	HumanValidationService_SubmitCorrection_FullMethodName     = "/document.validation.v1.HumanValidationService/SubmitCorrection"
)

// HumanValidationServiceClient is the client API for HumanValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HumanValidationServiceClient interface {
	// Orchestrator or Client registers a task needing human validation
	CreateValidationTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	// Retrieve pending tasks for review
	GetPendingTasks(ctx context.Context, in *GetPendingTasksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PendingTask], error)
	// Submit corrected JSON from human UI or script
	SubmitCorrection(ctx context.Context, in *SubmitCorrectionRequest, opts ...grpc.CallOption) (*SubmitCorrectionResponse, error)
}

type humanValidationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHumanValidationServiceClient(cc grpc.ClientConnInterface) HumanValidationServiceClient {
	return &humanValidationServiceClient{cc}
}

func (c *humanValidationServiceClient) CreateValidationTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, HumanValidationService_CreateValidationTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *humanValidationServiceClient) GetPendingTasks(ctx context.Context, in *GetPendingTasksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PendingTask], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HumanValidationService_ServiceDesc.Streams[0], HumanValidationService_GetPendingTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetPendingTasksRequest, PendingTask]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HumanValidationService_GetPendingTasksClient = grpc.ServerStreamingClient[PendingTask]

func (c *humanValidationServiceClient) SubmitCorrection(ctx context.Context, in *SubmitCorrectionRequest, opts ...grpc.CallOption) (*SubmitCorrectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitCorrectionResponse)
	err := c.cc.Invoke(ctx, HumanValidationService_SubmitCorrection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HumanValidationServiceServer is the server API for HumanValidationService service.
// All implementations must embed UnimplementedHumanValidationServiceServer
// for forward compatibility.
type HumanValidationServiceServer interface {
	// Orchestrator or Client registers a task needing human validation
	CreateValidationTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	// Retrieve pending tasks for review
	GetPendingTasks(*GetPendingTasksRequest, grpc.ServerStreamingServer[PendingTask]) error
	// Submit corrected JSON from human UI or script
	SubmitCorrection(context.Context, *SubmitCorrectionRequest) (*SubmitCorrectionResponse, error)
	mustEmbedUnimplementedHumanValidationServiceServer()
}

// UnimplementedHumanValidationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHumanValidationServiceServer struct{}

func (UnimplementedHumanValidationServiceServer) CreateValidationTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateValidationTask not implemented")
}
func (UnimplementedHumanValidationServiceServer) GetPendingTasks(*GetPendingTasksRequest, grpc.ServerStreamingServer[PendingTask]) error {
	return status.Error(codes.Unimplemented, "method GetPendingTasks not implemented")
}
func (UnimplementedHumanValidationServiceServer) SubmitCorrection(context.Context, *SubmitCorrectionRequest) (*SubmitCorrectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitCorrection not implemented")
}
func (UnimplementedHumanValidationServiceServer) mustEmbedUnimplementedHumanValidationServiceServer() {
}
func (UnimplementedHumanValidationServiceServer) testEmbeddedByValue() {}

// UnsafeHumanValidationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HumanValidationServiceServer will
// result in compilation errors.
type UnsafeHumanValidationServiceServer interface {
	mustEmbedUnimplementedHumanValidationServiceServer()
}

func RegisterHumanValidationServiceServer(s grpc.ServiceRegistrar, srv HumanValidationServiceServer) {
	// If the following call panics, it indicates UnimplementedHumanValidationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HumanValidationService_ServiceDesc, srv)
}

func _HumanValidationService_CreateValidationTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanValidationServiceServer).CreateValidationTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HumanValidationService_CreateValidationTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanValidationServiceServer).CreateValidationTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HumanValidationService_GetPendingTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPendingTasksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HumanValidationServiceServer).GetPendingTasks(m, &grpc.GenericServerStream[GetPendingTasksRequest, PendingTask]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HumanValidationService_GetPendingTasksServer = grpc.ServerStreamingServer[PendingTask]

func _HumanValidationService_SubmitCorrection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCorrectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanValidationServiceServer).SubmitCorrection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HumanValidationService_SubmitCorrection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanValidationServiceServer).SubmitCorrection(ctx, req.(*SubmitCorrectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HumanValidationService_ServiceDesc is the grpc.ServiceDesc for HumanValidationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HumanValidationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "document.validation.v1.HumanValidationService",
	HandlerType: (*HumanValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateValidationTask",
			Handler:    _HumanValidationService_CreateValidationTask_Handler,
		},
		{
			MethodName: "SubmitCorrection",
			Handler:    _HumanValidationService_SubmitCorrection_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPendingTasks",
			Handler:       _HumanValidationService_GetPendingTasks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "human_validation.proto",
}
