// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ml_worker.proto

package shared_protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MlWorkerService_RedactPii_FullMethodName = "/ml.worker.v1.MlWorkerService/RedactPii"
)

// MlWorkerServiceClient is the client API for MlWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MlWorkerServiceClient interface {
	RedactPii(ctx context.Context, in *PiiRedactionRequest, opts ...grpc.CallOption) (*PiiRedactionResponse, error)
}

type mlWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMlWorkerServiceClient(cc grpc.ClientConnInterface) MlWorkerServiceClient {
	return &mlWorkerServiceClient{cc}
}

func (c *mlWorkerServiceClient) RedactPii(ctx context.Context, in *PiiRedactionRequest, opts ...grpc.CallOption) (*PiiRedactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PiiRedactionResponse)
	err := c.cc.Invoke(ctx, MlWorkerService_RedactPii_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MlWorkerServiceServer is the server API for MlWorkerService service.
// All implementations must embed UnimplementedMlWorkerServiceServer
// for forward compatibility.
type MlWorkerServiceServer interface {
	RedactPii(context.Context, *PiiRedactionRequest) (*PiiRedactionResponse, error)
	mustEmbedUnimplementedMlWorkerServiceServer()
}

// UnimplementedMlWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMlWorkerServiceServer struct{}

func (UnimplementedMlWorkerServiceServer) RedactPii(context.Context, *PiiRedactionRequest) (*PiiRedactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RedactPii not implemented")
}
func (UnimplementedMlWorkerServiceServer) mustEmbedUnimplementedMlWorkerServiceServer() {}
func (UnimplementedMlWorkerServiceServer) testEmbeddedByValue()                         {}

// UnsafeMlWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MlWorkerServiceServer will
// result in compilation errors.
type UnsafeMlWorkerServiceServer interface {
	mustEmbedUnimplementedMlWorkerServiceServer()
}

func RegisterMlWorkerServiceServer(s grpc.ServiceRegistrar, srv MlWorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedMlWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MlWorkerService_ServiceDesc, srv)
}

func _MlWorkerService_RedactPii_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PiiRedactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlWorkerServiceServer).RedactPii(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlWorkerService_RedactPii_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlWorkerServiceServer).RedactPii(ctx, req.(*PiiRedactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MlWorkerService_ServiceDesc is the grpc.ServiceDesc for MlWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MlWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ml.worker.v1.MlWorkerService",
	HandlerType: (*MlWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RedactPii",
			Handler:    _MlWorkerService_RedactPii_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ml_worker.proto",
}

const (
	CppMlWorkerService_RedactDocument_FullMethodName = "/ml.worker.v1.CppMlWorkerService/RedactDocument"
)

// CppMlWorkerServiceClient is the client API for CppMlWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CppMlWorkerServiceClient interface {
	RedactDocument(ctx context.Context, in *RedactDocumentRequest, opts ...grpc.CallOption) (*RedactDocumentResponse, error)
}

type cppMlWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCppMlWorkerServiceClient(cc grpc.ClientConnInterface) CppMlWorkerServiceClient {
	return &cppMlWorkerServiceClient{cc}
}

func (c *cppMlWorkerServiceClient) RedactDocument(ctx context.Context, in *RedactDocumentRequest, opts ...grpc.CallOption) (*RedactDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedactDocumentResponse)
	err := c.cc.Invoke(ctx, CppMlWorkerService_RedactDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CppMlWorkerServiceServer is the server API for CppMlWorkerService service.
// All implementations must embed UnimplementedCppMlWorkerServiceServer
// for forward compatibility.
type CppMlWorkerServiceServer interface {
	RedactDocument(context.Context, *RedactDocumentRequest) (*RedactDocumentResponse, error)
	mustEmbedUnimplementedCppMlWorkerServiceServer()
}

// UnimplementedCppMlWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCppMlWorkerServiceServer struct{}

func (UnimplementedCppMlWorkerServiceServer) RedactDocument(context.Context, *RedactDocumentRequest) (*RedactDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RedactDocument not implemented")
}
func (UnimplementedCppMlWorkerServiceServer) mustEmbedUnimplementedCppMlWorkerServiceServer() {}
func (UnimplementedCppMlWorkerServiceServer) testEmbeddedByValue()                            {}

// UnsafeCppMlWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CppMlWorkerServiceServer will
// result in compilation errors.
type UnsafeCppMlWorkerServiceServer interface {
	mustEmbedUnimplementedCppMlWorkerServiceServer()
}

func RegisterCppMlWorkerServiceServer(s grpc.ServiceRegistrar, srv CppMlWorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedCppMlWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CppMlWorkerService_ServiceDesc, srv)
}

func _CppMlWorkerService_RedactDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedactDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CppMlWorkerServiceServer).RedactDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CppMlWorkerService_RedactDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CppMlWorkerServiceServer).RedactDocument(ctx, req.(*RedactDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CppMlWorkerService_ServiceDesc is the grpc.ServiceDesc for CppMlWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CppMlWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ml.worker.v1.CppMlWorkerService",
	HandlerType: (*CppMlWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RedactDocument",
			Handler:    _CppMlWorkerService_RedactDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ml_worker.proto",
}
