// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ml_worker.proto

package shared_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PiiType int32

const (
	PiiType_PII_TYPE_UNSPECIFIED         PiiType = 0
	PiiType_PII_TYPE_PERSON_NAME         PiiType = 1
	PiiType_PII_TYPE_ADDRESS             PiiType = 2
	PiiType_PII_TYPE_PHONE_NUMBER        PiiType = 3
	PiiType_PII_TYPE_EMAIL               PiiType = 4
	PiiType_PII_TYPE_MONEY               PiiType = 5
	PiiType_PII_TYPE_PERCENTAGE          PiiType = 6
	PiiType_PII_TYPE_CONTACT_INFORMATION PiiType = 7
	PiiType_PII_TYPE_BARCODE             PiiType = 8
	PiiType_PII_TYPE_QR_CODE             PiiType = 9
	PiiType_PII_TYPE_ESIGNATURE          PiiType = 10
	PiiType_PII_TYPE_IMAGE               PiiType = 11
	PiiType_PII_TYPE_TIME                PiiType = 12
	PiiType_PII_TYPE_SSN                 PiiType = 13
	PiiType_PII_TYPE_LENDER              PiiType = 14
	PiiType_PII_TYPE_ORDER_NUMBER        PiiType = 15
	PiiType_PII_TYPE_LOAN_NUMBER         PiiType = 16
	PiiType_PII_TYPE_AGENT               PiiType = 17
	PiiType_PII_TYPE_SIGNATURE           PiiType = 18
)

// Enum value maps for PiiType.
var (
	PiiType_name = map[int32]string{
		0:  "PII_TYPE_UNSPECIFIED",
		1:  "PII_TYPE_PERSON_NAME",
		2:  "PII_TYPE_ADDRESS",
		3:  "PII_TYPE_PHONE_NUMBER",
		4:  "PII_TYPE_EMAIL",
		5:  "PII_TYPE_MONEY",
		6:  "PII_TYPE_PERCENTAGE",
		7:  "PII_TYPE_CONTACT_INFORMATION",
		8:  "PII_TYPE_BARCODE",
		9:  "PII_TYPE_QR_CODE",
		10: "PII_TYPE_ESIGNATURE",
		11: "PII_TYPE_IMAGE",
		12: "PII_TYPE_TIME",
		13: "PII_TYPE_SSN",
		14: "PII_TYPE_LENDER",
		15: "PII_TYPE_ORDER_NUMBER",
		16: "PII_TYPE_LOAN_NUMBER",
		17: "PII_TYPE_AGENT",
		18: "PII_TYPE_SIGNATURE",
	}
	PiiType_value = map[string]int32{
		"PII_TYPE_UNSPECIFIED":         0,
		"PII_TYPE_PERSON_NAME":         1,
		"PII_TYPE_ADDRESS":             2,
		"PII_TYPE_PHONE_NUMBER":        3,
		"PII_TYPE_EMAIL":               4,
		"PII_TYPE_MONEY":               5,
		"PII_TYPE_PERCENTAGE":          6,
		"PII_TYPE_CONTACT_INFORMATION": 7,
		"PII_TYPE_BARCODE":             8,
		"PII_TYPE_QR_CODE":             9,
		"PII_TYPE_ESIGNATURE":          10,
		"PII_TYPE_IMAGE":               11,
		"PII_TYPE_TIME":                12,
		"PII_TYPE_SSN":                 13,
		"PII_TYPE_LENDER":              14,
		"PII_TYPE_ORDER_NUMBER":        15,
		"PII_TYPE_LOAN_NUMBER":         16,
		"PII_TYPE_AGENT":               17,
		"PII_TYPE_SIGNATURE":           18,
	}
)

func (x PiiType) Enum() *PiiType {
	p := new(PiiType)
	*p = x
	return p
}

func (x PiiType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PiiType) Descriptor() protoreflect.EnumDescriptor {
	return file_ml_worker_proto_enumTypes[0].Descriptor()
}

func (PiiType) Type() protoreflect.EnumType {
	return &file_ml_worker_proto_enumTypes[0]
}

func (x PiiType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PiiType.Descriptor instead.
func (PiiType) EnumDescriptor() ([]byte, []int) {
	return file_ml_worker_proto_rawDescGZIP(), []int{0}
}

type PiiRedactionRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Identity       *InfrastructureIdentity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	TargetPiiTypes []PiiType               `protobuf:"varint,2,rep,packed,name=target_pii_types,json=targetPiiTypes,proto3,enum=ml.worker.v1.PiiType" json:"target_pii_types,omitempty"`
	RawFileBytes   []byte                  `protobuf:"bytes,3,opt,name=raw_file_bytes,json=rawFileBytes,proto3" json:"raw_file_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PiiRedactionRequest) Reset() {
	*x = PiiRedactionRequest{}
	mi := &file_ml_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PiiRedactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiiRedactionRequest) ProtoMessage() {}

func (x *PiiRedactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiiRedactionRequest.ProtoReflect.Descriptor instead.
func (*PiiRedactionRequest) Descriptor() ([]byte, []int) {
	return file_ml_worker_proto_rawDescGZIP(), []int{0}
}

func (x *PiiRedactionRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PiiRedactionRequest) GetTargetPiiTypes() []PiiType {
	if x != nil {
		return x.TargetPiiTypes
	}
	return nil
}

func (x *PiiRedactionRequest) GetRawFileBytes() []byte {
	if x != nil {
		return x.RawFileBytes
	}
	return nil
}

type PiiRedactionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RedactedFileBytes  []byte                 `protobuf:"bytes,3,opt,name=redacted_file_bytes,json=redactedFileBytes,proto3" json:"redacted_file_bytes,omitempty"`
	RedactedBoxesCount int32                  `protobuf:"varint,4,opt,name=redacted_boxes_count,json=redactedBoxesCount,proto3" json:"redacted_boxes_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PiiRedactionResponse) Reset() {
	*x = PiiRedactionResponse{}
	mi := &file_ml_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PiiRedactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiiRedactionResponse) ProtoMessage() {}

func (x *PiiRedactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiiRedactionResponse.ProtoReflect.Descriptor instead.
func (*PiiRedactionResponse) Descriptor() ([]byte, []int) {
	return file_ml_worker_proto_rawDescGZIP(), []int{1}
}

func (x *PiiRedactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PiiRedactionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PiiRedactionResponse) GetRedactedFileBytes() []byte {
	if x != nil {
		return x.RedactedFileBytes
	}
	return nil
}

func (x *PiiRedactionResponse) GetRedactedBoxesCount() int32 {
	if x != nil {
		return x.RedactedBoxesCount
	}
	return 0
}

type NormalizedRedactionBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X0            float32                `protobuf:"fixed32,1,opt,name=x0,proto3" json:"x0,omitempty"`
	Y0            float32                `protobuf:"fixed32,2,opt,name=y0,proto3" json:"y0,omitempty"`
	X1            float32                `protobuf:"fixed32,3,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float32                `protobuf:"fixed32,4,opt,name=y1,proto3" json:"y1,omitempty"`
	PageNumber    int32                  `protobuf:"varint,5,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PiiType       PiiType                `protobuf:"varint,6,opt,name=pii_type,json=piiType,proto3,enum=ml.worker.v1.PiiType" json:"pii_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedRedactionBox) Reset() {
	*x = NormalizedRedactionBox{}
	mi := &file_ml_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedRedactionBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedRedactionBox) ProtoMessage() {}

func (x *NormalizedRedactionBox) ProtoReflect() protoreflect.Message {
	mi := &file_ml_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedRedactionBox.ProtoReflect.Descriptor instead.
func (*NormalizedRedactionBox) Descriptor() ([]byte, []int) {
	return file_ml_worker_proto_rawDescGZIP(), []int{2}
}

func (x *NormalizedRedactionBox) GetX0() float32 {
	if x != nil {
		return x.X0
	}
	return 0
}

func (x *NormalizedRedactionBox) GetY0() float32 {
	if x != nil {
		return x.Y0
	}
	return 0
}

func (x *NormalizedRedactionBox) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *NormalizedRedactionBox) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *NormalizedRedactionBox) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *NormalizedRedactionBox) GetPiiType() PiiType {
	if x != nil {
		return x.PiiType
	}
	return PiiType_PII_TYPE_UNSPECIFIED
}

type ExtractedSpan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	X0            float32                `protobuf:"fixed32,2,opt,name=x0,proto3" json:"x0,omitempty"`
	Y0            float32                `protobuf:"fixed32,3,opt,name=y0,proto3" json:"y0,omitempty"`
	X1            float32                `protobuf:"fixed32,4,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float32                `protobuf:"fixed32,5,opt,name=y1,proto3" json:"y1,omitempty"`
	Label         string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	Confidence    float32                `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	PageNumber    int32                  `protobuf:"varint,8,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractedSpan) Reset() {
	*x = ExtractedSpan{}
	mi := &file_ml_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractedSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractedSpan) ProtoMessage() {}

func (x *ExtractedSpan) ProtoReflect() protoreflect.Message {
	mi := &file_ml_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractedSpan.ProtoReflect.Descriptor instead.
func (*ExtractedSpan) Descriptor() ([]byte, []int) {
	return file_ml_worker_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractedSpan) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ExtractedSpan) GetX0() float32 {
	if x != nil {
		return x.X0
	}
	return 0
}

func (x *ExtractedSpan) GetY0() float32 {
	if x != nil {
		return x.Y0
	}
	return 0
}

func (x *ExtractedSpan) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *ExtractedSpan) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *ExtractedSpan) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ExtractedSpan) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ExtractedSpan) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type SpatialFeatureVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNumber    int32                  `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	HeaderDensity float32                `protobuf:"fixed32,2,opt,name=header_density,json=headerDensity,proto3" json:"header_density,omitempty"`
	BodyDensity   float32                `protobuf:"fixed32,3,opt,name=body_density,json=bodyDensity,proto3" json:"body_density,omitempty"`
	LineCount     int32                  `protobuf:"varint,4,opt,name=line_count,json=lineCount,proto3" json:"line_count,omitempty"`
	HasTopHeader  bool                   `protobuf:"varint,5,opt,name=has_top_header,json=hasTopHeader,proto3" json:"has_top_header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpatialFeatureVector) Reset() {
	*x = SpatialFeatureVector{}
	mi := &file_ml_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpatialFeatureVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpatialFeatureVector) ProtoMessage() {}

func (x *SpatialFeatureVector) ProtoReflect() protoreflect.Message {
	mi := &file_ml_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpatialFeatureVector.ProtoReflect.Descriptor instead.
func (*SpatialFeatureVector) Descriptor() ([]byte, []int) {
	return file_ml_worker_proto_rawDescGZIP(), []int{4}
}

func (x *SpatialFeatureVector) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *SpatialFeatureVector) GetHeaderDensity() float32 {
	if x != nil {
		return x.HeaderDensity
	}
	return 0
}

func (x *SpatialFeatureVector) GetBodyDensity() float32 {
	if x != nil {
		return x.BodyDensity
	}
	return 0
}

func (x *SpatialFeatureVector) GetLineCount() int32 {
	if x != nil {
		return x.LineCount
	}
	return 0
}

func (x *SpatialFeatureVector) GetHasTopHeader() bool {
	if x != nil {
		return x.HasTopHeader
	}
	return false
}

type RedactDocumentRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	DocumentUri   string                    `protobuf:"bytes,1,opt,name=document_uri,json=documentUri,proto3" json:"document_uri,omitempty"`
	Identity      *InfrastructureIdentity   `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	DynamicLabels []string                  `protobuf:"bytes,7,rep,name=dynamic_labels,json=dynamicLabels,proto3" json:"dynamic_labels,omitempty"`
	CustomBoxes   []*NormalizedRedactionBox `protobuf:"bytes,8,rep,name=custom_boxes,json=customBoxes,proto3" json:"custom_boxes,omitempty"`
	RawFileBytes  []byte                    `protobuf:"bytes,9,opt,name=raw_file_bytes,json=rawFileBytes,proto3" json:"raw_file_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedactDocumentRequest) Reset() {
	*x = RedactDocumentRequest{}
	mi := &file_ml_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactDocumentRequest) ProtoMessage() {}

func (x *RedactDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactDocumentRequest.ProtoReflect.Descriptor instead.
func (*RedactDocumentRequest) Descriptor() ([]byte, []int) {
	return file_ml_worker_proto_rawDescGZIP(), []int{5}
}

func (x *RedactDocumentRequest) GetDocumentUri() string {
	if x != nil {
		return x.DocumentUri
	}
	return ""
}

func (x *RedactDocumentRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *RedactDocumentRequest) GetDynamicLabels() []string {
	if x != nil {
		return x.DynamicLabels
	}
	return nil
}

func (x *RedactDocumentRequest) GetCustomBoxes() []*NormalizedRedactionBox {
	if x != nil {
		return x.CustomBoxes
	}
	return nil
}

func (x *RedactDocumentRequest) GetRawFileBytes() []byte {
	if x != nil {
		return x.RawFileBytes
	}
	return nil
}

type RedactDocumentResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RedactedFileBytes  []byte                 `protobuf:"bytes,3,opt,name=redacted_file_bytes,json=redactedFileBytes,proto3" json:"redacted_file_bytes,omitempty"`
	RedactedBoxesCount int32                  `protobuf:"varint,4,opt,name=redacted_boxes_count,json=redactedBoxesCount,proto3" json:"redacted_boxes_count,omitempty"`
	ExtractedSpans     []*ExtractedSpan       `protobuf:"bytes,5,rep,name=extracted_spans,json=extractedSpans,proto3" json:"extracted_spans,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RedactDocumentResponse) Reset() {
	*x = RedactDocumentResponse{}
	mi := &file_ml_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactDocumentResponse) ProtoMessage() {}

func (x *RedactDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactDocumentResponse.ProtoReflect.Descriptor instead.
func (*RedactDocumentResponse) Descriptor() ([]byte, []int) {
	return file_ml_worker_proto_rawDescGZIP(), []int{6}
}

func (x *RedactDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RedactDocumentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RedactDocumentResponse) GetRedactedFileBytes() []byte {
	if x != nil {
		return x.RedactedFileBytes
	}
	return nil
}

func (x *RedactDocumentResponse) GetRedactedBoxesCount() int32 {
	if x != nil {
		return x.RedactedBoxesCount
	}
	return 0
}

func (x *RedactDocumentResponse) GetExtractedSpans() []*ExtractedSpan {
	if x != nil {
		return x.ExtractedSpans
	}
	return nil
}

var File_ml_worker_proto protoreflect.FileDescriptor

const file_ml_worker_proto_rawDesc = "" +
	"\n" +
	"\x0fml_worker.proto\x12\fml.worker.v1\x1a\fmodels.proto\"\xc4\x01\n" +
	"\x13PiiRedactionRequest\x12F\n" +
	"\bidentity\x18\x01 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\x12?\n" +
	"\x10target_pii_types\x18\x02 \x03(\x0e2\x15.ml.worker.v1.PiiTypeR\x0etargetPiiTypes\x12$\n" +
	"\x0eraw_file_bytes\x18\x03 \x01(\fR\frawFileBytes\"\xb7\x01\n" +
	"\x14PiiRedactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12.\n" +
	"\x13redacted_file_bytes\x18\x03 \x01(\fR\x11redactedFileBytes\x120\n" +
	"\x14redacted_boxes_count\x18\x04 \x01(\x05R\x12redactedBoxesCount\"\xab\x01\n" +
	"\x16NormalizedRedactionBox\x12\x0e\n" +
	"\x02x0\x18\x01 \x01(\x02R\x02x0\x12\x0e\n" +
	"\x02y0\x18\x02 \x01(\x02R\x02y0\x12\x0e\n" +
	"\x02x1\x18\x03 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x04 \x01(\x02R\x02y1\x12\x1f\n" +
	"\vpage_number\x18\x05 \x01(\x05R\n" +
	"pageNumber\x120\n" +
	"\bpii_type\x18\x06 \x01(\x0e2\x15.ml.worker.v1.PiiTypeR\apiiType\"\xba\x01\n" +
	"\rExtractedSpan\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x0e\n" +
	"\x02x0\x18\x02 \x01(\x02R\x02x0\x12\x0e\n" +
	"\x02y0\x18\x03 \x01(\x02R\x02y0\x12\x0e\n" +
	"\x02x1\x18\x04 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x05 \x01(\x02R\x02y1\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\x12\x1f\n" +
	"\vpage_number\x18\b \x01(\x05R\n" +
	"pageNumber\"\xc6\x01\n" +
	"\x14SpatialFeatureVector\x12\x1f\n" +
	"\vpage_number\x18\x01 \x01(\x05R\n" +
	"pageNumber\x12%\n" +
	"\x0eheader_density\x18\x02 \x01(\x02R\rheaderDensity\x12!\n" +
	"\fbody_density\x18\x03 \x01(\x02R\vbodyDensity\x12\x1d\n" +
	"\n" +
	"line_count\x18\x04 \x01(\x05R\tlineCount\x12$\n" +
	"\x0ehas_top_header\x18\x05 \x01(\bR\fhasTopHeader\"\x98\x02\n" +
	"\x15RedactDocumentRequest\x12!\n" +
	"\fdocument_uri\x18\x01 \x01(\tR\vdocumentUri\x12F\n" +
	"\bidentity\x18\x02 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\x12%\n" +
	"\x0edynamic_labels\x18\a \x03(\tR\rdynamicLabels\x12G\n" +
	"\fcustom_boxes\x18\b \x03(\v2$.ml.worker.v1.NormalizedRedactionBoxR\vcustomBoxes\x12$\n" +
	"\x0eraw_file_bytes\x18\t \x01(\fR\frawFileBytes\"\xff\x01\n" +
	"\x16RedactDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12.\n" +
	"\x13redacted_file_bytes\x18\x03 \x01(\fR\x11redactedFileBytes\x120\n" +
	"\x14redacted_boxes_count\x18\x04 \x01(\x05R\x12redactedBoxesCount\x12D\n" +
	"\x0fextracted_spans\x18\x05 \x03(\v2\x1b.ml.worker.v1.ExtractedSpanR\x0eextractedSpans*\xc5\x03\n" +
	"\aPiiType\x12\x18\n" +
	"\x14PII_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PII_TYPE_PERSON_NAME\x10\x01\x12\x14\n" +
	"\x10PII_TYPE_ADDRESS\x10\x02\x12\x19\n" +
	"\x15PII_TYPE_PHONE_NUMBER\x10\x03\x12\x12\n" +
	"\x0ePII_TYPE_EMAIL\x10\x04\x12\x12\n" +
	"\x0ePII_TYPE_MONEY\x10\x05\x12\x17\n" +
	"\x13PII_TYPE_PERCENTAGE\x10\x06\x12 \n" +
	"\x1cPII_TYPE_CONTACT_INFORMATION\x10\a\x12\x14\n" +
	"\x10PII_TYPE_BARCODE\x10\b\x12\x14\n" +
	"\x10PII_TYPE_QR_CODE\x10\t\x12\x17\n" +
	"\x13PII_TYPE_ESIGNATURE\x10\n" +
	"\x12\x12\n" +
	"\x0ePII_TYPE_IMAGE\x10\v\x12\x11\n" +
	"\rPII_TYPE_TIME\x10\f\x12\x10\n" +
	"\fPII_TYPE_SSN\x10\r\x12\x13\n" +
	"\x0fPII_TYPE_LENDER\x10\x0e\x12\x19\n" +
	"\x15PII_TYPE_ORDER_NUMBER\x10\x0f\x12\x18\n" +
	"\x14PII_TYPE_LOAN_NUMBER\x10\x10\x12\x12\n" +
	"\x0ePII_TYPE_AGENT\x10\x11\x12\x16\n" +
	"\x12PII_TYPE_SIGNATURE\x10\x122e\n" +
	"\x0fMlWorkerService\x12R\n" +
	"\tRedactPii\x12!.ml.worker.v1.PiiRedactionRequest\x1a\".ml.worker.v1.PiiRedactionResponse2q\n" +
	"\x12CppMlWorkerService\x12[\n" +
	"\x0eRedactDocument\x12#.ml.worker.v1.RedactDocumentRequest\x1a$.ml.worker.v1.RedactDocumentResponseB5Z$github.com/AndrewK4758/shared_protos\xaa\x02\fMl.Worker.V1b\x06proto3"

var (
	file_ml_worker_proto_rawDescOnce sync.Once
	file_ml_worker_proto_rawDescData []byte
)

func file_ml_worker_proto_rawDescGZIP() []byte {
	file_ml_worker_proto_rawDescOnce.Do(func() {
		file_ml_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_worker_proto_rawDesc), len(file_ml_worker_proto_rawDesc)))
	})
	return file_ml_worker_proto_rawDescData
}

var file_ml_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ml_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ml_worker_proto_goTypes = []any{
	(PiiType)(0),                   // 0: ml.worker.v1.PiiType
	(*PiiRedactionRequest)(nil),    // 1: ml.worker.v1.PiiRedactionRequest
	(*PiiRedactionResponse)(nil),   // 2: ml.worker.v1.PiiRedactionResponse
	(*NormalizedRedactionBox)(nil), // 3: ml.worker.v1.NormalizedRedactionBox
	(*ExtractedSpan)(nil),          // 4: ml.worker.v1.ExtractedSpan
	(*SpatialFeatureVector)(nil),   // 5: ml.worker.v1.SpatialFeatureVector
	(*RedactDocumentRequest)(nil),  // 6: ml.worker.v1.RedactDocumentRequest
	(*RedactDocumentResponse)(nil), // 7: ml.worker.v1.RedactDocumentResponse
	(*InfrastructureIdentity)(nil), // 8: document.models.v1.InfrastructureIdentity
}
var file_ml_worker_proto_depIdxs = []int32{
	8, // 0: ml.worker.v1.PiiRedactionRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	0, // 1: ml.worker.v1.PiiRedactionRequest.target_pii_types:type_name -> ml.worker.v1.PiiType
	0, // 2: ml.worker.v1.NormalizedRedactionBox.pii_type:type_name -> ml.worker.v1.PiiType
	8, // 3: ml.worker.v1.RedactDocumentRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	3, // 4: ml.worker.v1.RedactDocumentRequest.custom_boxes:type_name -> ml.worker.v1.NormalizedRedactionBox
	4, // 5: ml.worker.v1.RedactDocumentResponse.extracted_spans:type_name -> ml.worker.v1.ExtractedSpan
	1, // 6: ml.worker.v1.MlWorkerService.RedactPii:input_type -> ml.worker.v1.PiiRedactionRequest
	6, // 7: ml.worker.v1.CppMlWorkerService.RedactDocument:input_type -> ml.worker.v1.RedactDocumentRequest
	2, // 8: ml.worker.v1.MlWorkerService.RedactPii:output_type -> ml.worker.v1.PiiRedactionResponse
	7, // 9: ml.worker.v1.CppMlWorkerService.RedactDocument:output_type -> ml.worker.v1.RedactDocumentResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ml_worker_proto_init() }
func file_ml_worker_proto_init() {
	if File_ml_worker_proto != nil {
		return
	}
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_worker_proto_rawDesc), len(file_ml_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ml_worker_proto_goTypes,
		DependencyIndexes: file_ml_worker_proto_depIdxs,
		EnumInfos:         file_ml_worker_proto_enumTypes,
		MessageInfos:      file_ml_worker_proto_msgTypes,
	}.Build()
	File_ml_worker_proto = out.File
	file_ml_worker_proto_goTypes = nil
	file_ml_worker_proto_depIdxs = nil
}
