syntax = "proto3";

package ml.worker.v1;

option go_package = "github.com/AndrewK4758/shared_protos";
option csharp_namespace = "Ml.Worker.V1";

import "models.proto";

service MlWorkerService {
  rpc RedactPii(PiiRedactionRequest) returns (PiiRedactionResponse);
}

enum PiiType {
  PII_TYPE_UNSPECIFIED = 0;
  PII_TYPE_PERSON_NAME = 1;
  PII_TYPE_ADDRESS = 2;
  PII_TYPE_PHONE_NUMBER = 3;
  PII_TYPE_EMAIL = 4;
  PII_TYPE_MONEY = 5;
  PII_TYPE_PERCENTAGE = 6;
  PII_TYPE_CONTACT_INFORMATION = 7;
  PII_TYPE_BARCODE = 8;
  PII_TYPE_QR_CODE = 9;
  PII_TYPE_ESIGNATURE = 10;
  PII_TYPE_IMAGE = 11;
  PII_TYPE_TIME = 12;
  PII_TYPE_SSN = 13;
  PII_TYPE_LENDER = 14;
  PII_TYPE_ORDER_NUMBER = 15;
  PII_TYPE_LOAN_NUMBER = 16;
  PII_TYPE_AGENT = 17;
  PII_TYPE_SIGNATURE = 18;
}

message PiiRedactionRequest {
  document.models.v1.InfrastructureIdentity identity = 1;
  repeated PiiType target_pii_types = 2;
  bytes raw_file_bytes = 3;
}

message PiiRedactionResponse {
  bool success = 1;
  string error_message = 2;
  bytes redacted_file_bytes = 3;
  int32 redacted_boxes_count = 4;
}

message NormalizedRedactionBox {
  float x0 = 1;
  float y0 = 2;
  float x1 = 3;
  float y1 = 4;
  int32 page_number = 5;
  PiiType pii_type = 6;
}

message ExtractedSpan {
  string text = 1;
  float x0 = 2;
  float y0 = 3;
  float x1 = 4;
  float y1 = 5;
  string label = 6;
  float confidence = 7;
  int32 page_number = 8;
}

message SpatialFeatureVector {
  int32 page_number = 1;
  float header_density = 2;
  float body_density = 3;
  int32 line_count = 4;
  bool has_top_header = 5;
}

service CppMlWorkerService {
  rpc RedactDocument(RedactDocumentRequest) returns (RedactDocumentResponse);
}

message RedactDocumentRequest {
  string document_uri = 1;
  document.models.v1.InfrastructureIdentity identity = 2;
  repeated string dynamic_labels = 7;
  repeated NormalizedRedactionBox custom_boxes = 8;
  bytes raw_file_bytes = 9;
}

message RedactDocumentResponse {
  bool success = 1;
  string error_message = 2;
  bytes redacted_file_bytes = 3;
  int32 redacted_boxes_count = 4;
  repeated ExtractedSpan extracted_spans = 5;
}

