// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: models.proto

package shared_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelChoice int32

const (
	ModelChoice_MODEL_CHOICE_UNSPECIFIED    ModelChoice = 0
	ModelChoice_MODEL_CHOICE_EXTRACTION     ModelChoice = 1
	ModelChoice_MODEL_CHOICE_CLASSIFICATION ModelChoice = 2
	ModelChoice_MODEL_CHOICE_PLANNING       ModelChoice = 3
	ModelChoice_MODEL_CHOICE_OCR            ModelChoice = 4
)

// Enum value maps for ModelChoice.
var (
	ModelChoice_name = map[int32]string{
		0: "MODEL_CHOICE_UNSPECIFIED",
		1: "MODEL_CHOICE_EXTRACTION",
		2: "MODEL_CHOICE_CLASSIFICATION",
		3: "MODEL_CHOICE_PLANNING",
		4: "MODEL_CHOICE_OCR",
	}
	ModelChoice_value = map[string]int32{
		"MODEL_CHOICE_UNSPECIFIED":    0,
		"MODEL_CHOICE_EXTRACTION":     1,
		"MODEL_CHOICE_CLASSIFICATION": 2,
		"MODEL_CHOICE_PLANNING":       3,
		"MODEL_CHOICE_OCR":            4,
	}
)

func (x ModelChoice) Enum() *ModelChoice {
	p := new(ModelChoice)
	*p = x
	return p
}

func (x ModelChoice) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelChoice) Descriptor() protoreflect.EnumDescriptor {
	return file_models_proto_enumTypes[0].Descriptor()
}

func (ModelChoice) Type() protoreflect.EnumType {
	return &file_models_proto_enumTypes[0]
}

func (x ModelChoice) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelChoice.Descriptor instead.
func (ModelChoice) EnumDescriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{0}
}

type WorkflowState int32

const (
	WorkflowState_WORKFLOW_STATE_UNSPECIFIED WorkflowState = 0
	WorkflowState_WORKFLOW_STATE_PENDING     WorkflowState = 1
	WorkflowState_WORKFLOW_STATE_PROCESSING  WorkflowState = 2
	WorkflowState_WORKFLOW_STATE_SUSPENDED   WorkflowState = 3
	WorkflowState_WORKFLOW_STATE_COMPLETED   WorkflowState = 4
	WorkflowState_WORKFLOW_STATE_FAILED      WorkflowState = 5
	WorkflowState_WORKFLOW_STATE_CANCELED    WorkflowState = 6
)

// Enum value maps for WorkflowState.
var (
	WorkflowState_name = map[int32]string{
		0: "WORKFLOW_STATE_UNSPECIFIED",
		1: "WORKFLOW_STATE_PENDING",
		2: "WORKFLOW_STATE_PROCESSING",
		3: "WORKFLOW_STATE_SUSPENDED",
		4: "WORKFLOW_STATE_COMPLETED",
		5: "WORKFLOW_STATE_FAILED",
		6: "WORKFLOW_STATE_CANCELED",
	}
	WorkflowState_value = map[string]int32{
		"WORKFLOW_STATE_UNSPECIFIED": 0,
		"WORKFLOW_STATE_PENDING":     1,
		"WORKFLOW_STATE_PROCESSING":  2,
		"WORKFLOW_STATE_SUSPENDED":   3,
		"WORKFLOW_STATE_COMPLETED":   4,
		"WORKFLOW_STATE_FAILED":      5,
		"WORKFLOW_STATE_CANCELED":    6,
	}
)

func (x WorkflowState) Enum() *WorkflowState {
	p := new(WorkflowState)
	*p = x
	return p
}

func (x WorkflowState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowState) Descriptor() protoreflect.EnumDescriptor {
	return file_models_proto_enumTypes[1].Descriptor()
}

func (WorkflowState) Type() protoreflect.EnumType {
	return &file_models_proto_enumTypes[1]
}

func (x WorkflowState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowState.Descriptor instead.
func (WorkflowState) EnumDescriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{1}
}

type ErrorContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientPayload *structpb.Struct       `protobuf:"bytes,6,opt,name=client_payload,json=clientPayload,proto3" json:"client_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorContract) Reset() {
	*x = ErrorContract{}
	mi := &file_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorContract) ProtoMessage() {}

func (x *ErrorContract) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorContract.ProtoReflect.Descriptor instead.
func (*ErrorContract) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorContract) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorContract) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ErrorContract) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorContract) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ErrorContract) GetClientPayload() *structpb.Struct {
	if x != nil {
		return x.ClientPayload
	}
	return nil
}

type InfrastructureIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfrastructureIdentity) Reset() {
	*x = InfrastructureIdentity{}
	mi := &file_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfrastructureIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureIdentity) ProtoMessage() {}

func (x *InfrastructureIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureIdentity.ProtoReflect.Descriptor instead.
func (*InfrastructureIdentity) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{1}
}

func (x *InfrastructureIdentity) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InfrastructureIdentity) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *InfrastructureIdentity) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StorageContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentUri   string                 `protobuf:"bytes,1,opt,name=document_uri,json=documentUri,proto3" json:"document_uri,omitempty"`
	DocumentPath  string                 `protobuf:"bytes,2,opt,name=document_path,json=documentPath,proto3" json:"document_path,omitempty"`
	PageCount     int32                  `protobuf:"varint,3,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageContract) Reset() {
	*x = StorageContract{}
	mi := &file_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageContract) ProtoMessage() {}

func (x *StorageContract) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageContract.ProtoReflect.Descriptor instead.
func (*StorageContract) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{2}
}

func (x *StorageContract) GetDocumentUri() string {
	if x != nil {
		return x.DocumentUri
	}
	return ""
}

func (x *StorageContract) GetDocumentPath() string {
	if x != nil {
		return x.DocumentPath
	}
	return ""
}

func (x *StorageContract) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

type DocumentProcessorContract struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ActionNameClassify      string                 `protobuf:"bytes,1,opt,name=action_name_classify,json=actionNameClassify,proto3" json:"action_name_classify,omitempty"`
	ActionNameBoundary      string                 `protobuf:"bytes,2,opt,name=action_name_boundary,json=actionNameBoundary,proto3" json:"action_name_boundary,omitempty"`
	DocTypeCorrupted        string                 `protobuf:"bytes,3,opt,name=doc_type_corrupted,json=docTypeCorrupted,proto3" json:"doc_type_corrupted,omitempty"`
	DocTypeClassified       string                 `protobuf:"bytes,4,opt,name=doc_type_classified,json=docTypeClassified,proto3" json:"doc_type_classified,omitempty"`
	DocTypeChunked          string                 `protobuf:"bytes,5,opt,name=doc_type_chunked,json=docTypeChunked,proto3" json:"doc_type_chunked,omitempty"`
	BoundaryDetectionPrompt string                 `protobuf:"bytes,6,opt,name=boundary_detection_prompt,json=boundaryDetectionPrompt,proto3" json:"boundary_detection_prompt,omitempty"`
	MaxPagesBeforeSplit     int32                  `protobuf:"varint,7,opt,name=max_pages_before_split,json=maxPagesBeforeSplit,proto3" json:"max_pages_before_split,omitempty"`
	SlidingWindowSize       int32                  `protobuf:"varint,8,opt,name=sliding_window_size,json=slidingWindowSize,proto3" json:"sliding_window_size,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DocumentProcessorContract) Reset() {
	*x = DocumentProcessorContract{}
	mi := &file_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentProcessorContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentProcessorContract) ProtoMessage() {}

func (x *DocumentProcessorContract) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentProcessorContract.ProtoReflect.Descriptor instead.
func (*DocumentProcessorContract) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{3}
}

func (x *DocumentProcessorContract) GetActionNameClassify() string {
	if x != nil {
		return x.ActionNameClassify
	}
	return ""
}

func (x *DocumentProcessorContract) GetActionNameBoundary() string {
	if x != nil {
		return x.ActionNameBoundary
	}
	return ""
}

func (x *DocumentProcessorContract) GetDocTypeCorrupted() string {
	if x != nil {
		return x.DocTypeCorrupted
	}
	return ""
}

func (x *DocumentProcessorContract) GetDocTypeClassified() string {
	if x != nil {
		return x.DocTypeClassified
	}
	return ""
}

func (x *DocumentProcessorContract) GetDocTypeChunked() string {
	if x != nil {
		return x.DocTypeChunked
	}
	return ""
}

func (x *DocumentProcessorContract) GetBoundaryDetectionPrompt() string {
	if x != nil {
		return x.BoundaryDetectionPrompt
	}
	return ""
}

func (x *DocumentProcessorContract) GetMaxPagesBeforeSplit() int32 {
	if x != nil {
		return x.MaxPagesBeforeSplit
	}
	return 0
}

func (x *DocumentProcessorContract) GetSlidingWindowSize() int32 {
	if x != nil {
		return x.SlidingWindowSize
	}
	return 0
}

type CacheContract struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Enabled                 bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CollectionName          string                 `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	CacheHit                bool                   `protobuf:"varint,4,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	Confidence              float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	EmbeddingLookup         *anypb.Any             `protobuf:"bytes,6,opt,name=embedding_lookup,json=embeddingLookup,proto3" json:"embedding_lookup,omitempty"`
	MetadataLookup          *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata_lookup,json=metadataLookup,proto3" json:"metadata_lookup,omitempty"`
	PlainTextEmbeddingValue string                 `protobuf:"bytes,8,opt,name=plain_text_embedding_value,json=plainTextEmbeddingValue,proto3" json:"plain_text_embedding_value,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CacheContract) Reset() {
	*x = CacheContract{}
	mi := &file_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheContract) ProtoMessage() {}

func (x *CacheContract) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheContract.ProtoReflect.Descriptor instead.
func (*CacheContract) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{4}
}

func (x *CacheContract) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CacheContract) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CacheContract) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *CacheContract) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CacheContract) GetEmbeddingLookup() *anypb.Any {
	if x != nil {
		return x.EmbeddingLookup
	}
	return nil
}

func (x *CacheContract) GetMetadataLookup() *structpb.Struct {
	if x != nil {
		return x.MetadataLookup
	}
	return nil
}

func (x *CacheContract) GetPlainTextEmbeddingValue() string {
	if x != nil {
		return x.PlainTextEmbeddingValue
	}
	return ""
}

type HumanValidationContract struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Required       bool                   `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	BypassFallback bool                   `protobuf:"varint,2,opt,name=bypass_fallback,json=bypassFallback,proto3" json:"bypass_fallback,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HumanValidationContract) Reset() {
	*x = HumanValidationContract{}
	mi := &file_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanValidationContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanValidationContract) ProtoMessage() {}

func (x *HumanValidationContract) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanValidationContract.ProtoReflect.Descriptor instead.
func (*HumanValidationContract) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{5}
}

func (x *HumanValidationContract) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *HumanValidationContract) GetBypassFallback() bool {
	if x != nil {
		return x.BypassFallback
	}
	return false
}

type NodeConfiguration struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeName           string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	SystemInstructions string                 `protobuf:"bytes,2,opt,name=system_instructions,json=systemInstructions,proto3" json:"system_instructions,omitempty"`
	// Deprecated: Marked as deprecated in models.proto.
	ExpectedSchema       string           `protobuf:"bytes,3,opt,name=expected_schema,json=expectedSchema,proto3" json:"expected_schema,omitempty"`
	TargetWorkerSubject  string           `protobuf:"bytes,4,opt,name=target_worker_subject,json=targetWorkerSubject,proto3" json:"target_worker_subject,omitempty"`
	StateOutputKey       string           `protobuf:"bytes,5,opt,name=state_output_key,json=stateOutputKey,proto3" json:"state_output_key,omitempty"`
	InferenceInputKey    string           `protobuf:"bytes,6,opt,name=inference_input_key,json=inferenceInputKey,proto3" json:"inference_input_key,omitempty"`
	ExpectedSchemaStruct *structpb.Struct `protobuf:"bytes,7,opt,name=expected_schema_struct,json=expectedSchemaStruct,proto3" json:"expected_schema_struct,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeConfiguration) Reset() {
	*x = NodeConfiguration{}
	mi := &file_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfiguration) ProtoMessage() {}

func (x *NodeConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfiguration.ProtoReflect.Descriptor instead.
func (*NodeConfiguration) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{6}
}

func (x *NodeConfiguration) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeConfiguration) GetSystemInstructions() string {
	if x != nil {
		return x.SystemInstructions
	}
	return ""
}

// Deprecated: Marked as deprecated in models.proto.
func (x *NodeConfiguration) GetExpectedSchema() string {
	if x != nil {
		return x.ExpectedSchema
	}
	return ""
}

func (x *NodeConfiguration) GetTargetWorkerSubject() string {
	if x != nil {
		return x.TargetWorkerSubject
	}
	return ""
}

func (x *NodeConfiguration) GetStateOutputKey() string {
	if x != nil {
		return x.StateOutputKey
	}
	return ""
}

func (x *NodeConfiguration) GetInferenceInputKey() string {
	if x != nil {
		return x.InferenceInputKey
	}
	return ""
}

func (x *NodeConfiguration) GetExpectedSchemaStruct() *structpb.Struct {
	if x != nil {
		return x.ExpectedSchemaStruct
	}
	return nil
}

type ActionDefinition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Prompt              string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Rules               []string               `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	TargetWorkerSubject string                 `protobuf:"bytes,6,opt,name=target_worker_subject,json=targetWorkerSubject,proto3" json:"target_worker_subject,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ActionDefinition) Reset() {
	*x = ActionDefinition{}
	mi := &file_models_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionDefinition) ProtoMessage() {}

func (x *ActionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionDefinition.ProtoReflect.Descriptor instead.
func (*ActionDefinition) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{7}
}

func (x *ActionDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionDefinition) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ActionDefinition) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ActionDefinition) GetTargetWorkerSubject() string {
	if x != nil {
		return x.TargetWorkerSubject
	}
	return ""
}

type ActiveJobExecution struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobDefinitionId string                 `protobuf:"bytes,2,opt,name=job_definition_id,json=jobDefinitionId,proto3" json:"job_definition_id,omitempty"`
	CurrentStepId   string                 `protobuf:"bytes,3,opt,name=current_step_id,json=currentStepId,proto3" json:"current_step_id,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActiveJobExecution) Reset() {
	*x = ActiveJobExecution{}
	mi := &file_models_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveJobExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveJobExecution) ProtoMessage() {}

func (x *ActiveJobExecution) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveJobExecution.ProtoReflect.Descriptor instead.
func (*ActiveJobExecution) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{8}
}

func (x *ActiveJobExecution) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ActiveJobExecution) GetJobDefinitionId() string {
	if x != nil {
		return x.JobDefinitionId
	}
	return ""
}

func (x *ActiveJobExecution) GetCurrentStepId() string {
	if x != nil {
		return x.CurrentStepId
	}
	return ""
}

func (x *ActiveJobExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActiveJobExecution) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ActiveJobExecution) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GenericWorkflowState struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CurrentState  WorkflowState           `protobuf:"varint,1,opt,name=current_state,json=currentState,proto3,enum=document.models.v1.WorkflowState" json:"current_state,omitempty"`
	StateReason   string                  `protobuf:"bytes,2,opt,name=state_reason,json=stateReason,proto3" json:"state_reason,omitempty"`
	StatePayload  *structpb.Struct        `protobuf:"bytes,3,opt,name=state_payload,json=statePayload,proto3" json:"state_payload,omitempty"`
	LastUpdated   *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Identity      *InfrastructureIdentity `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericWorkflowState) Reset() {
	*x = GenericWorkflowState{}
	mi := &file_models_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericWorkflowState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericWorkflowState) ProtoMessage() {}

func (x *GenericWorkflowState) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericWorkflowState.ProtoReflect.Descriptor instead.
func (*GenericWorkflowState) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{9}
}

func (x *GenericWorkflowState) GetCurrentState() WorkflowState {
	if x != nil {
		return x.CurrentState
	}
	return WorkflowState_WORKFLOW_STATE_UNSPECIFIED
}

func (x *GenericWorkflowState) GetStateReason() string {
	if x != nil {
		return x.StateReason
	}
	return ""
}

func (x *GenericWorkflowState) GetStatePayload() *structpb.Struct {
	if x != nil {
		return x.StatePayload
	}
	return nil
}

func (x *GenericWorkflowState) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *GenericWorkflowState) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type ExecuteTaskPayload struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	NodeConfig        *NodeConfiguration         `protobuf:"bytes,1,opt,name=node_config,json=nodeConfig,proto3" json:"node_config,omitempty"`
	GlobalState       *structpb.Struct           `protobuf:"bytes,2,opt,name=global_state,json=globalState,proto3" json:"global_state,omitempty"`
	NodeOutput        *structpb.Struct           `protobuf:"bytes,3,opt,name=node_output,json=nodeOutput,proto3" json:"node_output,omitempty"`
	Metadata          *structpb.Struct           `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Cache             *CacheContract             `protobuf:"bytes,5,opt,name=cache,proto3" json:"cache,omitempty"`
	HumanValidation   *HumanValidationContract   `protobuf:"bytes,6,opt,name=human_validation,json=humanValidation,proto3" json:"human_validation,omitempty"`
	Storage           *StorageContract           `protobuf:"bytes,7,opt,name=storage,proto3" json:"storage,omitempty"`
	DocumentProcessor *DocumentProcessorContract `protobuf:"bytes,8,opt,name=document_processor,json=documentProcessor,proto3" json:"document_processor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteTaskPayload) Reset() {
	*x = ExecuteTaskPayload{}
	mi := &file_models_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskPayload) ProtoMessage() {}

func (x *ExecuteTaskPayload) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskPayload.ProtoReflect.Descriptor instead.
func (*ExecuteTaskPayload) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteTaskPayload) GetNodeConfig() *NodeConfiguration {
	if x != nil {
		return x.NodeConfig
	}
	return nil
}

func (x *ExecuteTaskPayload) GetGlobalState() *structpb.Struct {
	if x != nil {
		return x.GlobalState
	}
	return nil
}

func (x *ExecuteTaskPayload) GetNodeOutput() *structpb.Struct {
	if x != nil {
		return x.NodeOutput
	}
	return nil
}

func (x *ExecuteTaskPayload) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteTaskPayload) GetCache() *CacheContract {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *ExecuteTaskPayload) GetHumanValidation() *HumanValidationContract {
	if x != nil {
		return x.HumanValidation
	}
	return nil
}

func (x *ExecuteTaskPayload) GetStorage() *StorageContract {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *ExecuteTaskPayload) GetDocumentProcessor() *DocumentProcessorContract {
	if x != nil {
		return x.DocumentProcessor
	}
	return nil
}

type GlobalState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functional    *structpb.Struct       `protobuf:"bytes,1,opt,name=functional,proto3" json:"functional,omitempty"`
	NonFunctional *structpb.Struct       `protobuf:"bytes,2,opt,name=non_functional,json=nonFunctional,proto3" json:"non_functional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalState) Reset() {
	*x = GlobalState{}
	mi := &file_models_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalState) ProtoMessage() {}

func (x *GlobalState) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalState.ProtoReflect.Descriptor instead.
func (*GlobalState) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{11}
}

func (x *GlobalState) GetFunctional() *structpb.Struct {
	if x != nil {
		return x.Functional
	}
	return nil
}

func (x *GlobalState) GetNonFunctional() *structpb.Struct {
	if x != nil {
		return x.NonFunctional
	}
	return nil
}

type RootWorkflowPayload struct {
	state                protoimpl.MessageState     `protogen:"open.v1"`
	GraphId              string                     `protobuf:"bytes,1,opt,name=graph_id,json=graphId,proto3" json:"graph_id,omitempty"`
	InitialNodeId        string                     `protobuf:"bytes,2,opt,name=initial_node_id,json=initialNodeId,proto3" json:"initial_node_id,omitempty"`
	Metadata             *structpb.Struct           `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Cache                *CacheContract             `protobuf:"bytes,5,opt,name=cache,proto3" json:"cache,omitempty"`
	GlobalState          *GlobalState               `protobuf:"bytes,6,opt,name=global_state,json=globalState,proto3" json:"global_state,omitempty"`
	NodeConfig           *NodeConfiguration         `protobuf:"bytes,7,opt,name=node_config,json=nodeConfig,proto3" json:"node_config,omitempty"`
	Storage              *StorageContract           `protobuf:"bytes,8,opt,name=storage,proto3" json:"storage,omitempty"`
	DocumentProcessor    *DocumentProcessorContract `protobuf:"bytes,9,opt,name=document_processor,json=documentProcessor,proto3" json:"document_processor,omitempty"`
	ExpectedSchemaStruct *structpb.Struct           `protobuf:"bytes,10,opt,name=expected_schema_struct,json=expectedSchemaStruct,proto3" json:"expected_schema_struct,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RootWorkflowPayload) Reset() {
	*x = RootWorkflowPayload{}
	mi := &file_models_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootWorkflowPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootWorkflowPayload) ProtoMessage() {}

func (x *RootWorkflowPayload) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootWorkflowPayload.ProtoReflect.Descriptor instead.
func (*RootWorkflowPayload) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{12}
}

func (x *RootWorkflowPayload) GetGraphId() string {
	if x != nil {
		return x.GraphId
	}
	return ""
}

func (x *RootWorkflowPayload) GetInitialNodeId() string {
	if x != nil {
		return x.InitialNodeId
	}
	return ""
}

func (x *RootWorkflowPayload) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RootWorkflowPayload) GetCache() *CacheContract {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *RootWorkflowPayload) GetGlobalState() *GlobalState {
	if x != nil {
		return x.GlobalState
	}
	return nil
}

func (x *RootWorkflowPayload) GetNodeConfig() *NodeConfiguration {
	if x != nil {
		return x.NodeConfig
	}
	return nil
}

func (x *RootWorkflowPayload) GetStorage() *StorageContract {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *RootWorkflowPayload) GetDocumentProcessor() *DocumentProcessorContract {
	if x != nil {
		return x.DocumentProcessor
	}
	return nil
}

func (x *RootWorkflowPayload) GetExpectedSchemaStruct() *structpb.Struct {
	if x != nil {
		return x.ExpectedSchemaStruct
	}
	return nil
}

var File_models_proto protoreflect.FileDescriptor

const file_models_proto_rawDesc = "" +
	"\n" +
	"\fmodels.proto\x12\x12document.models.v1\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n" +
	"\rErrorContract\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12>\n" +
	"\x0eclient_payload\x18\x06 \x01(\v2\x17.google.protobuf.StructR\rclientPayload\"c\n" +
	"\x16InfrastructureIdentity\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\"x\n" +
	"\x0fStorageContract\x12!\n" +
	"\fdocument_uri\x18\x01 \x01(\tR\vdocumentUri\x12#\n" +
	"\rdocument_path\x18\x02 \x01(\tR\fdocumentPath\x12\x1d\n" +
	"\n" +
	"page_count\x18\x03 \x01(\x05R\tpageCount\"\xa8\x03\n" +
	"\x19DocumentProcessorContract\x120\n" +
	"\x14action_name_classify\x18\x01 \x01(\tR\x12actionNameClassify\x120\n" +
	"\x14action_name_boundary\x18\x02 \x01(\tR\x12actionNameBoundary\x12,\n" +
	"\x12doc_type_corrupted\x18\x03 \x01(\tR\x10docTypeCorrupted\x12.\n" +
	"\x13doc_type_classified\x18\x04 \x01(\tR\x11docTypeClassified\x12(\n" +
	"\x10doc_type_chunked\x18\x05 \x01(\tR\x0edocTypeChunked\x12:\n" +
	"\x19boundary_detection_prompt\x18\x06 \x01(\tR\x17boundaryDetectionPrompt\x123\n" +
	"\x16max_pages_before_split\x18\a \x01(\x05R\x13maxPagesBeforeSplit\x12.\n" +
	"\x13sliding_window_size\x18\b \x01(\x05R\x11slidingWindowSize\"\xcf\x02\n" +
	"\rCacheContract\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12'\n" +
	"\x0fcollection_name\x18\x02 \x01(\tR\x0ecollectionName\x12\x1b\n" +
	"\tcache_hit\x18\x04 \x01(\bR\bcacheHit\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12?\n" +
	"\x10embedding_lookup\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\x0fembeddingLookup\x12@\n" +
	"\x0fmetadata_lookup\x18\a \x01(\v2\x17.google.protobuf.StructR\x0emetadataLookup\x12;\n" +
	"\x1aplain_text_embedding_value\x18\b \x01(\tR\x17plainTextEmbeddingValue\"^\n" +
	"\x17HumanValidationContract\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\bR\brequired\x12'\n" +
	"\x0fbypass_fallback\x18\x02 \x01(\bR\x0ebypassFallback\"\xeb\x02\n" +
	"\x11NodeConfiguration\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12/\n" +
	"\x13system_instructions\x18\x02 \x01(\tR\x12systemInstructions\x12+\n" +
	"\x0fexpected_schema\x18\x03 \x01(\tB\x02\x18\x01R\x0eexpectedSchema\x122\n" +
	"\x15target_worker_subject\x18\x04 \x01(\tR\x13targetWorkerSubject\x12(\n" +
	"\x10state_output_key\x18\x05 \x01(\tR\x0estateOutputKey\x12.\n" +
	"\x13inference_input_key\x18\x06 \x01(\tR\x11inferenceInputKey\x12M\n" +
	"\x16expected_schema_struct\x18\a \x01(\v2\x17.google.protobuf.StructR\x14expectedSchemaStruct\"\x98\x01\n" +
	"\x10ActionDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05rules\x18\x04 \x03(\tR\x05rules\x122\n" +
	"\x15target_worker_subject\x18\x06 \x01(\tR\x13targetWorkerSubject\"\xd5\x01\n" +
	"\x12ActiveJobExecution\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x11job_definition_id\x18\x02 \x01(\tR\x0fjobDefinitionId\x12&\n" +
	"\x0fcurrent_step_id\x18\x03 \x01(\tR\rcurrentStepId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xc6\x02\n" +
	"\x14GenericWorkflowState\x12F\n" +
	"\rcurrent_state\x18\x01 \x01(\x0e2!.document.models.v1.WorkflowStateR\fcurrentState\x12!\n" +
	"\fstate_reason\x18\x02 \x01(\tR\vstateReason\x12<\n" +
	"\rstate_payload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\fstatePayload\x12=\n" +
	"\flast_updated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12F\n" +
	"\bidentity\x18\x05 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"\xb5\x04\n" +
	"\x12ExecuteTaskPayload\x12F\n" +
	"\vnode_config\x18\x01 \x01(\v2%.document.models.v1.NodeConfigurationR\n" +
	"nodeConfig\x12:\n" +
	"\fglobal_state\x18\x02 \x01(\v2\x17.google.protobuf.StructR\vglobalState\x128\n" +
	"\vnode_output\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"nodeOutput\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x127\n" +
	"\x05cache\x18\x05 \x01(\v2!.document.models.v1.CacheContractR\x05cache\x12V\n" +
	"\x10human_validation\x18\x06 \x01(\v2+.document.models.v1.HumanValidationContractR\x0fhumanValidation\x12=\n" +
	"\astorage\x18\a \x01(\v2#.document.models.v1.StorageContractR\astorage\x12\\\n" +
	"\x12document_processor\x18\b \x01(\v2-.document.models.v1.DocumentProcessorContractR\x11documentProcessor\"\x86\x01\n" +
	"\vGlobalState\x127\n" +
	"\n" +
	"functional\x18\x01 \x01(\v2\x17.google.protobuf.StructR\n" +
	"functional\x12>\n" +
	"\x0enon_functional\x18\x02 \x01(\v2\x17.google.protobuf.StructR\rnonFunctional\"\xbe\x04\n" +
	"\x13RootWorkflowPayload\x12\x19\n" +
	"\bgraph_id\x18\x01 \x01(\tR\agraphId\x12&\n" +
	"\x0finitial_node_id\x18\x02 \x01(\tR\rinitialNodeId\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x127\n" +
	"\x05cache\x18\x05 \x01(\v2!.document.models.v1.CacheContractR\x05cache\x12B\n" +
	"\fglobal_state\x18\x06 \x01(\v2\x1f.document.models.v1.GlobalStateR\vglobalState\x12F\n" +
	"\vnode_config\x18\a \x01(\v2%.document.models.v1.NodeConfigurationR\n" +
	"nodeConfig\x12=\n" +
	"\astorage\x18\b \x01(\v2#.document.models.v1.StorageContractR\astorage\x12\\\n" +
	"\x12document_processor\x18\t \x01(\v2-.document.models.v1.DocumentProcessorContractR\x11documentProcessor\x12M\n" +
	"\x16expected_schema_struct\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x14expectedSchemaStruct*\x9a\x01\n" +
	"\vModelChoice\x12\x1c\n" +
	"\x18MODEL_CHOICE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MODEL_CHOICE_EXTRACTION\x10\x01\x12\x1f\n" +
	"\x1bMODEL_CHOICE_CLASSIFICATION\x10\x02\x12\x19\n" +
	"\x15MODEL_CHOICE_PLANNING\x10\x03\x12\x14\n" +
	"\x10MODEL_CHOICE_OCR\x10\x04*\xde\x01\n" +
	"\rWorkflowState\x12\x1e\n" +
	"\x1aWORKFLOW_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WORKFLOW_STATE_PENDING\x10\x01\x12\x1d\n" +
	"\x19WORKFLOW_STATE_PROCESSING\x10\x02\x12\x1c\n" +
	"\x18WORKFLOW_STATE_SUSPENDED\x10\x03\x12\x1c\n" +
	"\x18WORKFLOW_STATE_COMPLETED\x10\x04\x12\x19\n" +
	"\x15WORKFLOW_STATE_FAILED\x10\x05\x12\x1b\n" +
	"\x17WORKFLOW_STATE_CANCELED\x10\x06B;Z$github.com/AndrewK4758/shared_protos\xaa\x02\x12Document.Models.V1b\x06proto3"

var (
	file_models_proto_rawDescOnce sync.Once
	file_models_proto_rawDescData []byte
)

func file_models_proto_rawDescGZIP() []byte {
	file_models_proto_rawDescOnce.Do(func() {
		file_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_proto_rawDesc), len(file_models_proto_rawDesc)))
	})
	return file_models_proto_rawDescData
}

var file_models_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_models_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_models_proto_goTypes = []any{
	(ModelChoice)(0),                  // 0: document.models.v1.ModelChoice
	(WorkflowState)(0),                // 1: document.models.v1.WorkflowState
	(*ErrorContract)(nil),             // 2: document.models.v1.ErrorContract
	(*InfrastructureIdentity)(nil),    // 3: document.models.v1.InfrastructureIdentity
	(*StorageContract)(nil),           // 4: document.models.v1.StorageContract
	(*DocumentProcessorContract)(nil), // 5: document.models.v1.DocumentProcessorContract
	(*CacheContract)(nil),             // 6: document.models.v1.CacheContract
	(*HumanValidationContract)(nil),   // 7: document.models.v1.HumanValidationContract
	(*NodeConfiguration)(nil),         // 8: document.models.v1.NodeConfiguration
	(*ActionDefinition)(nil),          // 9: document.models.v1.ActionDefinition
	(*ActiveJobExecution)(nil),        // 10: document.models.v1.ActiveJobExecution
	(*GenericWorkflowState)(nil),      // 11: document.models.v1.GenericWorkflowState
	(*ExecuteTaskPayload)(nil),        // 12: document.models.v1.ExecuteTaskPayload
	(*GlobalState)(nil),               // 13: document.models.v1.GlobalState
	(*RootWorkflowPayload)(nil),       // 14: document.models.v1.RootWorkflowPayload
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
	(*structpb.Struct)(nil),           // 16: google.protobuf.Struct
	(*anypb.Any)(nil),                 // 17: google.protobuf.Any
}
var file_models_proto_depIdxs = []int32{
	15, // 0: document.models.v1.ErrorContract.timestamp:type_name -> google.protobuf.Timestamp
	16, // 1: document.models.v1.ErrorContract.client_payload:type_name -> google.protobuf.Struct
	17, // 2: document.models.v1.CacheContract.embedding_lookup:type_name -> google.protobuf.Any
	16, // 3: document.models.v1.CacheContract.metadata_lookup:type_name -> google.protobuf.Struct
	16, // 4: document.models.v1.NodeConfiguration.expected_schema_struct:type_name -> google.protobuf.Struct
	1,  // 5: document.models.v1.GenericWorkflowState.current_state:type_name -> document.models.v1.WorkflowState
	16, // 6: document.models.v1.GenericWorkflowState.state_payload:type_name -> google.protobuf.Struct
	15, // 7: document.models.v1.GenericWorkflowState.last_updated:type_name -> google.protobuf.Timestamp
	3,  // 8: document.models.v1.GenericWorkflowState.identity:type_name -> document.models.v1.InfrastructureIdentity
	8,  // 9: document.models.v1.ExecuteTaskPayload.node_config:type_name -> document.models.v1.NodeConfiguration
	16, // 10: document.models.v1.ExecuteTaskPayload.global_state:type_name -> google.protobuf.Struct
	16, // 11: document.models.v1.ExecuteTaskPayload.node_output:type_name -> google.protobuf.Struct
	16, // 12: document.models.v1.ExecuteTaskPayload.metadata:type_name -> google.protobuf.Struct
	6,  // 13: document.models.v1.ExecuteTaskPayload.cache:type_name -> document.models.v1.CacheContract
	7,  // 14: document.models.v1.ExecuteTaskPayload.human_validation:type_name -> document.models.v1.HumanValidationContract
	4,  // 15: document.models.v1.ExecuteTaskPayload.storage:type_name -> document.models.v1.StorageContract
	5,  // 16: document.models.v1.ExecuteTaskPayload.document_processor:type_name -> document.models.v1.DocumentProcessorContract
	16, // 17: document.models.v1.GlobalState.functional:type_name -> google.protobuf.Struct
	16, // 18: document.models.v1.GlobalState.non_functional:type_name -> google.protobuf.Struct
	16, // 19: document.models.v1.RootWorkflowPayload.metadata:type_name -> google.protobuf.Struct
	6,  // 20: document.models.v1.RootWorkflowPayload.cache:type_name -> document.models.v1.CacheContract
	13, // 21: document.models.v1.RootWorkflowPayload.global_state:type_name -> document.models.v1.GlobalState
	8,  // 22: document.models.v1.RootWorkflowPayload.node_config:type_name -> document.models.v1.NodeConfiguration
	4,  // 23: document.models.v1.RootWorkflowPayload.storage:type_name -> document.models.v1.StorageContract
	5,  // 24: document.models.v1.RootWorkflowPayload.document_processor:type_name -> document.models.v1.DocumentProcessorContract
	16, // 25: document.models.v1.RootWorkflowPayload.expected_schema_struct:type_name -> google.protobuf.Struct
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_models_proto_init() }
func file_models_proto_init() {
	if File_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_proto_rawDesc), len(file_models_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_proto_goTypes,
		DependencyIndexes: file_models_proto_depIdxs,
		EnumInfos:         file_models_proto_enumTypes,
		MessageInfos:      file_models_proto_msgTypes,
	}.Build()
	File_models_proto = out.File
	file_models_proto_goTypes = nil
	file_models_proto_depIdxs = nil
}
