// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: models.proto

package shared_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelChoice int32

const (
	ModelChoice_MODEL_CHOICE_UNSPECIFIED    ModelChoice = 0
	ModelChoice_MODEL_CHOICE_EXTRACTION     ModelChoice = 1
	ModelChoice_MODEL_CHOICE_CLASSIFICATION ModelChoice = 2
	ModelChoice_MODEL_CHOICE_PLANNING       ModelChoice = 3
)

// Enum value maps for ModelChoice.
var (
	ModelChoice_name = map[int32]string{
		0: "MODEL_CHOICE_UNSPECIFIED",
		1: "MODEL_CHOICE_EXTRACTION",
		2: "MODEL_CHOICE_CLASSIFICATION",
		3: "MODEL_CHOICE_PLANNING",
	}
	ModelChoice_value = map[string]int32{
		"MODEL_CHOICE_UNSPECIFIED":    0,
		"MODEL_CHOICE_EXTRACTION":     1,
		"MODEL_CHOICE_CLASSIFICATION": 2,
		"MODEL_CHOICE_PLANNING":       3,
	}
)

func (x ModelChoice) Enum() *ModelChoice {
	p := new(ModelChoice)
	*p = x
	return p
}

func (x ModelChoice) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelChoice) Descriptor() protoreflect.EnumDescriptor {
	return file_models_proto_enumTypes[0].Descriptor()
}

func (ModelChoice) Type() protoreflect.EnumType {
	return &file_models_proto_enumTypes[0]
}

func (x ModelChoice) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelChoice.Descriptor instead.
func (ModelChoice) EnumDescriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{0}
}

type OrchestratorPrimitive int32

const (
	OrchestratorPrimitive_PRIMITIVE_UNSPECIFIED OrchestratorPrimitive = 0
	OrchestratorPrimitive_PRIMITIVE_AI_STEP     OrchestratorPrimitive = 1
	OrchestratorPrimitive_PRIMITIVE_HUMAN_STEP  OrchestratorPrimitive = 2
)

// Enum value maps for OrchestratorPrimitive.
var (
	OrchestratorPrimitive_name = map[int32]string{
		0: "PRIMITIVE_UNSPECIFIED",
		1: "PRIMITIVE_AI_STEP",
		2: "PRIMITIVE_HUMAN_STEP",
	}
	OrchestratorPrimitive_value = map[string]int32{
		"PRIMITIVE_UNSPECIFIED": 0,
		"PRIMITIVE_AI_STEP":     1,
		"PRIMITIVE_HUMAN_STEP":  2,
	}
)

func (x OrchestratorPrimitive) Enum() *OrchestratorPrimitive {
	p := new(OrchestratorPrimitive)
	*p = x
	return p
}

func (x OrchestratorPrimitive) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrchestratorPrimitive) Descriptor() protoreflect.EnumDescriptor {
	return file_models_proto_enumTypes[1].Descriptor()
}

func (OrchestratorPrimitive) Type() protoreflect.EnumType {
	return &file_models_proto_enumTypes[1]
}

func (x OrchestratorPrimitive) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrchestratorPrimitive.Descriptor instead.
func (OrchestratorPrimitive) EnumDescriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{1}
}

type ActionDefinition struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Prompt                string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Rules                 []string               `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	ExpectedOutputSchema  string                 `protobuf:"bytes,5,opt,name=expected_output_schema,json=expectedOutputSchema,proto3" json:"expected_output_schema,omitempty"`
	OrchestratorPrimitive string                 `protobuf:"bytes,6,opt,name=orchestrator_primitive,json=orchestratorPrimitive,proto3" json:"orchestrator_primitive,omitempty"`
	PrimitiveType         OrchestratorPrimitive  `protobuf:"varint,7,opt,name=primitive_type,json=primitiveType,proto3,enum=document.models.v1.OrchestratorPrimitive" json:"primitive_type,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ActionDefinition) Reset() {
	*x = ActionDefinition{}
	mi := &file_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionDefinition) ProtoMessage() {}

func (x *ActionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionDefinition.ProtoReflect.Descriptor instead.
func (*ActionDefinition) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{0}
}

func (x *ActionDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionDefinition) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ActionDefinition) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ActionDefinition) GetExpectedOutputSchema() string {
	if x != nil {
		return x.ExpectedOutputSchema
	}
	return ""
}

func (x *ActionDefinition) GetOrchestratorPrimitive() string {
	if x != nil {
		return x.OrchestratorPrimitive
	}
	return ""
}

func (x *ActionDefinition) GetPrimitiveType() OrchestratorPrimitive {
	if x != nil {
		return x.PrimitiveType
	}
	return OrchestratorPrimitive_PRIMITIVE_UNSPECIFIED
}

type JobDefinition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               int32                  `protobuf:"varint,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	GlobalInstructions string                 `protobuf:"bytes,4,opt,name=global_instructions,json=globalInstructions,proto3" json:"global_instructions,omitempty"`
	IsActive           bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	InitialStepId      string                 `protobuf:"bytes,6,opt,name=initial_step_id,json=initialStepId,proto3" json:"initial_step_id,omitempty"`
	SystemContext      string                 `protobuf:"bytes,7,opt,name=system_context,json=systemContext,proto3" json:"system_context,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobDefinition) Reset() {
	*x = JobDefinition{}
	mi := &file_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDefinition) ProtoMessage() {}

func (x *JobDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDefinition.ProtoReflect.Descriptor instead.
func (*JobDefinition) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{1}
}

func (x *JobDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobDefinition) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *JobDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobDefinition) GetGlobalInstructions() string {
	if x != nil {
		return x.GlobalInstructions
	}
	return ""
}

func (x *JobDefinition) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *JobDefinition) GetInitialStepId() string {
	if x != nil {
		return x.InitialStepId
	}
	return ""
}

func (x *JobDefinition) GetSystemContext() string {
	if x != nil {
		return x.SystemContext
	}
	return ""
}

type StepDefinition struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StepName             string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	CustomInstructions   string                 `protobuf:"bytes,3,opt,name=custom_instructions,json=customInstructions,proto3" json:"custom_instructions,omitempty"`
	ExpectedSchema       string                 `protobuf:"bytes,4,opt,name=expected_schema,json=expectedSchema,proto3" json:"expected_schema,omitempty"`
	ReadsFromStateKey    string                 `protobuf:"bytes,5,opt,name=reads_from_state_key,json=readsFromStateKey,proto3" json:"reads_from_state_key,omitempty"`
	WritesToStateKey     string                 `protobuf:"bytes,6,opt,name=writes_to_state_key,json=writesToStateKey,proto3" json:"writes_to_state_key,omitempty"`
	RequireHumanReview   bool                   `protobuf:"varint,7,opt,name=require_human_review,json=requireHumanReview,proto3" json:"require_human_review,omitempty"`
	BypassHumanFallback  bool                   `protobuf:"varint,8,opt,name=bypass_human_fallback,json=bypassHumanFallback,proto3" json:"bypass_human_fallback,omitempty"`
	DynamicRuleTableName string                 `protobuf:"bytes,9,opt,name=dynamic_rule_table_name,json=dynamicRuleTableName,proto3" json:"dynamic_rule_table_name,omitempty"`
	DynamicRuleStateKey  string                 `protobuf:"bytes,10,opt,name=dynamic_rule_state_key,json=dynamicRuleStateKey,proto3" json:"dynamic_rule_state_key,omitempty"`
	ContextInput         string                 `protobuf:"bytes,11,opt,name=context_input,json=contextInput,proto3" json:"context_input,omitempty"`
	UseCache             bool                   `protobuf:"varint,12,opt,name=use_cache,json=useCache,proto3" json:"use_cache,omitempty"`                 // Deprecated: Use cache_config instead
	CacheKeyInput        string                 `protobuf:"bytes,13,opt,name=cache_key_input,json=cacheKeyInput,proto3" json:"cache_key_input,omitempty"` // Deprecated: Use cache_config instead
	CacheConfig          *CacheConfiguration    `protobuf:"bytes,14,opt,name=cache_config,json=cacheConfig,proto3" json:"cache_config,omitempty"`
	StepPrimitive        OrchestratorPrimitive  `protobuf:"varint,15,opt,name=step_primitive,json=stepPrimitive,proto3,enum=document.models.v1.OrchestratorPrimitive" json:"step_primitive,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StepDefinition) Reset() {
	*x = StepDefinition{}
	mi := &file_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepDefinition) ProtoMessage() {}

func (x *StepDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepDefinition.ProtoReflect.Descriptor instead.
func (*StepDefinition) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{2}
}

func (x *StepDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StepDefinition) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StepDefinition) GetCustomInstructions() string {
	if x != nil {
		return x.CustomInstructions
	}
	return ""
}

func (x *StepDefinition) GetExpectedSchema() string {
	if x != nil {
		return x.ExpectedSchema
	}
	return ""
}

func (x *StepDefinition) GetReadsFromStateKey() string {
	if x != nil {
		return x.ReadsFromStateKey
	}
	return ""
}

func (x *StepDefinition) GetWritesToStateKey() string {
	if x != nil {
		return x.WritesToStateKey
	}
	return ""
}

func (x *StepDefinition) GetRequireHumanReview() bool {
	if x != nil {
		return x.RequireHumanReview
	}
	return false
}

func (x *StepDefinition) GetBypassHumanFallback() bool {
	if x != nil {
		return x.BypassHumanFallback
	}
	return false
}

func (x *StepDefinition) GetDynamicRuleTableName() string {
	if x != nil {
		return x.DynamicRuleTableName
	}
	return ""
}

func (x *StepDefinition) GetDynamicRuleStateKey() string {
	if x != nil {
		return x.DynamicRuleStateKey
	}
	return ""
}

func (x *StepDefinition) GetContextInput() string {
	if x != nil {
		return x.ContextInput
	}
	return ""
}

func (x *StepDefinition) GetUseCache() bool {
	if x != nil {
		return x.UseCache
	}
	return false
}

func (x *StepDefinition) GetCacheKeyInput() string {
	if x != nil {
		return x.CacheKeyInput
	}
	return ""
}

func (x *StepDefinition) GetCacheConfig() *CacheConfiguration {
	if x != nil {
		return x.CacheConfig
	}
	return nil
}

func (x *StepDefinition) GetStepPrimitive() OrchestratorPrimitive {
	if x != nil {
		return x.StepPrimitive
	}
	return OrchestratorPrimitive_PRIMITIVE_UNSPECIFIED
}

type CacheConfiguration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UseCache       bool                   `protobuf:"varint,1,opt,name=use_cache,json=useCache,proto3" json:"use_cache,omitempty"`
	CollectionName string                 `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	CacheInput     string                 `protobuf:"bytes,3,opt,name=cache_input,json=cacheInput,proto3" json:"cache_input,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Threshold      float32                `protobuf:"fixed32,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CacheConfiguration) Reset() {
	*x = CacheConfiguration{}
	mi := &file_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheConfiguration) ProtoMessage() {}

func (x *CacheConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheConfiguration.ProtoReflect.Descriptor instead.
func (*CacheConfiguration) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{3}
}

func (x *CacheConfiguration) GetUseCache() bool {
	if x != nil {
		return x.UseCache
	}
	return false
}

func (x *CacheConfiguration) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CacheConfiguration) GetCacheInput() string {
	if x != nil {
		return x.CacheInput
	}
	return ""
}

func (x *CacheConfiguration) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CacheConfiguration) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type JobWorkflowEdge struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JobDefinitionId     string                 `protobuf:"bytes,2,opt,name=job_definition_id,json=jobDefinitionId,proto3" json:"job_definition_id,omitempty"`
	SourceStepId        string                 `protobuf:"bytes,3,opt,name=source_step_id,json=sourceStepId,proto3" json:"source_step_id,omitempty"`
	ConditionStateKey   string                 `protobuf:"bytes,4,opt,name=condition_state_key,json=conditionStateKey,proto3" json:"condition_state_key,omitempty"`
	ConditionMatchValue string                 `protobuf:"bytes,5,opt,name=condition_match_value,json=conditionMatchValue,proto3" json:"condition_match_value,omitempty"`
	TargetStepId        string                 `protobuf:"bytes,6,opt,name=target_step_id,json=targetStepId,proto3" json:"target_step_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *JobWorkflowEdge) Reset() {
	*x = JobWorkflowEdge{}
	mi := &file_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobWorkflowEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobWorkflowEdge) ProtoMessage() {}

func (x *JobWorkflowEdge) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobWorkflowEdge.ProtoReflect.Descriptor instead.
func (*JobWorkflowEdge) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{4}
}

func (x *JobWorkflowEdge) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobWorkflowEdge) GetJobDefinitionId() string {
	if x != nil {
		return x.JobDefinitionId
	}
	return ""
}

func (x *JobWorkflowEdge) GetSourceStepId() string {
	if x != nil {
		return x.SourceStepId
	}
	return ""
}

func (x *JobWorkflowEdge) GetConditionStateKey() string {
	if x != nil {
		return x.ConditionStateKey
	}
	return ""
}

func (x *JobWorkflowEdge) GetConditionMatchValue() string {
	if x != nil {
		return x.ConditionMatchValue
	}
	return ""
}

func (x *JobWorkflowEdge) GetTargetStepId() string {
	if x != nil {
		return x.TargetStepId
	}
	return ""
}

type ActiveJobExecution struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobDefinitionId string                 `protobuf:"bytes,2,opt,name=job_definition_id,json=jobDefinitionId,proto3" json:"job_definition_id,omitempty"`
	CurrentStepId   string                 `protobuf:"bytes,3,opt,name=current_step_id,json=currentStepId,proto3" json:"current_step_id,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActiveJobExecution) Reset() {
	*x = ActiveJobExecution{}
	mi := &file_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveJobExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveJobExecution) ProtoMessage() {}

func (x *ActiveJobExecution) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveJobExecution.ProtoReflect.Descriptor instead.
func (*ActiveJobExecution) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{5}
}

func (x *ActiveJobExecution) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ActiveJobExecution) GetJobDefinitionId() string {
	if x != nil {
		return x.JobDefinitionId
	}
	return ""
}

func (x *ActiveJobExecution) GetCurrentStepId() string {
	if x != nil {
		return x.CurrentStepId
	}
	return ""
}

func (x *ActiveJobExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActiveJobExecution) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ActiveJobExecution) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type WorkflowContext struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ActiveExecution    *ActiveJobExecution    `protobuf:"bytes,3,opt,name=active_execution,json=activeExecution,proto3" json:"active_execution,omitempty"`
	JobDefinition      *JobDefinition         `protobuf:"bytes,4,opt,name=job_definition,json=jobDefinition,proto3" json:"job_definition,omitempty"`
	GlobalState        *structpb.Struct       `protobuf:"bytes,6,opt,name=global_state,json=globalState,proto3" json:"global_state,omitempty"`
	CurrentStepIndex   int32                  `protobuf:"varint,7,opt,name=current_step_index,json=currentStepIndex,proto3" json:"current_step_index,omitempty"`
	PendingActions     []*ActionDefinition    `protobuf:"bytes,8,rep,name=pending_actions,json=pendingActions,proto3" json:"pending_actions,omitempty"`
	CurrentActionIndex int32                  `protobuf:"varint,9,opt,name=current_action_index,json=currentActionIndex,proto3" json:"current_action_index,omitempty"`
	ActionState        *structpb.Struct       `protobuf:"bytes,10,opt,name=action_state,json=actionState,proto3" json:"action_state,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowContext) Reset() {
	*x = WorkflowContext{}
	mi := &file_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContext) ProtoMessage() {}

func (x *WorkflowContext) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContext.ProtoReflect.Descriptor instead.
func (*WorkflowContext) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowContext) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *WorkflowContext) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowContext) GetActiveExecution() *ActiveJobExecution {
	if x != nil {
		return x.ActiveExecution
	}
	return nil
}

func (x *WorkflowContext) GetJobDefinition() *JobDefinition {
	if x != nil {
		return x.JobDefinition
	}
	return nil
}

func (x *WorkflowContext) GetGlobalState() *structpb.Struct {
	if x != nil {
		return x.GlobalState
	}
	return nil
}

func (x *WorkflowContext) GetCurrentStepIndex() int32 {
	if x != nil {
		return x.CurrentStepIndex
	}
	return 0
}

func (x *WorkflowContext) GetPendingActions() []*ActionDefinition {
	if x != nil {
		return x.PendingActions
	}
	return nil
}

func (x *WorkflowContext) GetCurrentActionIndex() int32 {
	if x != nil {
		return x.CurrentActionIndex
	}
	return 0
}

func (x *WorkflowContext) GetActionState() *structpb.Struct {
	if x != nil {
		return x.ActionState
	}
	return nil
}

var File_models_proto protoreflect.FileDescriptor

const file_models_proto_rawDesc = "" +
	"\n" +
	"\fmodels.proto\x12\x12document.models.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xa3\x02\n" +
	"\x10ActionDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05rules\x18\x04 \x03(\tR\x05rules\x124\n" +
	"\x16expected_output_schema\x18\x05 \x01(\tR\x14expectedOutputSchema\x125\n" +
	"\x16orchestrator_primitive\x18\x06 \x01(\tR\x15orchestratorPrimitive\x12P\n" +
	"\x0eprimitive_type\x18\a \x01(\x0e2).document.models.v1.OrchestratorPrimitiveR\rprimitiveType\"\xf2\x01\n" +
	"\rJobDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\x05R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12/\n" +
	"\x13global_instructions\x18\x04 \x01(\tR\x12globalInstructions\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12&\n" +
	"\x0finitial_step_id\x18\x06 \x01(\tR\rinitialStepId\x12%\n" +
	"\x0esystem_context\x18\a \x01(\tR\rsystemContext\"\xd0\x05\n" +
	"\x0eStepDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12/\n" +
	"\x13custom_instructions\x18\x03 \x01(\tR\x12customInstructions\x12'\n" +
	"\x0fexpected_schema\x18\x04 \x01(\tR\x0eexpectedSchema\x12/\n" +
	"\x14reads_from_state_key\x18\x05 \x01(\tR\x11readsFromStateKey\x12-\n" +
	"\x13writes_to_state_key\x18\x06 \x01(\tR\x10writesToStateKey\x120\n" +
	"\x14require_human_review\x18\a \x01(\bR\x12requireHumanReview\x122\n" +
	"\x15bypass_human_fallback\x18\b \x01(\bR\x13bypassHumanFallback\x125\n" +
	"\x17dynamic_rule_table_name\x18\t \x01(\tR\x14dynamicRuleTableName\x123\n" +
	"\x16dynamic_rule_state_key\x18\n" +
	" \x01(\tR\x13dynamicRuleStateKey\x12#\n" +
	"\rcontext_input\x18\v \x01(\tR\fcontextInput\x12\x1b\n" +
	"\tuse_cache\x18\f \x01(\bR\buseCache\x12&\n" +
	"\x0fcache_key_input\x18\r \x01(\tR\rcacheKeyInput\x12I\n" +
	"\fcache_config\x18\x0e \x01(\v2&.document.models.v1.CacheConfigurationR\vcacheConfig\x12P\n" +
	"\x0estep_primitive\x18\x0f \x01(\x0e2).document.models.v1.OrchestratorPrimitiveR\rstepPrimitive\"\xce\x01\n" +
	"\x12CacheConfiguration\x12\x1b\n" +
	"\tuse_cache\x18\x01 \x01(\bR\buseCache\x12'\n" +
	"\x0fcollection_name\x18\x02 \x01(\tR\x0ecollectionName\x12\x1f\n" +
	"\vcache_input\x18\x03 \x01(\tR\n" +
	"cacheInput\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x02R\tthreshold\"\xfd\x01\n" +
	"\x0fJobWorkflowEdge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12*\n" +
	"\x11job_definition_id\x18\x02 \x01(\tR\x0fjobDefinitionId\x12$\n" +
	"\x0esource_step_id\x18\x03 \x01(\tR\fsourceStepId\x12.\n" +
	"\x13condition_state_key\x18\x04 \x01(\tR\x11conditionStateKey\x122\n" +
	"\x15condition_match_value\x18\x05 \x01(\tR\x13conditionMatchValue\x12$\n" +
	"\x0etarget_step_id\x18\x06 \x01(\tR\ftargetStepId\"\xd5\x01\n" +
	"\x12ActiveJobExecution\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x11job_definition_id\x18\x02 \x01(\tR\x0fjobDefinitionId\x12&\n" +
	"\x0fcurrent_step_id\x18\x03 \x01(\tR\rcurrentStepId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xfe\x04\n" +
	"\x0fWorkflowContext\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12M\n" +
	"\bmetadata\x18\x02 \x03(\v21.document.models.v1.WorkflowContext.MetadataEntryR\bmetadata\x12Q\n" +
	"\x10active_execution\x18\x03 \x01(\v2&.document.models.v1.ActiveJobExecutionR\x0factiveExecution\x12H\n" +
	"\x0ejob_definition\x18\x04 \x01(\v2!.document.models.v1.JobDefinitionR\rjobDefinition\x12:\n" +
	"\fglobal_state\x18\x06 \x01(\v2\x17.google.protobuf.StructR\vglobalState\x12,\n" +
	"\x12current_step_index\x18\a \x01(\x05R\x10currentStepIndex\x12M\n" +
	"\x0fpending_actions\x18\b \x03(\v2$.document.models.v1.ActionDefinitionR\x0ependingActions\x120\n" +
	"\x14current_action_index\x18\t \x01(\x05R\x12currentActionIndex\x12:\n" +
	"\faction_state\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\vactionState\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x05\x10\x06*\x84\x01\n" +
	"\vModelChoice\x12\x1c\n" +
	"\x18MODEL_CHOICE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MODEL_CHOICE_EXTRACTION\x10\x01\x12\x1f\n" +
	"\x1bMODEL_CHOICE_CLASSIFICATION\x10\x02\x12\x19\n" +
	"\x15MODEL_CHOICE_PLANNING\x10\x03*c\n" +
	"\x15OrchestratorPrimitive\x12\x19\n" +
	"\x15PRIMITIVE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PRIMITIVE_AI_STEP\x10\x01\x12\x18\n" +
	"\x14PRIMITIVE_HUMAN_STEP\x10\x02B;Z$github.com/AndrewK4758/shared_protos\xaa\x02\x12Document.Models.V1b\x06proto3"

var (
	file_models_proto_rawDescOnce sync.Once
	file_models_proto_rawDescData []byte
)

func file_models_proto_rawDescGZIP() []byte {
	file_models_proto_rawDescOnce.Do(func() {
		file_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_proto_rawDesc), len(file_models_proto_rawDesc)))
	})
	return file_models_proto_rawDescData
}

var file_models_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_models_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_models_proto_goTypes = []any{
	(ModelChoice)(0),           // 0: document.models.v1.ModelChoice
	(OrchestratorPrimitive)(0), // 1: document.models.v1.OrchestratorPrimitive
	(*ActionDefinition)(nil),   // 2: document.models.v1.ActionDefinition
	(*JobDefinition)(nil),      // 3: document.models.v1.JobDefinition
	(*StepDefinition)(nil),     // 4: document.models.v1.StepDefinition
	(*CacheConfiguration)(nil), // 5: document.models.v1.CacheConfiguration
	(*JobWorkflowEdge)(nil),    // 6: document.models.v1.JobWorkflowEdge
	(*ActiveJobExecution)(nil), // 7: document.models.v1.ActiveJobExecution
	(*WorkflowContext)(nil),    // 8: document.models.v1.WorkflowContext
	nil,                        // 9: document.models.v1.WorkflowContext.MetadataEntry
	(*structpb.Struct)(nil),    // 10: google.protobuf.Struct
}
var file_models_proto_depIdxs = []int32{
	1,  // 0: document.models.v1.ActionDefinition.primitive_type:type_name -> document.models.v1.OrchestratorPrimitive
	5,  // 1: document.models.v1.StepDefinition.cache_config:type_name -> document.models.v1.CacheConfiguration
	1,  // 2: document.models.v1.StepDefinition.step_primitive:type_name -> document.models.v1.OrchestratorPrimitive
	10, // 3: document.models.v1.CacheConfiguration.metadata:type_name -> google.protobuf.Struct
	9,  // 4: document.models.v1.WorkflowContext.metadata:type_name -> document.models.v1.WorkflowContext.MetadataEntry
	7,  // 5: document.models.v1.WorkflowContext.active_execution:type_name -> document.models.v1.ActiveJobExecution
	3,  // 6: document.models.v1.WorkflowContext.job_definition:type_name -> document.models.v1.JobDefinition
	10, // 7: document.models.v1.WorkflowContext.global_state:type_name -> google.protobuf.Struct
	2,  // 8: document.models.v1.WorkflowContext.pending_actions:type_name -> document.models.v1.ActionDefinition
	10, // 9: document.models.v1.WorkflowContext.action_state:type_name -> google.protobuf.Struct
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_models_proto_init() }
func file_models_proto_init() {
	if File_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_proto_rawDesc), len(file_models_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_proto_goTypes,
		DependencyIndexes: file_models_proto_depIdxs,
		EnumInfos:         file_models_proto_enumTypes,
		MessageInfos:      file_models_proto_msgTypes,
	}.Build()
	File_models_proto = out.File
	file_models_proto_goTypes = nil
	file_models_proto_depIdxs = nil
}
