// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: orchestrator.proto

package shared_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitJobRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Context           *WorkflowContext       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Steps             []*StepDefinition      `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	JobGraph          []*JobWorkflowEdge     `protobuf:"bytes,4,rep,name=job_graph,json=jobGraph,proto3" json:"job_graph,omitempty"`
	ModelChoice       ModelChoice            `protobuf:"varint,7,opt,name=model_choice,json=modelChoice,proto3,enum=document.models.v1.ModelChoice" json:"model_choice,omitempty"`
	TargetFields      []string               `protobuf:"bytes,8,rep,name=target_fields,json=targetFields,proto3" json:"target_fields,omitempty"`
	ActionDefinitions []*ActionDefinition    `protobuf:"bytes,10,rep,name=action_definitions,json=actionDefinitions,proto3" json:"action_definitions,omitempty"`
	CallbackAddress   string                 `protobuf:"bytes,11,opt,name=callback_address,json=callbackAddress,proto3" json:"callback_address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetContext() *WorkflowContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SubmitJobRequest) GetSteps() []*StepDefinition {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *SubmitJobRequest) GetJobGraph() []*JobWorkflowEdge {
	if x != nil {
		return x.JobGraph
	}
	return nil
}

func (x *SubmitJobRequest) GetModelChoice() ModelChoice {
	if x != nil {
		return x.ModelChoice
	}
	return ModelChoice_MODEL_CHOICE_UNSPECIFIED
}

func (x *SubmitJobRequest) GetTargetFields() []string {
	if x != nil {
		return x.TargetFields
	}
	return nil
}

func (x *SubmitJobRequest) GetActionDefinitions() []*ActionDefinition {
	if x != nil {
		return x.ActionDefinitions
	}
	return nil
}

func (x *SubmitJobRequest) GetCallbackAddress() string {
	if x != nil {
		return x.CallbackAddress
	}
	return ""
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // e.g., "CACHED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StartJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobRequest) Reset() {
	*x = StartJobRequest{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobRequest) ProtoMessage() {}

func (x *StartJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobRequest.ProtoReflect.Descriptor instead.
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *StartJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StartJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ActiveStepId  string                 `protobuf:"bytes,3,opt,name=active_step_id,json=activeStepId,proto3" json:"active_step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobResponse) Reset() {
	*x = StartJobResponse{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobResponse) ProtoMessage() {}

func (x *StartJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobResponse.ProtoReflect.Descriptor instead.
func (*StartJobResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *StartJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartJobResponse) GetActiveStepId() string {
	if x != nil {
		return x.ActiveStepId
	}
	return ""
}

type SubmitStepRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StepId             string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	CustomInstructions string                 `protobuf:"bytes,3,opt,name=custom_instructions,json=customInstructions,proto3" json:"custom_instructions,omitempty"`
	ExpectedSchema     string                 `protobuf:"bytes,4,opt,name=expected_schema,json=expectedSchema,proto3" json:"expected_schema,omitempty"`
	CompleteJob        bool                   `protobuf:"varint,5,opt,name=complete_job,json=completeJob,proto3" json:"complete_job,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubmitStepRequest) Reset() {
	*x = SubmitStepRequest{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitStepRequest) ProtoMessage() {}

func (x *SubmitStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitStepRequest.ProtoReflect.Descriptor instead.
func (*SubmitStepRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitStepRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitStepRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *SubmitStepRequest) GetCustomInstructions() string {
	if x != nil {
		return x.CustomInstructions
	}
	return ""
}

func (x *SubmitStepRequest) GetExpectedSchema() string {
	if x != nil {
		return x.ExpectedSchema
	}
	return ""
}

func (x *SubmitStepRequest) GetCompleteJob() bool {
	if x != nil {
		return x.CompleteJob
	}
	return false
}

type SubmitStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"` // Unique ID for tracking this specific step execution
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitStepResponse) Reset() {
	*x = SubmitStepResponse{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitStepResponse) ProtoMessage() {}

func (x *SubmitStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitStepResponse.ProtoReflect.Descriptor instead.
func (*SubmitStepResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitStepResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitStepResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitStepResponse) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

type ListenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenRequest) Reset() {
	*x = ListenRequest{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenRequest) ProtoMessage() {}

func (x *ListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenRequest.ProtoReflect.Descriptor instead.
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *ListenRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ProgressUpdate struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	JobId   string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status  string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // e.g., "CHUNKING", "PROCESSING", "STITCHING", "COMPLETE", "FAILED"
	Message string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Detailed message, e.g., "Processing chunk 2 of 5"
	// Only populated when status == "COMPLETE"
	FinalResultsJson string `protobuf:"bytes,4,opt,name=final_results_json,json=finalResultsJson,proto3" json:"final_results_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *ProgressUpdate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProgressUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressUpdate) GetFinalResultsJson() string {
	if x != nil {
		return x.FinalResultsJson
	}
	return ""
}

type ResumeJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CorrectedJson string                 `protobuf:"bytes,2,opt,name=corrected_json,json=correctedJson,proto3" json:"corrected_json,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeJobRequest) Reset() {
	*x = ResumeJobRequest{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeJobRequest) ProtoMessage() {}

func (x *ResumeJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeJobRequest.ProtoReflect.Descriptor instead.
func (*ResumeJobRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *ResumeJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ResumeJobRequest) GetCorrectedJson() string {
	if x != nil {
		return x.CorrectedJson
	}
	return ""
}

func (x *ResumeJobRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

type ResumeJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeJobResponse) Reset() {
	*x = ResumeJobResponse{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeJobResponse) ProtoMessage() {}

func (x *ResumeJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeJobResponse.ProtoReflect.Descriptor instead.
func (*ResumeJobResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *ResumeJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StepCompleteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobDefinitionId string                 `protobuf:"bytes,2,opt,name=job_definition_id,json=jobDefinitionId,proto3" json:"job_definition_id,omitempty"` // Extracted from ActiveJobExecution / Context
	CompletedStepId string                 `protobuf:"bytes,3,opt,name=completed_step_id,json=completedStepId,proto3" json:"completed_step_id,omitempty"`
	GlobalState     *structpb.Struct       `protobuf:"bytes,4,opt,name=global_state,json=globalState,proto3" json:"global_state,omitempty"` // Contains extracted data to evaluate routing rules
	StepOutput      *structpb.Struct       `protobuf:"bytes,5,opt,name=step_output,json=stepOutput,proto3" json:"step_output,omitempty"`    // The isolated output of the step that just completed
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StepCompleteRequest) Reset() {
	*x = StepCompleteRequest{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepCompleteRequest) ProtoMessage() {}

func (x *StepCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepCompleteRequest.ProtoReflect.Descriptor instead.
func (*StepCompleteRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *StepCompleteRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StepCompleteRequest) GetJobDefinitionId() string {
	if x != nil {
		return x.JobDefinitionId
	}
	return ""
}

func (x *StepCompleteRequest) GetCompletedStepId() string {
	if x != nil {
		return x.CompletedStepId
	}
	return ""
}

func (x *StepCompleteRequest) GetGlobalState() *structpb.Struct {
	if x != nil {
		return x.GlobalState
	}
	return nil
}

func (x *StepCompleteRequest) GetStepOutput() *structpb.Struct {
	if x != nil {
		return x.StepOutput
	}
	return nil
}

type StepCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepCompleteResponse) Reset() {
	*x = StepCompleteResponse{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepCompleteResponse) ProtoMessage() {}

func (x *StepCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepCompleteResponse.ProtoReflect.Descriptor instead.
func (*StepCompleteResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *StepCompleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type JobFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	FailedStepId  string                 `protobuf:"bytes,2,opt,name=failed_step_id,json=failedStepId,proto3" json:"failed_step_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFailedRequest) Reset() {
	*x = JobFailedRequest{}
	mi := &file_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFailedRequest) ProtoMessage() {}

func (x *JobFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFailedRequest.ProtoReflect.Descriptor instead.
func (*JobFailedRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *JobFailedRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobFailedRequest) GetFailedStepId() string {
	if x != nil {
		return x.FailedStepId
	}
	return ""
}

func (x *JobFailedRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type JobFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFailedResponse) Reset() {
	*x = JobFailedResponse{}
	mi := &file_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFailedResponse) ProtoMessage() {}

func (x *JobFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFailedResponse.ProtoReflect.Descriptor instead.
func (*JobFailedResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *JobFailedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetJobDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobDetailsRequest) Reset() {
	*x = GetJobDetailsRequest{}
	mi := &file_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobDetailsRequest) ProtoMessage() {}

func (x *GetJobDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetJobDetailsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *GetJobDetailsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobDetailsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Found           bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	OriginalRequest *SubmitJobRequest      `protobuf:"bytes,2,opt,name=original_request,json=originalRequest,proto3" json:"original_request,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetJobDetailsResponse) Reset() {
	*x = GetJobDetailsResponse{}
	mi := &file_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobDetailsResponse) ProtoMessage() {}

func (x *GetJobDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetJobDetailsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *GetJobDetailsResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetJobDetailsResponse) GetOriginalRequest() *SubmitJobRequest {
	if x != nil {
		return x.OriginalRequest
	}
	return nil
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\x18document.orchestrator.v1\x1a\x0fprocessor.proto\x1a\fmodels.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb6\x03\n" +
	"\x10SubmitJobRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.document.models.v1.WorkflowContextR\acontext\x128\n" +
	"\x05steps\x18\x03 \x03(\v2\".document.models.v1.StepDefinitionR\x05steps\x12@\n" +
	"\tjob_graph\x18\x04 \x03(\v2#.document.models.v1.JobWorkflowEdgeR\bjobGraph\x12B\n" +
	"\fmodel_choice\x18\a \x01(\x0e2\x1f.document.models.v1.ModelChoiceR\vmodelChoice\x12#\n" +
	"\rtarget_fields\x18\b \x03(\tR\ftargetFields\x12S\n" +
	"\x12action_definitions\x18\n" +
	" \x03(\v2$.document.models.v1.ActionDefinitionR\x11actionDefinitions\x12)\n" +
	"\x10callback_address\x18\v \x01(\tR\x0fcallbackAddress\"B\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"(\n" +
	"\x0fStartJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"l\n" +
	"\x10StartJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x0eactive_step_id\x18\x03 \x01(\tR\factiveStepId\"\xc0\x01\n" +
	"\x11SubmitStepRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12/\n" +
	"\x13custom_instructions\x18\x03 \x01(\tR\x12customInstructions\x12'\n" +
	"\x0fexpected_schema\x18\x04 \x01(\tR\x0eexpectedSchema\x12!\n" +
	"\fcomplete_job\x18\x05 \x01(\bR\vcompleteJob\"a\n" +
	"\x12SubmitStepResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\"&\n" +
	"\rListenRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x87\x01\n" +
	"\x0eProgressUpdate\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12,\n" +
	"\x12final_results_json\x18\x04 \x01(\tR\x10finalResultsJson\"i\n" +
	"\x10ResumeJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x0ecorrected_json\x18\x02 \x01(\tR\rcorrectedJson\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\"G\n" +
	"\x11ResumeJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfa\x01\n" +
	"\x13StepCompleteRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x11job_definition_id\x18\x02 \x01(\tR\x0fjobDefinitionId\x12*\n" +
	"\x11completed_step_id\x18\x03 \x01(\tR\x0fcompletedStepId\x12:\n" +
	"\fglobal_state\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vglobalState\x128\n" +
	"\vstep_output\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"stepOutput\"0\n" +
	"\x14StepCompleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"t\n" +
	"\x10JobFailedRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12$\n" +
	"\x0efailed_step_id\x18\x02 \x01(\tR\ffailedStepId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"-\n" +
	"\x11JobFailedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x14GetJobDetailsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x84\x01\n" +
	"\x15GetJobDetailsResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12U\n" +
	"\x10original_request\x18\x02 \x01(\v2*.document.orchestrator.v1.SubmitJobRequestR\x0foriginalRequest2\x97\x04\n" +
	"\x13OrchestratorService\x12d\n" +
	"\tSubmitJob\x12*.document.orchestrator.v1.SubmitJobRequest\x1a+.document.orchestrator.v1.SubmitJobResponse\x12a\n" +
	"\bStartJob\x12).document.orchestrator.v1.StartJobRequest\x1a*.document.orchestrator.v1.StartJobResponse\x12g\n" +
	"\n" +
	"SubmitStep\x12+.document.orchestrator.v1.SubmitStepRequest\x1a,.document.orchestrator.v1.SubmitStepResponse\x12h\n" +
	"\x11ListenForProgress\x12'.document.orchestrator.v1.ListenRequest\x1a(.document.orchestrator.v1.ProgressUpdate0\x01\x12d\n" +
	"\tResumeJob\x12*.document.orchestrator.v1.ResumeJobRequest\x1a+.document.orchestrator.v1.ResumeJobResponse2\xe8\x02\n" +
	"\x1bOrchestratorCallbackService\x12o\n" +
	"\x0eOnStepComplete\x12-.document.orchestrator.v1.StepCompleteRequest\x1a..document.orchestrator.v1.StepCompleteResponse\x12f\n" +
	"\vOnJobFailed\x12*.document.orchestrator.v1.JobFailedRequest\x1a+.document.orchestrator.v1.JobFailedResponse\x12p\n" +
	"\rGetJobDetails\x12..document.orchestrator.v1.GetJobDetailsRequest\x1a/.document.orchestrator.v1.GetJobDetailsResponseBAZ$github.com/AndrewK4758/shared_protos\xaa\x02\x18Document.Orchestrator.V1b\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_orchestrator_proto_goTypes = []any{
	(*SubmitJobRequest)(nil),      // 0: document.orchestrator.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),     // 1: document.orchestrator.v1.SubmitJobResponse
	(*StartJobRequest)(nil),       // 2: document.orchestrator.v1.StartJobRequest
	(*StartJobResponse)(nil),      // 3: document.orchestrator.v1.StartJobResponse
	(*SubmitStepRequest)(nil),     // 4: document.orchestrator.v1.SubmitStepRequest
	(*SubmitStepResponse)(nil),    // 5: document.orchestrator.v1.SubmitStepResponse
	(*ListenRequest)(nil),         // 6: document.orchestrator.v1.ListenRequest
	(*ProgressUpdate)(nil),        // 7: document.orchestrator.v1.ProgressUpdate
	(*ResumeJobRequest)(nil),      // 8: document.orchestrator.v1.ResumeJobRequest
	(*ResumeJobResponse)(nil),     // 9: document.orchestrator.v1.ResumeJobResponse
	(*StepCompleteRequest)(nil),   // 10: document.orchestrator.v1.StepCompleteRequest
	(*StepCompleteResponse)(nil),  // 11: document.orchestrator.v1.StepCompleteResponse
	(*JobFailedRequest)(nil),      // 12: document.orchestrator.v1.JobFailedRequest
	(*JobFailedResponse)(nil),     // 13: document.orchestrator.v1.JobFailedResponse
	(*GetJobDetailsRequest)(nil),  // 14: document.orchestrator.v1.GetJobDetailsRequest
	(*GetJobDetailsResponse)(nil), // 15: document.orchestrator.v1.GetJobDetailsResponse
	(*WorkflowContext)(nil),       // 16: document.models.v1.WorkflowContext
	(*StepDefinition)(nil),        // 17: document.models.v1.StepDefinition
	(*JobWorkflowEdge)(nil),       // 18: document.models.v1.JobWorkflowEdge
	(ModelChoice)(0),              // 19: document.models.v1.ModelChoice
	(*ActionDefinition)(nil),      // 20: document.models.v1.ActionDefinition
	(*structpb.Struct)(nil),       // 21: google.protobuf.Struct
}
var file_orchestrator_proto_depIdxs = []int32{
	16, // 0: document.orchestrator.v1.SubmitJobRequest.context:type_name -> document.models.v1.WorkflowContext
	17, // 1: document.orchestrator.v1.SubmitJobRequest.steps:type_name -> document.models.v1.StepDefinition
	18, // 2: document.orchestrator.v1.SubmitJobRequest.job_graph:type_name -> document.models.v1.JobWorkflowEdge
	19, // 3: document.orchestrator.v1.SubmitJobRequest.model_choice:type_name -> document.models.v1.ModelChoice
	20, // 4: document.orchestrator.v1.SubmitJobRequest.action_definitions:type_name -> document.models.v1.ActionDefinition
	21, // 5: document.orchestrator.v1.StepCompleteRequest.global_state:type_name -> google.protobuf.Struct
	21, // 6: document.orchestrator.v1.StepCompleteRequest.step_output:type_name -> google.protobuf.Struct
	0,  // 7: document.orchestrator.v1.GetJobDetailsResponse.original_request:type_name -> document.orchestrator.v1.SubmitJobRequest
	0,  // 8: document.orchestrator.v1.OrchestratorService.SubmitJob:input_type -> document.orchestrator.v1.SubmitJobRequest
	2,  // 9: document.orchestrator.v1.OrchestratorService.StartJob:input_type -> document.orchestrator.v1.StartJobRequest
	4,  // 10: document.orchestrator.v1.OrchestratorService.SubmitStep:input_type -> document.orchestrator.v1.SubmitStepRequest
	6,  // 11: document.orchestrator.v1.OrchestratorService.ListenForProgress:input_type -> document.orchestrator.v1.ListenRequest
	8,  // 12: document.orchestrator.v1.OrchestratorService.ResumeJob:input_type -> document.orchestrator.v1.ResumeJobRequest
	10, // 13: document.orchestrator.v1.OrchestratorCallbackService.OnStepComplete:input_type -> document.orchestrator.v1.StepCompleteRequest
	12, // 14: document.orchestrator.v1.OrchestratorCallbackService.OnJobFailed:input_type -> document.orchestrator.v1.JobFailedRequest
	14, // 15: document.orchestrator.v1.OrchestratorCallbackService.GetJobDetails:input_type -> document.orchestrator.v1.GetJobDetailsRequest
	1,  // 16: document.orchestrator.v1.OrchestratorService.SubmitJob:output_type -> document.orchestrator.v1.SubmitJobResponse
	3,  // 17: document.orchestrator.v1.OrchestratorService.StartJob:output_type -> document.orchestrator.v1.StartJobResponse
	5,  // 18: document.orchestrator.v1.OrchestratorService.SubmitStep:output_type -> document.orchestrator.v1.SubmitStepResponse
	7,  // 19: document.orchestrator.v1.OrchestratorService.ListenForProgress:output_type -> document.orchestrator.v1.ProgressUpdate
	9,  // 20: document.orchestrator.v1.OrchestratorService.ResumeJob:output_type -> document.orchestrator.v1.ResumeJobResponse
	11, // 21: document.orchestrator.v1.OrchestratorCallbackService.OnStepComplete:output_type -> document.orchestrator.v1.StepCompleteResponse
	13, // 22: document.orchestrator.v1.OrchestratorCallbackService.OnJobFailed:output_type -> document.orchestrator.v1.JobFailedResponse
	15, // 23: document.orchestrator.v1.OrchestratorCallbackService.GetJobDetails:output_type -> document.orchestrator.v1.GetJobDetailsResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	file_processor_proto_init()
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
