syntax = "proto3";

package document.orchestrator.v1;

option go_package = "github.com/AndrewK4758/shared_protos";
option csharp_namespace = "Document.Orchestrator.V1";

import "google/protobuf/struct.proto";
import "models.proto";

service OrchestratorService {
  rpc ExecuteTask(ExecuteTaskRequest) returns (ExecuteTaskResponse);
  rpc ListenForProgress(ListenRequest) returns (stream ProgressUpdate);
  rpc ResumeJob(ResumeJobRequest) returns (ResumeJobResponse);
  rpc PurgeSystemState(PurgeSystemStateRequest) returns (PurgeSystemStateResponse);
}

message ExecuteTaskRequest {
  document.models.v1.InfrastructureIdentity identity = 1;
  string task_subject = 2;
  google.protobuf.Struct payload = 3;
  string step_id = 4;
  map<string, string> headers = 5;
  string callback_address = 6;
}

message ExecuteTaskResponse {
  bool success = 1;
  string message = 2;
  string step_id = 3;
}

message ListenRequest {
  document.models.v1.InfrastructureIdentity identity = 2;
}

message ProgressUpdate {
  string status = 2;
  string message = 3;
  google.protobuf.Struct final_results = 4;
  document.models.v1.InfrastructureIdentity identity = 5;
}

message ResumeJobRequest {
  google.protobuf.Struct corrected = 2;
  string step_id = 3;
  document.models.v1.InfrastructureIdentity identity = 4;
}

message ResumeJobResponse {
  bool success = 1;
  string message = 2;
}

message PurgeSystemStateRequest {
  bool purge_queues = 2;
  document.models.v1.InfrastructureIdentity identity = 3;
}

message PurgeSystemStateResponse {
  bool success = 1;
  int32 jobs_cancelled = 2;
  int32 queues_purged = 3;
}

service OrchestratorCallbackService {
  rpc OnTaskExecutionComplete(stream ExecuteTaskRequest) returns (stream TaskExecutionCompleteResponse);
  rpc OnJobFailed(JobFailedRequest) returns (JobFailedResponse);
  rpc OnJobSuspended(JobSuspendedRequest) returns (JobSuspendedResponse);
}

message TaskExecutionCompleteResponse {
  bool success = 1; 
}

message JobFailedResponse {
  bool success = 1;
}

message JobSuspendedResponse {
  bool success = 1;
}

message JobFailedRequest {
  document.models.v1.InfrastructureIdentity identity = 1;
  string step_id = 2;
  document.models.v1.ErrorContract error = 3;
}

message JobSuspendedRequest {
  document.models.v1.InfrastructureIdentity identity = 1;
  string step_id = 2;
  document.models.v1.ErrorContract error = 3;
}
