// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: orchestrator.proto

package shared_protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorService_SubmitDocument_FullMethodName    = "/document.orchestrator.v1.OrchestratorService/SubmitDocument"
	OrchestratorService_SubmitStep_FullMethodName        = "/document.orchestrator.v1.OrchestratorService/SubmitStep"
	OrchestratorService_ListenForProgress_FullMethodName = "/document.orchestrator.v1.OrchestratorService/ListenForProgress"
	OrchestratorService_ResumeJob_FullMethodName         = "/document.orchestrator.v1.OrchestratorService/ResumeJob"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorServiceClient interface {
	// Client submits a large PDF and immediately receives a JobID. Heavy payload is cached.
	SubmitDocument(ctx context.Context, in *SubmitDocumentRequest, opts ...grpc.CallOption) (*SubmitDocumentResponse, error)
	// Client submits a single, generic step to be executed for a specific JobID.
	SubmitStep(ctx context.Context, in *SubmitStepRequest, opts ...grpc.CallOption) (*SubmitStepResponse, error)
	// Client listens to this Server Stream to get real-time progress of their JobID
	ListenForProgress(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressUpdate], error)
	// Resume a job after human validation has corrected the AI output
	ResumeJob(ctx context.Context, in *ResumeJobRequest, opts ...grpc.CallOption) (*ResumeJobResponse, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) SubmitDocument(ctx context.Context, in *SubmitDocumentRequest, opts ...grpc.CallOption) (*SubmitDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitDocumentResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_SubmitDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) SubmitStep(ctx context.Context, in *SubmitStepRequest, opts ...grpc.CallOption) (*SubmitStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitStepResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_SubmitStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ListenForProgress(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestratorService_ServiceDesc.Streams[0], OrchestratorService_ListenForProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenRequest, ProgressUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorService_ListenForProgressClient = grpc.ServerStreamingClient[ProgressUpdate]

func (c *orchestratorServiceClient) ResumeJob(ctx context.Context, in *ResumeJobRequest, opts ...grpc.CallOption) (*ResumeJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeJobResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ResumeJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility.
type OrchestratorServiceServer interface {
	// Client submits a large PDF and immediately receives a JobID. Heavy payload is cached.
	SubmitDocument(context.Context, *SubmitDocumentRequest) (*SubmitDocumentResponse, error)
	// Client submits a single, generic step to be executed for a specific JobID.
	SubmitStep(context.Context, *SubmitStepRequest) (*SubmitStepResponse, error)
	// Client listens to this Server Stream to get real-time progress of their JobID
	ListenForProgress(*ListenRequest, grpc.ServerStreamingServer[ProgressUpdate]) error
	// Resume a job after human validation has corrected the AI output
	ResumeJob(context.Context, *ResumeJobRequest) (*ResumeJobResponse, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) SubmitDocument(context.Context, *SubmitDocumentRequest) (*SubmitDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitDocument not implemented")
}
func (UnimplementedOrchestratorServiceServer) SubmitStep(context.Context, *SubmitStepRequest) (*SubmitStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitStep not implemented")
}
func (UnimplementedOrchestratorServiceServer) ListenForProgress(*ListenRequest, grpc.ServerStreamingServer[ProgressUpdate]) error {
	return status.Error(codes.Unimplemented, "method ListenForProgress not implemented")
}
func (UnimplementedOrchestratorServiceServer) ResumeJob(context.Context, *ResumeJobRequest) (*ResumeJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeJob not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}
func (UnimplementedOrchestratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_SubmitDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).SubmitDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_SubmitDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).SubmitDocument(ctx, req.(*SubmitDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_SubmitStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).SubmitStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_SubmitStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).SubmitStep(ctx, req.(*SubmitStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ListenForProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServiceServer).ListenForProgress(m, &grpc.GenericServerStream[ListenRequest, ProgressUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorService_ListenForProgressServer = grpc.ServerStreamingServer[ProgressUpdate]

func _OrchestratorService_ResumeJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ResumeJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ResumeJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ResumeJob(ctx, req.(*ResumeJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "document.orchestrator.v1.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitDocument",
			Handler:    _OrchestratorService_SubmitDocument_Handler,
		},
		{
			MethodName: "SubmitStep",
			Handler:    _OrchestratorService_SubmitStep_Handler,
		},
		{
			MethodName: "ResumeJob",
			Handler:    _OrchestratorService_ResumeJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenForProgress",
			Handler:       _OrchestratorService_ListenForProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orchestrator.proto",
}

const (
	StepCallbackService_OnStepComplete_FullMethodName = "/document.orchestrator.v1.StepCallbackService/OnStepComplete"
)

// StepCallbackServiceClient is the client API for StepCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A completely generic gRPC service that any external application can implement
// to receive the lightweight callback containing the step result.
type StepCallbackServiceClient interface {
	OnStepComplete(ctx context.Context, in *StepCompleteRequest, opts ...grpc.CallOption) (*StepCompleteResponse, error)
}

type stepCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStepCallbackServiceClient(cc grpc.ClientConnInterface) StepCallbackServiceClient {
	return &stepCallbackServiceClient{cc}
}

func (c *stepCallbackServiceClient) OnStepComplete(ctx context.Context, in *StepCompleteRequest, opts ...grpc.CallOption) (*StepCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepCompleteResponse)
	err := c.cc.Invoke(ctx, StepCallbackService_OnStepComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StepCallbackServiceServer is the server API for StepCallbackService service.
// All implementations must embed UnimplementedStepCallbackServiceServer
// for forward compatibility.
//
// A completely generic gRPC service that any external application can implement
// to receive the lightweight callback containing the step result.
type StepCallbackServiceServer interface {
	OnStepComplete(context.Context, *StepCompleteRequest) (*StepCompleteResponse, error)
	mustEmbedUnimplementedStepCallbackServiceServer()
}

// UnimplementedStepCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStepCallbackServiceServer struct{}

func (UnimplementedStepCallbackServiceServer) OnStepComplete(context.Context, *StepCompleteRequest) (*StepCompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnStepComplete not implemented")
}
func (UnimplementedStepCallbackServiceServer) mustEmbedUnimplementedStepCallbackServiceServer() {}
func (UnimplementedStepCallbackServiceServer) testEmbeddedByValue()                             {}

// UnsafeStepCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StepCallbackServiceServer will
// result in compilation errors.
type UnsafeStepCallbackServiceServer interface {
	mustEmbedUnimplementedStepCallbackServiceServer()
}

func RegisterStepCallbackServiceServer(s grpc.ServiceRegistrar, srv StepCallbackServiceServer) {
	// If the following call panics, it indicates UnimplementedStepCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StepCallbackService_ServiceDesc, srv)
}

func _StepCallbackService_OnStepComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepCallbackServiceServer).OnStepComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepCallbackService_OnStepComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepCallbackServiceServer).OnStepComplete(ctx, req.(*StepCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StepCallbackService_ServiceDesc is the grpc.ServiceDesc for StepCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StepCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "document.orchestrator.v1.StepCallbackService",
	HandlerType: (*StepCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnStepComplete",
			Handler:    _StepCallbackService_OnStepComplete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestrator.proto",
}
