// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: orchestrator.proto

package shared_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteWorkflowNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in orchestrator.proto.
	JobId           string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StepId          string                  `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`                                                                 // The current node being executed
	CallbackAddress string                  `protobuf:"bytes,3,opt,name=callback_address,json=callbackAddress,proto3" json:"callback_address,omitempty"`                                      // Where to webhook the mutated state
	GlobalState     *structpb.Struct        `protobuf:"bytes,4,opt,name=global_state,json=globalState,proto3" json:"global_state,omitempty"`                                                  // The single source of truth payload
	Metadata        map[string]string       `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. correlation_id
	NodeConfig      *NodeConfiguration      `protobuf:"bytes,6,opt,name=node_config,json=nodeConfig,proto3" json:"node_config,omitempty"`
	Identity        *InfrastructureIdentity `protobuf:"bytes,7,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteWorkflowNodeRequest) Reset() {
	*x = ExecuteWorkflowNodeRequest{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowNodeRequest) ProtoMessage() {}

func (x *ExecuteWorkflowNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowNodeRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowNodeRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in orchestrator.proto.
func (x *ExecuteWorkflowNodeRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ExecuteWorkflowNodeRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ExecuteWorkflowNodeRequest) GetCallbackAddress() string {
	if x != nil {
		return x.CallbackAddress
	}
	return ""
}

func (x *ExecuteWorkflowNodeRequest) GetGlobalState() *structpb.Struct {
	if x != nil {
		return x.GlobalState
	}
	return nil
}

func (x *ExecuteWorkflowNodeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteWorkflowNodeRequest) GetNodeConfig() *NodeConfiguration {
	if x != nil {
		return x.NodeConfig
	}
	return nil
}

func (x *ExecuteWorkflowNodeRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type ExecuteWorkflowNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowNodeResponse) Reset() {
	*x = ExecuteWorkflowNodeResponse{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowNodeResponse) ProtoMessage() {}

func (x *ExecuteWorkflowNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowNodeResponse.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowNodeResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteWorkflowNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteWorkflowNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteWorkflowNodeResponse) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

type ListenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in orchestrator.proto.
	JobId         string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Identity      *InfrastructureIdentity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenRequest) Reset() {
	*x = ListenRequest{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenRequest) ProtoMessage() {}

func (x *ListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenRequest.ProtoReflect.Descriptor instead.
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

// Deprecated: Marked as deprecated in orchestrator.proto.
func (x *ListenRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ListenRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type ProgressUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in orchestrator.proto.
	JobId   string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // e.g., "CHUNKING", "PROCESSING", "STITCHING", "COMPLETE", "FAILED"
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Detailed message, e.g., "Processing chunk 2 of 5"
	// Only populated when status == "COMPLETE"
	FinalResultsJson string                  `protobuf:"bytes,4,opt,name=final_results_json,json=finalResultsJson,proto3" json:"final_results_json,omitempty"`
	Identity         *InfrastructureIdentity `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

// Deprecated: Marked as deprecated in orchestrator.proto.
func (x *ProgressUpdate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProgressUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressUpdate) GetFinalResultsJson() string {
	if x != nil {
		return x.FinalResultsJson
	}
	return ""
}

func (x *ProgressUpdate) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type ResumeJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in orchestrator.proto.
	JobId         string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CorrectedJson string                  `protobuf:"bytes,2,opt,name=corrected_json,json=correctedJson,proto3" json:"corrected_json,omitempty"`
	StepId        string                  `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Identity      *InfrastructureIdentity `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeJobRequest) Reset() {
	*x = ResumeJobRequest{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeJobRequest) ProtoMessage() {}

func (x *ResumeJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeJobRequest.ProtoReflect.Descriptor instead.
func (*ResumeJobRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

// Deprecated: Marked as deprecated in orchestrator.proto.
func (x *ResumeJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ResumeJobRequest) GetCorrectedJson() string {
	if x != nil {
		return x.CorrectedJson
	}
	return ""
}

func (x *ResumeJobRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ResumeJobRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type ResumeJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeJobResponse) Reset() {
	*x = ResumeJobResponse{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeJobResponse) ProtoMessage() {}

func (x *ResumeJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeJobResponse.ProtoReflect.Descriptor instead.
func (*ResumeJobResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PurgeSystemStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in orchestrator.proto.
	JobId         string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                    // Scopes the cancellation to a specific tenant/app
	PurgeQueues   bool                    `protobuf:"varint,2,opt,name=purge_queues,json=purgeQueues,proto3" json:"purge_queues,omitempty"` // Explicit command to purge NATS JetStream queues
	Identity      *InfrastructureIdentity `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeSystemStateRequest) Reset() {
	*x = PurgeSystemStateRequest{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeSystemStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeSystemStateRequest) ProtoMessage() {}

func (x *PurgeSystemStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeSystemStateRequest.ProtoReflect.Descriptor instead.
func (*PurgeSystemStateRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

// Deprecated: Marked as deprecated in orchestrator.proto.
func (x *PurgeSystemStateRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PurgeSystemStateRequest) GetPurgeQueues() bool {
	if x != nil {
		return x.PurgeQueues
	}
	return false
}

func (x *PurgeSystemStateRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type PurgeSystemStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	JobsCancelled int32                  `protobuf:"varint,2,opt,name=jobs_cancelled,json=jobsCancelled,proto3" json:"jobs_cancelled,omitempty"`
	QueuesPurged  int32                  `protobuf:"varint,3,opt,name=queues_purged,json=queuesPurged,proto3" json:"queues_purged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeSystemStateResponse) Reset() {
	*x = PurgeSystemStateResponse{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeSystemStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeSystemStateResponse) ProtoMessage() {}

func (x *PurgeSystemStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeSystemStateResponse.ProtoReflect.Descriptor instead.
func (*PurgeSystemStateResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *PurgeSystemStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PurgeSystemStateResponse) GetJobsCancelled() int32 {
	if x != nil {
		return x.JobsCancelled
	}
	return 0
}

func (x *PurgeSystemStateResponse) GetQueuesPurged() int32 {
	if x != nil {
		return x.QueuesPurged
	}
	return 0
}

type NodeExecutionCompleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in orchestrator.proto.
	JobId           string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CompletedStepId string                  `protobuf:"bytes,2,opt,name=completed_step_id,json=completedStepId,proto3" json:"completed_step_id,omitempty"`
	GlobalState     *structpb.Struct        `protobuf:"bytes,3,opt,name=global_state,json=globalState,proto3" json:"global_state,omitempty"` // The mutated state
	NodeOutput      *structpb.Struct        `protobuf:"bytes,4,opt,name=node_output,json=nodeOutput,proto3" json:"node_output,omitempty"`    // The isolated output for dynamic rule evaluation
	Success         bool                    `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                  `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Identity        *InfrastructureIdentity `protobuf:"bytes,7,opt,name=identity,proto3" json:"identity,omitempty"`
	Metadata        map[string]string       `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeExecutionCompleteRequest) Reset() {
	*x = NodeExecutionCompleteRequest{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeExecutionCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeExecutionCompleteRequest) ProtoMessage() {}

func (x *NodeExecutionCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeExecutionCompleteRequest.ProtoReflect.Descriptor instead.
func (*NodeExecutionCompleteRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

// Deprecated: Marked as deprecated in orchestrator.proto.
func (x *NodeExecutionCompleteRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *NodeExecutionCompleteRequest) GetCompletedStepId() string {
	if x != nil {
		return x.CompletedStepId
	}
	return ""
}

func (x *NodeExecutionCompleteRequest) GetGlobalState() *structpb.Struct {
	if x != nil {
		return x.GlobalState
	}
	return nil
}

func (x *NodeExecutionCompleteRequest) GetNodeOutput() *structpb.Struct {
	if x != nil {
		return x.NodeOutput
	}
	return nil
}

func (x *NodeExecutionCompleteRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NodeExecutionCompleteRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *NodeExecutionCompleteRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *NodeExecutionCompleteRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type NodeExecutionCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeExecutionCompleteResponse) Reset() {
	*x = NodeExecutionCompleteResponse{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeExecutionCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeExecutionCompleteResponse) ProtoMessage() {}

func (x *NodeExecutionCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeExecutionCompleteResponse.ProtoReflect.Descriptor instead.
func (*NodeExecutionCompleteResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *NodeExecutionCompleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type JobFailedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in orchestrator.proto.
	JobId         string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	FailedStepId  string                  `protobuf:"bytes,2,opt,name=failed_step_id,json=failedStepId,proto3" json:"failed_step_id,omitempty"`
	ErrorMessage  string                  `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Identity      *InfrastructureIdentity `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	Metadata      map[string]string       `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFailedRequest) Reset() {
	*x = JobFailedRequest{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFailedRequest) ProtoMessage() {}

func (x *JobFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFailedRequest.ProtoReflect.Descriptor instead.
func (*JobFailedRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

// Deprecated: Marked as deprecated in orchestrator.proto.
func (x *JobFailedRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobFailedRequest) GetFailedStepId() string {
	if x != nil {
		return x.FailedStepId
	}
	return ""
}

func (x *JobFailedRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobFailedRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *JobFailedRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type JobFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFailedResponse) Reset() {
	*x = JobFailedResponse{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFailedResponse) ProtoMessage() {}

func (x *JobFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFailedResponse.ProtoReflect.Descriptor instead.
func (*JobFailedResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *JobFailedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\x18document.orchestrator.v1\x1a\fmodels.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xe4\x03\n" +
	"\x1aExecuteWorkflowNodeRequest\x12\x19\n" +
	"\x06job_id\x18\x01 \x01(\tB\x02\x18\x01R\x05jobId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12)\n" +
	"\x10callback_address\x18\x03 \x01(\tR\x0fcallbackAddress\x12:\n" +
	"\fglobal_state\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vglobalState\x12^\n" +
	"\bmetadata\x18\x05 \x03(\v2B.document.orchestrator.v1.ExecuteWorkflowNodeRequest.MetadataEntryR\bmetadata\x12F\n" +
	"\vnode_config\x18\x06 \x01(\v2%.document.models.v1.NodeConfigurationR\n" +
	"nodeConfig\x12F\n" +
	"\bidentity\x18\a \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x1bExecuteWorkflowNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\"r\n" +
	"\rListenRequest\x12\x19\n" +
	"\x06job_id\x18\x01 \x01(\tB\x02\x18\x01R\x05jobId\x12F\n" +
	"\bidentity\x18\x02 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"\xd3\x01\n" +
	"\x0eProgressUpdate\x12\x19\n" +
	"\x06job_id\x18\x01 \x01(\tB\x02\x18\x01R\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12,\n" +
	"\x12final_results_json\x18\x04 \x01(\tR\x10finalResultsJson\x12F\n" +
	"\bidentity\x18\x05 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"\xb5\x01\n" +
	"\x10ResumeJobRequest\x12\x19\n" +
	"\x06job_id\x18\x01 \x01(\tB\x02\x18\x01R\x05jobId\x12%\n" +
	"\x0ecorrected_json\x18\x02 \x01(\tR\rcorrectedJson\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12F\n" +
	"\bidentity\x18\x04 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"G\n" +
	"\x11ResumeJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9f\x01\n" +
	"\x17PurgeSystemStateRequest\x12\x19\n" +
	"\x06job_id\x18\x01 \x01(\tB\x02\x18\x01R\x05jobId\x12!\n" +
	"\fpurge_queues\x18\x02 \x01(\bR\vpurgeQueues\x12F\n" +
	"\bidentity\x18\x03 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"\x80\x01\n" +
	"\x18PurgeSystemStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ejobs_cancelled\x18\x02 \x01(\x05R\rjobsCancelled\x12#\n" +
	"\rqueues_purged\x18\x03 \x01(\x05R\fqueuesPurged\"\x81\x04\n" +
	"\x1cNodeExecutionCompleteRequest\x12\x19\n" +
	"\x06job_id\x18\x01 \x01(\tB\x02\x18\x01R\x05jobId\x12*\n" +
	"\x11completed_step_id\x18\x02 \x01(\tR\x0fcompletedStepId\x12:\n" +
	"\fglobal_state\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vglobalState\x128\n" +
	"\vnode_output\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"nodeOutput\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12F\n" +
	"\bidentity\x18\a \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\x12`\n" +
	"\bmetadata\x18\b \x03(\v2D.document.orchestrator.v1.NodeExecutionCompleteRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x1dNodeExecutionCompleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd3\x02\n" +
	"\x10JobFailedRequest\x12\x19\n" +
	"\x06job_id\x18\x01 \x01(\tB\x02\x18\x01R\x05jobId\x12$\n" +
	"\x0efailed_step_id\x18\x02 \x01(\tR\ffailedStepId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12F\n" +
	"\bidentity\x18\x04 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\x12T\n" +
	"\bmetadata\x18\x05 \x03(\v28.document.orchestrator.v1.JobFailedRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x11JobFailedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe5\x03\n" +
	"\x13OrchestratorService\x12\x82\x01\n" +
	"\x13ExecuteWorkflowNode\x124.document.orchestrator.v1.ExecuteWorkflowNodeRequest\x1a5.document.orchestrator.v1.ExecuteWorkflowNodeResponse\x12h\n" +
	"\x11ListenForProgress\x12'.document.orchestrator.v1.ListenRequest\x1a(.document.orchestrator.v1.ProgressUpdate0\x01\x12d\n" +
	"\tResumeJob\x12*.document.orchestrator.v1.ResumeJobRequest\x1a+.document.orchestrator.v1.ResumeJobResponse\x12y\n" +
	"\x10PurgeSystemState\x121.document.orchestrator.v1.PurgeSystemStateRequest\x1a2.document.orchestrator.v1.PurgeSystemStateResponse2\x96\x02\n" +
	"\x1bOrchestratorCallbackService\x12\x8e\x01\n" +
	"\x17OnNodeExecutionComplete\x126.document.orchestrator.v1.NodeExecutionCompleteRequest\x1a7.document.orchestrator.v1.NodeExecutionCompleteResponse(\x010\x01\x12f\n" +
	"\vOnJobFailed\x12*.document.orchestrator.v1.JobFailedRequest\x1a+.document.orchestrator.v1.JobFailedResponseBAZ$github.com/AndrewK4758/shared_protos\xaa\x02\x18Document.Orchestrator.V1b\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_orchestrator_proto_goTypes = []any{
	(*ExecuteWorkflowNodeRequest)(nil),    // 0: document.orchestrator.v1.ExecuteWorkflowNodeRequest
	(*ExecuteWorkflowNodeResponse)(nil),   // 1: document.orchestrator.v1.ExecuteWorkflowNodeResponse
	(*ListenRequest)(nil),                 // 2: document.orchestrator.v1.ListenRequest
	(*ProgressUpdate)(nil),                // 3: document.orchestrator.v1.ProgressUpdate
	(*ResumeJobRequest)(nil),              // 4: document.orchestrator.v1.ResumeJobRequest
	(*ResumeJobResponse)(nil),             // 5: document.orchestrator.v1.ResumeJobResponse
	(*PurgeSystemStateRequest)(nil),       // 6: document.orchestrator.v1.PurgeSystemStateRequest
	(*PurgeSystemStateResponse)(nil),      // 7: document.orchestrator.v1.PurgeSystemStateResponse
	(*NodeExecutionCompleteRequest)(nil),  // 8: document.orchestrator.v1.NodeExecutionCompleteRequest
	(*NodeExecutionCompleteResponse)(nil), // 9: document.orchestrator.v1.NodeExecutionCompleteResponse
	(*JobFailedRequest)(nil),              // 10: document.orchestrator.v1.JobFailedRequest
	(*JobFailedResponse)(nil),             // 11: document.orchestrator.v1.JobFailedResponse
	nil,                                   // 12: document.orchestrator.v1.ExecuteWorkflowNodeRequest.MetadataEntry
	nil,                                   // 13: document.orchestrator.v1.NodeExecutionCompleteRequest.MetadataEntry
	nil,                                   // 14: document.orchestrator.v1.JobFailedRequest.MetadataEntry
	(*structpb.Struct)(nil),               // 15: google.protobuf.Struct
	(*NodeConfiguration)(nil),             // 16: document.models.v1.NodeConfiguration
	(*InfrastructureIdentity)(nil),        // 17: document.models.v1.InfrastructureIdentity
}
var file_orchestrator_proto_depIdxs = []int32{
	15, // 0: document.orchestrator.v1.ExecuteWorkflowNodeRequest.global_state:type_name -> google.protobuf.Struct
	12, // 1: document.orchestrator.v1.ExecuteWorkflowNodeRequest.metadata:type_name -> document.orchestrator.v1.ExecuteWorkflowNodeRequest.MetadataEntry
	16, // 2: document.orchestrator.v1.ExecuteWorkflowNodeRequest.node_config:type_name -> document.models.v1.NodeConfiguration
	17, // 3: document.orchestrator.v1.ExecuteWorkflowNodeRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	17, // 4: document.orchestrator.v1.ListenRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	17, // 5: document.orchestrator.v1.ProgressUpdate.identity:type_name -> document.models.v1.InfrastructureIdentity
	17, // 6: document.orchestrator.v1.ResumeJobRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	17, // 7: document.orchestrator.v1.PurgeSystemStateRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	15, // 8: document.orchestrator.v1.NodeExecutionCompleteRequest.global_state:type_name -> google.protobuf.Struct
	15, // 9: document.orchestrator.v1.NodeExecutionCompleteRequest.node_output:type_name -> google.protobuf.Struct
	17, // 10: document.orchestrator.v1.NodeExecutionCompleteRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	13, // 11: document.orchestrator.v1.NodeExecutionCompleteRequest.metadata:type_name -> document.orchestrator.v1.NodeExecutionCompleteRequest.MetadataEntry
	17, // 12: document.orchestrator.v1.JobFailedRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	14, // 13: document.orchestrator.v1.JobFailedRequest.metadata:type_name -> document.orchestrator.v1.JobFailedRequest.MetadataEntry
	0,  // 14: document.orchestrator.v1.OrchestratorService.ExecuteWorkflowNode:input_type -> document.orchestrator.v1.ExecuteWorkflowNodeRequest
	2,  // 15: document.orchestrator.v1.OrchestratorService.ListenForProgress:input_type -> document.orchestrator.v1.ListenRequest
	4,  // 16: document.orchestrator.v1.OrchestratorService.ResumeJob:input_type -> document.orchestrator.v1.ResumeJobRequest
	6,  // 17: document.orchestrator.v1.OrchestratorService.PurgeSystemState:input_type -> document.orchestrator.v1.PurgeSystemStateRequest
	8,  // 18: document.orchestrator.v1.OrchestratorCallbackService.OnNodeExecutionComplete:input_type -> document.orchestrator.v1.NodeExecutionCompleteRequest
	10, // 19: document.orchestrator.v1.OrchestratorCallbackService.OnJobFailed:input_type -> document.orchestrator.v1.JobFailedRequest
	1,  // 20: document.orchestrator.v1.OrchestratorService.ExecuteWorkflowNode:output_type -> document.orchestrator.v1.ExecuteWorkflowNodeResponse
	3,  // 21: document.orchestrator.v1.OrchestratorService.ListenForProgress:output_type -> document.orchestrator.v1.ProgressUpdate
	5,  // 22: document.orchestrator.v1.OrchestratorService.ResumeJob:output_type -> document.orchestrator.v1.ResumeJobResponse
	7,  // 23: document.orchestrator.v1.OrchestratorService.PurgeSystemState:output_type -> document.orchestrator.v1.PurgeSystemStateResponse
	9,  // 24: document.orchestrator.v1.OrchestratorCallbackService.OnNodeExecutionComplete:output_type -> document.orchestrator.v1.NodeExecutionCompleteResponse
	11, // 25: document.orchestrator.v1.OrchestratorCallbackService.OnJobFailed:output_type -> document.orchestrator.v1.JobFailedResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
