// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: schema_registry.proto

package shared_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRulesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClassificationName string                 `protobuf:"bytes,1,opt,name=classification_name,json=classificationName,proto3" json:"classification_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetRulesRequest) Reset() {
	*x = GetRulesRequest{}
	mi := &file_schema_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesRequest) ProtoMessage() {}

func (x *GetRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesRequest.ProtoReflect.Descriptor instead.
func (*GetRulesRequest) Descriptor() ([]byte, []int) {
	return file_schema_registry_proto_rawDescGZIP(), []int{0}
}

func (x *GetRulesRequest) GetClassificationName() string {
	if x != nil {
		return x.ClassificationName
	}
	return ""
}

type GetRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RulesText     string                 `protobuf:"bytes,3,opt,name=rules_text,json=rulesText,proto3" json:"rules_text,omitempty"`
	JsonSchema    string                 `protobuf:"bytes,4,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRulesResponse) Reset() {
	*x = GetRulesResponse{}
	mi := &file_schema_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesResponse) ProtoMessage() {}

func (x *GetRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesResponse.ProtoReflect.Descriptor instead.
func (*GetRulesResponse) Descriptor() ([]byte, []int) {
	return file_schema_registry_proto_rawDescGZIP(), []int{1}
}

func (x *GetRulesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRulesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetRulesResponse) GetRulesText() string {
	if x != nil {
		return x.RulesText
	}
	return ""
}

func (x *GetRulesResponse) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

var File_schema_registry_proto protoreflect.FileDescriptor

const file_schema_registry_proto_rawDesc = "" +
	"\n" +
	"\x15schema_registry.proto\x12\x14document.registry.v1\"B\n" +
	"\x0fGetRulesRequest\x12/\n" +
	"\x13classification_name\x18\x01 \x01(\tR\x12classificationName\"\x91\x01\n" +
	"\x10GetRulesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"rules_text\x18\x03 \x01(\tR\trulesText\x12\x1f\n" +
	"\vjson_schema\x18\x04 \x01(\tR\n" +
	"jsonSchema2\x83\x01\n" +
	"\x15SchemaRegistryService\x12j\n" +
	"\x19GetRulesForClassification\x12%.document.registry.v1.GetRulesRequest\x1a&.document.registry.v1.GetRulesResponseB&Z$github.com/AndrewK4758/shared_protosb\x06proto3"

var (
	file_schema_registry_proto_rawDescOnce sync.Once
	file_schema_registry_proto_rawDescData []byte
)

func file_schema_registry_proto_rawDescGZIP() []byte {
	file_schema_registry_proto_rawDescOnce.Do(func() {
		file_schema_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_registry_proto_rawDesc), len(file_schema_registry_proto_rawDesc)))
	})
	return file_schema_registry_proto_rawDescData
}

var file_schema_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schema_registry_proto_goTypes = []any{
	(*GetRulesRequest)(nil),  // 0: document.registry.v1.GetRulesRequest
	(*GetRulesResponse)(nil), // 1: document.registry.v1.GetRulesResponse
}
var file_schema_registry_proto_depIdxs = []int32{
	0, // 0: document.registry.v1.SchemaRegistryService.GetRulesForClassification:input_type -> document.registry.v1.GetRulesRequest
	1, // 1: document.registry.v1.SchemaRegistryService.GetRulesForClassification:output_type -> document.registry.v1.GetRulesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_registry_proto_init() }
func file_schema_registry_proto_init() {
	if File_schema_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_registry_proto_rawDesc), len(file_schema_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_registry_proto_goTypes,
		DependencyIndexes: file_schema_registry_proto_depIdxs,
		MessageInfos:      file_schema_registry_proto_msgTypes,
	}.Build()
	File_schema_registry_proto = out.File
	file_schema_registry_proto_goTypes = nil
	file_schema_registry_proto_depIdxs = nil
}
