// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: schema_registry.proto

package shared_protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchemaRegistryService_GetRulesForClassification_FullMethodName = "/document.registry.v1.SchemaRegistryService/GetRulesForClassification"
)

// SchemaRegistryServiceClient is the client API for SchemaRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchemaRegistryServiceClient interface {
	GetRulesForClassification(ctx context.Context, in *GetRulesRequest, opts ...grpc.CallOption) (*GetRulesResponse, error)
}

type schemaRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchemaRegistryServiceClient(cc grpc.ClientConnInterface) SchemaRegistryServiceClient {
	return &schemaRegistryServiceClient{cc}
}

func (c *schemaRegistryServiceClient) GetRulesForClassification(ctx context.Context, in *GetRulesRequest, opts ...grpc.CallOption) (*GetRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRulesResponse)
	err := c.cc.Invoke(ctx, SchemaRegistryService_GetRulesForClassification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchemaRegistryServiceServer is the server API for SchemaRegistryService service.
// All implementations must embed UnimplementedSchemaRegistryServiceServer
// for forward compatibility.
type SchemaRegistryServiceServer interface {
	GetRulesForClassification(context.Context, *GetRulesRequest) (*GetRulesResponse, error)
	mustEmbedUnimplementedSchemaRegistryServiceServer()
}

// UnimplementedSchemaRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchemaRegistryServiceServer struct{}

func (UnimplementedSchemaRegistryServiceServer) GetRulesForClassification(context.Context, *GetRulesRequest) (*GetRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRulesForClassification not implemented")
}
func (UnimplementedSchemaRegistryServiceServer) mustEmbedUnimplementedSchemaRegistryServiceServer() {}
func (UnimplementedSchemaRegistryServiceServer) testEmbeddedByValue()                               {}

// UnsafeSchemaRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchemaRegistryServiceServer will
// result in compilation errors.
type UnsafeSchemaRegistryServiceServer interface {
	mustEmbedUnimplementedSchemaRegistryServiceServer()
}

func RegisterSchemaRegistryServiceServer(s grpc.ServiceRegistrar, srv SchemaRegistryServiceServer) {
	// If the following call panics, it indicates UnimplementedSchemaRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchemaRegistryService_ServiceDesc, srv)
}

func _SchemaRegistryService_GetRulesForClassification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServiceServer).GetRulesForClassification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaRegistryService_GetRulesForClassification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServiceServer).GetRulesForClassification(ctx, req.(*GetRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchemaRegistryService_ServiceDesc is the grpc.ServiceDesc for SchemaRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchemaRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "document.registry.v1.SchemaRegistryService",
	HandlerType: (*SchemaRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRulesForClassification",
			Handler:    _SchemaRegistryService_GetRulesForClassification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema_registry.proto",
}
