// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: semantic_cache.proto

package shared_protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SemanticCacheService_CheckCache_FullMethodName      = "/semanticcache.v1.SemanticCacheService/CheckCache"
	SemanticCacheService_StoreExtraction_FullMethodName = "/semanticcache.v1.SemanticCacheService/StoreExtraction"
)

// SemanticCacheServiceClient is the client API for SemanticCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SemanticCacheServiceClient interface {
	CheckCache(ctx context.Context, in *CheckCacheRequest, opts ...grpc.CallOption) (*CheckCacheResponse, error)
	StoreExtraction(ctx context.Context, in *StoreExtractionRequest, opts ...grpc.CallOption) (*StoreExtractionResponse, error)
}

type semanticCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticCacheServiceClient(cc grpc.ClientConnInterface) SemanticCacheServiceClient {
	return &semanticCacheServiceClient{cc}
}

func (c *semanticCacheServiceClient) CheckCache(ctx context.Context, in *CheckCacheRequest, opts ...grpc.CallOption) (*CheckCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCacheResponse)
	err := c.cc.Invoke(ctx, SemanticCacheService_CheckCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticCacheServiceClient) StoreExtraction(ctx context.Context, in *StoreExtractionRequest, opts ...grpc.CallOption) (*StoreExtractionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreExtractionResponse)
	err := c.cc.Invoke(ctx, SemanticCacheService_StoreExtraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticCacheServiceServer is the server API for SemanticCacheService service.
// All implementations must embed UnimplementedSemanticCacheServiceServer
// for forward compatibility.
type SemanticCacheServiceServer interface {
	CheckCache(context.Context, *CheckCacheRequest) (*CheckCacheResponse, error)
	StoreExtraction(context.Context, *StoreExtractionRequest) (*StoreExtractionResponse, error)
	mustEmbedUnimplementedSemanticCacheServiceServer()
}

// UnimplementedSemanticCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticCacheServiceServer struct{}

func (UnimplementedSemanticCacheServiceServer) CheckCache(context.Context, *CheckCacheRequest) (*CheckCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckCache not implemented")
}
func (UnimplementedSemanticCacheServiceServer) StoreExtraction(context.Context, *StoreExtractionRequest) (*StoreExtractionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreExtraction not implemented")
}
func (UnimplementedSemanticCacheServiceServer) mustEmbedUnimplementedSemanticCacheServiceServer() {}
func (UnimplementedSemanticCacheServiceServer) testEmbeddedByValue()                              {}

// UnsafeSemanticCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticCacheServiceServer will
// result in compilation errors.
type UnsafeSemanticCacheServiceServer interface {
	mustEmbedUnimplementedSemanticCacheServiceServer()
}

func RegisterSemanticCacheServiceServer(s grpc.ServiceRegistrar, srv SemanticCacheServiceServer) {
	// If the following call panics, it indicates UnimplementedSemanticCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SemanticCacheService_ServiceDesc, srv)
}

func _SemanticCacheService_CheckCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServiceServer).CheckCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCacheService_CheckCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServiceServer).CheckCache(ctx, req.(*CheckCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticCacheService_StoreExtraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreExtractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServiceServer).StoreExtraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCacheService_StoreExtraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServiceServer).StoreExtraction(ctx, req.(*StoreExtractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticCacheService_ServiceDesc is the grpc.ServiceDesc for SemanticCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "semanticcache.v1.SemanticCacheService",
	HandlerType: (*SemanticCacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckCache",
			Handler:    _SemanticCacheService_CheckCache_Handler,
		},
		{
			MethodName: "StoreExtraction",
			Handler:    _SemanticCacheService_StoreExtraction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "semantic_cache.proto",
}
