// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: semantic_cache.proto

package shared_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckCacheRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Threshold      float32                `protobuf:"fixed32,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckCacheRequest) Reset() {
	*x = CheckCacheRequest{}
	mi := &file_semantic_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCacheRequest) ProtoMessage() {}

func (x *CheckCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCacheRequest.ProtoReflect.Descriptor instead.
func (*CheckCacheRequest) Descriptor() ([]byte, []int) {
	return file_semantic_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CheckCacheRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CheckCacheRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CheckCacheRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CheckCacheRequest) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type CheckCacheResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hit              bool                   `protobuf:"varint,1,opt,name=hit,proto3" json:"hit,omitempty"`
	ExtractedPayload string                 `protobuf:"bytes,2,opt,name=extracted_payload,json=extractedPayload,proto3" json:"extracted_payload,omitempty"`
	Confidence       float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckCacheResponse) Reset() {
	*x = CheckCacheResponse{}
	mi := &file_semantic_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCacheResponse) ProtoMessage() {}

func (x *CheckCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCacheResponse.ProtoReflect.Descriptor instead.
func (*CheckCacheResponse) Descriptor() ([]byte, []int) {
	return file_semantic_cache_proto_rawDescGZIP(), []int{1}
}

func (x *CheckCacheResponse) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *CheckCacheResponse) GetExtractedPayload() string {
	if x != nil {
		return x.ExtractedPayload
	}
	return ""
}

func (x *CheckCacheResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type StoreExtractionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CollectionName   string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Text             string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Metadata         *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExtractedPayload string                 `protobuf:"bytes,4,opt,name=extracted_payload,json=extractedPayload,proto3" json:"extracted_payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StoreExtractionRequest) Reset() {
	*x = StoreExtractionRequest{}
	mi := &file_semantic_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreExtractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreExtractionRequest) ProtoMessage() {}

func (x *StoreExtractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreExtractionRequest.ProtoReflect.Descriptor instead.
func (*StoreExtractionRequest) Descriptor() ([]byte, []int) {
	return file_semantic_cache_proto_rawDescGZIP(), []int{2}
}

func (x *StoreExtractionRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *StoreExtractionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StoreExtractionRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StoreExtractionRequest) GetExtractedPayload() string {
	if x != nil {
		return x.ExtractedPayload
	}
	return ""
}

type StoreExtractionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreExtractionResponse) Reset() {
	*x = StoreExtractionResponse{}
	mi := &file_semantic_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreExtractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreExtractionResponse) ProtoMessage() {}

func (x *StoreExtractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreExtractionResponse.ProtoReflect.Descriptor instead.
func (*StoreExtractionResponse) Descriptor() ([]byte, []int) {
	return file_semantic_cache_proto_rawDescGZIP(), []int{3}
}

func (x *StoreExtractionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SeedCacheRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CollectionName   string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	TemplateText     string                 `protobuf:"bytes,2,opt,name=template_text,json=templateText,proto3" json:"template_text,omitempty"`
	Metadata         *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExtractedPayload string                 `protobuf:"bytes,4,opt,name=extracted_payload,json=extractedPayload,proto3" json:"extracted_payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SeedCacheRequest) Reset() {
	*x = SeedCacheRequest{}
	mi := &file_semantic_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedCacheRequest) ProtoMessage() {}

func (x *SeedCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedCacheRequest.ProtoReflect.Descriptor instead.
func (*SeedCacheRequest) Descriptor() ([]byte, []int) {
	return file_semantic_cache_proto_rawDescGZIP(), []int{4}
}

func (x *SeedCacheRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *SeedCacheRequest) GetTemplateText() string {
	if x != nil {
		return x.TemplateText
	}
	return ""
}

func (x *SeedCacheRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SeedCacheRequest) GetExtractedPayload() string {
	if x != nil {
		return x.ExtractedPayload
	}
	return ""
}

type SeedCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedCacheResponse) Reset() {
	*x = SeedCacheResponse{}
	mi := &file_semantic_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedCacheResponse) ProtoMessage() {}

func (x *SeedCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedCacheResponse.ProtoReflect.Descriptor instead.
func (*SeedCacheResponse) Descriptor() ([]byte, []int) {
	return file_semantic_cache_proto_rawDescGZIP(), []int{5}
}

func (x *SeedCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SeedCacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_semantic_cache_proto protoreflect.FileDescriptor

const file_semantic_cache_proto_rawDesc = "" +
	"\n" +
	"\x14semantic_cache.proto\x12\x10semanticcache.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xa3\x01\n" +
	"\x11CheckCacheRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x02R\tthreshold\"s\n" +
	"\x12CheckCacheResponse\x12\x10\n" +
	"\x03hit\x18\x01 \x01(\bR\x03hit\x12+\n" +
	"\x11extracted_payload\x18\x02 \x01(\tR\x10extractedPayload\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\"\xb7\x01\n" +
	"\x16StoreExtractionRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12+\n" +
	"\x11extracted_payload\x18\x04 \x01(\tR\x10extractedPayload\"3\n" +
	"\x17StoreExtractionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc2\x01\n" +
	"\x10SeedCacheRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12#\n" +
	"\rtemplate_text\x18\x02 \x01(\tR\ftemplateText\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12+\n" +
	"\x11extracted_payload\x18\x04 \x01(\tR\x10extractedPayload\"G\n" +
	"\x11SeedCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xad\x02\n" +
	"\x14SemanticCacheService\x12W\n" +
	"\n" +
	"CheckCache\x12#.semanticcache.v1.CheckCacheRequest\x1a$.semanticcache.v1.CheckCacheResponse\x12f\n" +
	"\x0fStoreExtraction\x12(.semanticcache.v1.StoreExtractionRequest\x1a).semanticcache.v1.StoreExtractionResponse\x12T\n" +
	"\tSeedCache\x12\".semanticcache.v1.SeedCacheRequest\x1a#.semanticcache.v1.SeedCacheResponseB&Z$github.com/AndrewK4758/shared_protosb\x06proto3"

var (
	file_semantic_cache_proto_rawDescOnce sync.Once
	file_semantic_cache_proto_rawDescData []byte
)

func file_semantic_cache_proto_rawDescGZIP() []byte {
	file_semantic_cache_proto_rawDescOnce.Do(func() {
		file_semantic_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_semantic_cache_proto_rawDesc), len(file_semantic_cache_proto_rawDesc)))
	})
	return file_semantic_cache_proto_rawDescData
}

var file_semantic_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_semantic_cache_proto_goTypes = []any{
	(*CheckCacheRequest)(nil),       // 0: semanticcache.v1.CheckCacheRequest
	(*CheckCacheResponse)(nil),      // 1: semanticcache.v1.CheckCacheResponse
	(*StoreExtractionRequest)(nil),  // 2: semanticcache.v1.StoreExtractionRequest
	(*StoreExtractionResponse)(nil), // 3: semanticcache.v1.StoreExtractionResponse
	(*SeedCacheRequest)(nil),        // 4: semanticcache.v1.SeedCacheRequest
	(*SeedCacheResponse)(nil),       // 5: semanticcache.v1.SeedCacheResponse
	(*structpb.Struct)(nil),         // 6: google.protobuf.Struct
}
var file_semantic_cache_proto_depIdxs = []int32{
	6, // 0: semanticcache.v1.CheckCacheRequest.metadata:type_name -> google.protobuf.Struct
	6, // 1: semanticcache.v1.StoreExtractionRequest.metadata:type_name -> google.protobuf.Struct
	6, // 2: semanticcache.v1.SeedCacheRequest.metadata:type_name -> google.protobuf.Struct
	0, // 3: semanticcache.v1.SemanticCacheService.CheckCache:input_type -> semanticcache.v1.CheckCacheRequest
	2, // 4: semanticcache.v1.SemanticCacheService.StoreExtraction:input_type -> semanticcache.v1.StoreExtractionRequest
	4, // 5: semanticcache.v1.SemanticCacheService.SeedCache:input_type -> semanticcache.v1.SeedCacheRequest
	1, // 6: semanticcache.v1.SemanticCacheService.CheckCache:output_type -> semanticcache.v1.CheckCacheResponse
	3, // 7: semanticcache.v1.SemanticCacheService.StoreExtraction:output_type -> semanticcache.v1.StoreExtractionResponse
	5, // 8: semanticcache.v1.SemanticCacheService.SeedCache:output_type -> semanticcache.v1.SeedCacheResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_semantic_cache_proto_init() }
func file_semantic_cache_proto_init() {
	if File_semantic_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_semantic_cache_proto_rawDesc), len(file_semantic_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_semantic_cache_proto_goTypes,
		DependencyIndexes: file_semantic_cache_proto_depIdxs,
		MessageInfos:      file_semantic_cache_proto_msgTypes,
	}.Build()
	File_semantic_cache_proto = out.File
	file_semantic_cache_proto_goTypes = nil
	file_semantic_cache_proto_depIdxs = nil
}
