// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: semantic_cache.proto

package shared_protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SemanticCacheService_CheckCache_FullMethodName            = "/semanticcache.v1.SemanticCacheService/CheckCache"
	SemanticCacheService_StoreExtraction_FullMethodName       = "/semanticcache.v1.SemanticCacheService/StoreExtraction"
	SemanticCacheService_SeedCache_FullMethodName             = "/semanticcache.v1.SemanticCacheService/SeedCache"
	SemanticCacheService_CheckMetadataExists_FullMethodName   = "/semanticcache.v1.SemanticCacheService/CheckMetadataExists"
	SemanticCacheService_QueryBlankDocument_FullMethodName    = "/semanticcache.v1.SemanticCacheService/QueryBlankDocument"
	SemanticCacheService_RegisterBlankDocument_FullMethodName = "/semanticcache.v1.SemanticCacheService/RegisterBlankDocument"
	SemanticCacheService_MaskEntities_FullMethodName          = "/semanticcache.v1.SemanticCacheService/MaskEntities"
	SemanticCacheService_SemanticChunkDocument_FullMethodName = "/semanticcache.v1.SemanticCacheService/SemanticChunkDocument"
)

// SemanticCacheServiceClient is the client API for SemanticCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SemanticCacheServiceClient interface {
	CheckCache(ctx context.Context, in *CheckCacheRequest, opts ...grpc.CallOption) (*CheckCacheResponse, error)
	StoreExtraction(ctx context.Context, in *StoreExtractionRequest, opts ...grpc.CallOption) (*StoreExtractionResponse, error)
	SeedCache(ctx context.Context, in *SeedCacheRequest, opts ...grpc.CallOption) (*SeedCacheResponse, error)
	CheckMetadataExists(ctx context.Context, in *CheckMetadataRequest, opts ...grpc.CallOption) (*CheckMetadataResponse, error)
	QueryBlankDocument(ctx context.Context, in *QueryBlankDocumentRequest, opts ...grpc.CallOption) (*QueryBlankDocumentResponse, error)
	RegisterBlankDocument(ctx context.Context, in *RegisterBlankDocumentRequest, opts ...grpc.CallOption) (*RegisterBlankDocumentResponse, error)
	MaskEntities(ctx context.Context, in *MaskEntitiesRequest, opts ...grpc.CallOption) (*MaskEntitiesResponse, error)
	SemanticChunkDocument(ctx context.Context, in *SemanticChunkDocumentRequest, opts ...grpc.CallOption) (*SemanticChunkDocumentResponse, error)
}

type semanticCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticCacheServiceClient(cc grpc.ClientConnInterface) SemanticCacheServiceClient {
	return &semanticCacheServiceClient{cc}
}

func (c *semanticCacheServiceClient) CheckCache(ctx context.Context, in *CheckCacheRequest, opts ...grpc.CallOption) (*CheckCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCacheResponse)
	err := c.cc.Invoke(ctx, SemanticCacheService_CheckCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticCacheServiceClient) StoreExtraction(ctx context.Context, in *StoreExtractionRequest, opts ...grpc.CallOption) (*StoreExtractionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreExtractionResponse)
	err := c.cc.Invoke(ctx, SemanticCacheService_StoreExtraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticCacheServiceClient) SeedCache(ctx context.Context, in *SeedCacheRequest, opts ...grpc.CallOption) (*SeedCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeedCacheResponse)
	err := c.cc.Invoke(ctx, SemanticCacheService_SeedCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticCacheServiceClient) CheckMetadataExists(ctx context.Context, in *CheckMetadataRequest, opts ...grpc.CallOption) (*CheckMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckMetadataResponse)
	err := c.cc.Invoke(ctx, SemanticCacheService_CheckMetadataExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticCacheServiceClient) QueryBlankDocument(ctx context.Context, in *QueryBlankDocumentRequest, opts ...grpc.CallOption) (*QueryBlankDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryBlankDocumentResponse)
	err := c.cc.Invoke(ctx, SemanticCacheService_QueryBlankDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticCacheServiceClient) RegisterBlankDocument(ctx context.Context, in *RegisterBlankDocumentRequest, opts ...grpc.CallOption) (*RegisterBlankDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterBlankDocumentResponse)
	err := c.cc.Invoke(ctx, SemanticCacheService_RegisterBlankDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticCacheServiceClient) MaskEntities(ctx context.Context, in *MaskEntitiesRequest, opts ...grpc.CallOption) (*MaskEntitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaskEntitiesResponse)
	err := c.cc.Invoke(ctx, SemanticCacheService_MaskEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticCacheServiceClient) SemanticChunkDocument(ctx context.Context, in *SemanticChunkDocumentRequest, opts ...grpc.CallOption) (*SemanticChunkDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SemanticChunkDocumentResponse)
	err := c.cc.Invoke(ctx, SemanticCacheService_SemanticChunkDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticCacheServiceServer is the server API for SemanticCacheService service.
// All implementations must embed UnimplementedSemanticCacheServiceServer
// for forward compatibility.
type SemanticCacheServiceServer interface {
	CheckCache(context.Context, *CheckCacheRequest) (*CheckCacheResponse, error)
	StoreExtraction(context.Context, *StoreExtractionRequest) (*StoreExtractionResponse, error)
	SeedCache(context.Context, *SeedCacheRequest) (*SeedCacheResponse, error)
	CheckMetadataExists(context.Context, *CheckMetadataRequest) (*CheckMetadataResponse, error)
	QueryBlankDocument(context.Context, *QueryBlankDocumentRequest) (*QueryBlankDocumentResponse, error)
	RegisterBlankDocument(context.Context, *RegisterBlankDocumentRequest) (*RegisterBlankDocumentResponse, error)
	MaskEntities(context.Context, *MaskEntitiesRequest) (*MaskEntitiesResponse, error)
	SemanticChunkDocument(context.Context, *SemanticChunkDocumentRequest) (*SemanticChunkDocumentResponse, error)
	mustEmbedUnimplementedSemanticCacheServiceServer()
}

// UnimplementedSemanticCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticCacheServiceServer struct{}

func (UnimplementedSemanticCacheServiceServer) CheckCache(context.Context, *CheckCacheRequest) (*CheckCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckCache not implemented")
}
func (UnimplementedSemanticCacheServiceServer) StoreExtraction(context.Context, *StoreExtractionRequest) (*StoreExtractionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreExtraction not implemented")
}
func (UnimplementedSemanticCacheServiceServer) SeedCache(context.Context, *SeedCacheRequest) (*SeedCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SeedCache not implemented")
}
func (UnimplementedSemanticCacheServiceServer) CheckMetadataExists(context.Context, *CheckMetadataRequest) (*CheckMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckMetadataExists not implemented")
}
func (UnimplementedSemanticCacheServiceServer) QueryBlankDocument(context.Context, *QueryBlankDocumentRequest) (*QueryBlankDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryBlankDocument not implemented")
}
func (UnimplementedSemanticCacheServiceServer) RegisterBlankDocument(context.Context, *RegisterBlankDocumentRequest) (*RegisterBlankDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBlankDocument not implemented")
}
func (UnimplementedSemanticCacheServiceServer) MaskEntities(context.Context, *MaskEntitiesRequest) (*MaskEntitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MaskEntities not implemented")
}
func (UnimplementedSemanticCacheServiceServer) SemanticChunkDocument(context.Context, *SemanticChunkDocumentRequest) (*SemanticChunkDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SemanticChunkDocument not implemented")
}
func (UnimplementedSemanticCacheServiceServer) mustEmbedUnimplementedSemanticCacheServiceServer() {}
func (UnimplementedSemanticCacheServiceServer) testEmbeddedByValue()                              {}

// UnsafeSemanticCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticCacheServiceServer will
// result in compilation errors.
type UnsafeSemanticCacheServiceServer interface {
	mustEmbedUnimplementedSemanticCacheServiceServer()
}

func RegisterSemanticCacheServiceServer(s grpc.ServiceRegistrar, srv SemanticCacheServiceServer) {
	// If the following call panics, it indicates UnimplementedSemanticCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SemanticCacheService_ServiceDesc, srv)
}

func _SemanticCacheService_CheckCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServiceServer).CheckCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCacheService_CheckCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServiceServer).CheckCache(ctx, req.(*CheckCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticCacheService_StoreExtraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreExtractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServiceServer).StoreExtraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCacheService_StoreExtraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServiceServer).StoreExtraction(ctx, req.(*StoreExtractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticCacheService_SeedCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServiceServer).SeedCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCacheService_SeedCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServiceServer).SeedCache(ctx, req.(*SeedCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticCacheService_CheckMetadataExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServiceServer).CheckMetadataExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCacheService_CheckMetadataExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServiceServer).CheckMetadataExists(ctx, req.(*CheckMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticCacheService_QueryBlankDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBlankDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServiceServer).QueryBlankDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCacheService_QueryBlankDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServiceServer).QueryBlankDocument(ctx, req.(*QueryBlankDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticCacheService_RegisterBlankDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBlankDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServiceServer).RegisterBlankDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCacheService_RegisterBlankDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServiceServer).RegisterBlankDocument(ctx, req.(*RegisterBlankDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticCacheService_MaskEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaskEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServiceServer).MaskEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCacheService_MaskEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServiceServer).MaskEntities(ctx, req.(*MaskEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticCacheService_SemanticChunkDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemanticChunkDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServiceServer).SemanticChunkDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCacheService_SemanticChunkDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServiceServer).SemanticChunkDocument(ctx, req.(*SemanticChunkDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticCacheService_ServiceDesc is the grpc.ServiceDesc for SemanticCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "semanticcache.v1.SemanticCacheService",
	HandlerType: (*SemanticCacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckCache",
			Handler:    _SemanticCacheService_CheckCache_Handler,
		},
		{
			MethodName: "StoreExtraction",
			Handler:    _SemanticCacheService_StoreExtraction_Handler,
		},
		{
			MethodName: "SeedCache",
			Handler:    _SemanticCacheService_SeedCache_Handler,
		},
		{
			MethodName: "CheckMetadataExists",
			Handler:    _SemanticCacheService_CheckMetadataExists_Handler,
		},
		{
			MethodName: "QueryBlankDocument",
			Handler:    _SemanticCacheService_QueryBlankDocument_Handler,
		},
		{
			MethodName: "RegisterBlankDocument",
			Handler:    _SemanticCacheService_RegisterBlankDocument_Handler,
		},
		{
			MethodName: "MaskEntities",
			Handler:    _SemanticCacheService_MaskEntities_Handler,
		},
		{
			MethodName: "SemanticChunkDocument",
			Handler:    _SemanticCacheService_SemanticChunkDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "semantic_cache.proto",
}
