// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: storage_gateway.proto

package shared_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The first chunk must contain the metadata. Subsequent chunks only need the chunk_data.
	//
	// Types that are valid to be assigned to UploadElement:
	//
	//	*UploadRequest_Metadata
	//	*UploadRequest_ChunkData
	UploadElement isUploadRequest_UploadElement `protobuf_oneof:"upload_element"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_storage_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_storage_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetUploadElement() isUploadRequest_UploadElement {
	if x != nil {
		return x.UploadElement
	}
	return nil
}

func (x *UploadRequest) GetMetadata() *UploadMetadata {
	if x != nil {
		if x, ok := x.UploadElement.(*UploadRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.UploadElement.(*UploadRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadRequest_UploadElement interface {
	isUploadRequest_UploadElement()
}

type UploadRequest_Metadata struct {
	Metadata *UploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadRequest_Metadata) isUploadRequest_UploadElement() {}

func (*UploadRequest_ChunkData) isUploadRequest_UploadElement() {}

type UploadMetadata struct {
	state    protoimpl.MessageState  `protogen:"open.v1"`
	Identity *InfrastructureIdentity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// The original filename (e.g., "invoice.pdf")
	OriginalFilename string `protobuf:"bytes,2,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UploadMetadata) Reset() {
	*x = UploadMetadata{}
	mi := &file_storage_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadata) ProtoMessage() {}

func (x *UploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_storage_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadata.ProtoReflect.Descriptor instead.
func (*UploadMetadata) Descriptor() ([]byte, []int) {
	return file_storage_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMetadata) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *UploadMetadata) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

type UploadResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// The internal reference string, e.g. "internal-store://tenant_id/app_id/job_id/filename.pdf"
	StorageUri    string `protobuf:"bytes,3,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_storage_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_storage_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *UploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UploadResponse) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

type DownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The exact internal reference string to download
	StorageUri    string                  `protobuf:"bytes,1,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	Identity      *InfrastructureIdentity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_storage_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_storage_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadRequest) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *DownloadRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkData     []byte                 `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_storage_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_storage_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

type ClearJobDataRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Identity      *InfrastructureIdentity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearJobDataRequest) Reset() {
	*x = ClearJobDataRequest{}
	mi := &file_storage_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearJobDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearJobDataRequest) ProtoMessage() {}

func (x *ClearJobDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearJobDataRequest.ProtoReflect.Descriptor instead.
func (*ClearJobDataRequest) Descriptor() ([]byte, []int) {
	return file_storage_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ClearJobDataRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type ClearJobDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FilesDeleted  int32                  `protobuf:"varint,3,opt,name=files_deleted,json=filesDeleted,proto3" json:"files_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearJobDataResponse) Reset() {
	*x = ClearJobDataResponse{}
	mi := &file_storage_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearJobDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearJobDataResponse) ProtoMessage() {}

func (x *ClearJobDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearJobDataResponse.ProtoReflect.Descriptor instead.
func (*ClearJobDataResponse) Descriptor() ([]byte, []int) {
	return file_storage_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ClearJobDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearJobDataResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ClearJobDataResponse) GetFilesDeleted() int32 {
	if x != nil {
		return x.FilesDeleted
	}
	return 0
}

var File_storage_gateway_proto protoreflect.FileDescriptor

const file_storage_gateway_proto_rawDesc = "" +
	"\n" +
	"\x15storage_gateway.proto\x12\rshared_protos\x1a\fmodels.proto\"\x7f\n" +
	"\rUploadRequest\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1d.shared_protos.UploadMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x10\n" +
	"\x0eupload_element\"\x85\x01\n" +
	"\x0eUploadMetadata\x12F\n" +
	"\bidentity\x18\x01 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\x12+\n" +
	"\x11original_filename\x18\x02 \x01(\tR\x10originalFilename\"p\n" +
	"\x0eUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vstorage_uri\x18\x03 \x01(\tR\n" +
	"storageUri\"z\n" +
	"\x0fDownloadRequest\x12\x1f\n" +
	"\vstorage_uri\x18\x01 \x01(\tR\n" +
	"storageUri\x12F\n" +
	"\bidentity\x18\x02 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"1\n" +
	"\x10DownloadResponse\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x01 \x01(\fR\tchunkData\"]\n" +
	"\x13ClearJobDataRequest\x12F\n" +
	"\bidentity\x18\x01 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"z\n" +
	"\x14ClearJobDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12#\n" +
	"\rfiles_deleted\x18\x03 \x01(\x05R\ffilesDeleted2\x98\x02\n" +
	"\x15StorageGatewayService\x12O\n" +
	"\x0eUploadDocument\x12\x1c.shared_protos.UploadRequest\x1a\x1d.shared_protos.UploadResponse(\x01\x12U\n" +
	"\x10DownloadDocument\x12\x1e.shared_protos.DownloadRequest\x1a\x1f.shared_protos.DownloadResponse0\x01\x12W\n" +
	"\fClearJobData\x12\".shared_protos.ClearJobDataRequest\x1a#.shared_protos.ClearJobDataResponseB&Z$github.com/AndrewK4758/shared_protosb\x06proto3"

var (
	file_storage_gateway_proto_rawDescOnce sync.Once
	file_storage_gateway_proto_rawDescData []byte
)

func file_storage_gateway_proto_rawDescGZIP() []byte {
	file_storage_gateway_proto_rawDescOnce.Do(func() {
		file_storage_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_gateway_proto_rawDesc), len(file_storage_gateway_proto_rawDesc)))
	})
	return file_storage_gateway_proto_rawDescData
}

var file_storage_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_storage_gateway_proto_goTypes = []any{
	(*UploadRequest)(nil),          // 0: shared_protos.UploadRequest
	(*UploadMetadata)(nil),         // 1: shared_protos.UploadMetadata
	(*UploadResponse)(nil),         // 2: shared_protos.UploadResponse
	(*DownloadRequest)(nil),        // 3: shared_protos.DownloadRequest
	(*DownloadResponse)(nil),       // 4: shared_protos.DownloadResponse
	(*ClearJobDataRequest)(nil),    // 5: shared_protos.ClearJobDataRequest
	(*ClearJobDataResponse)(nil),   // 6: shared_protos.ClearJobDataResponse
	(*InfrastructureIdentity)(nil), // 7: document.models.v1.InfrastructureIdentity
}
var file_storage_gateway_proto_depIdxs = []int32{
	1, // 0: shared_protos.UploadRequest.metadata:type_name -> shared_protos.UploadMetadata
	7, // 1: shared_protos.UploadMetadata.identity:type_name -> document.models.v1.InfrastructureIdentity
	7, // 2: shared_protos.DownloadRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	7, // 3: shared_protos.ClearJobDataRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	0, // 4: shared_protos.StorageGatewayService.UploadDocument:input_type -> shared_protos.UploadRequest
	3, // 5: shared_protos.StorageGatewayService.DownloadDocument:input_type -> shared_protos.DownloadRequest
	5, // 6: shared_protos.StorageGatewayService.ClearJobData:input_type -> shared_protos.ClearJobDataRequest
	2, // 7: shared_protos.StorageGatewayService.UploadDocument:output_type -> shared_protos.UploadResponse
	4, // 8: shared_protos.StorageGatewayService.DownloadDocument:output_type -> shared_protos.DownloadResponse
	6, // 9: shared_protos.StorageGatewayService.ClearJobData:output_type -> shared_protos.ClearJobDataResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_storage_gateway_proto_init() }
func file_storage_gateway_proto_init() {
	if File_storage_gateway_proto != nil {
		return
	}
	file_models_proto_init()
	file_storage_gateway_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadRequest_Metadata)(nil),
		(*UploadRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_gateway_proto_rawDesc), len(file_storage_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_gateway_proto_goTypes,
		DependencyIndexes: file_storage_gateway_proto_depIdxs,
		MessageInfos:      file_storage_gateway_proto_msgTypes,
	}.Build()
	File_storage_gateway_proto = out.File
	file_storage_gateway_proto_goTypes = nil
	file_storage_gateway_proto_depIdxs = nil
}
