// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: traceability.proto

package shared_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobTraceRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	JobId         string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Identity      *InfrastructureIdentity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobTraceRequest) Reset() {
	*x = GetJobTraceRequest{}
	mi := &file_traceability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobTraceRequest) ProtoMessage() {}

func (x *GetJobTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traceability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobTraceRequest.ProtoReflect.Descriptor instead.
func (*GetJobTraceRequest) Descriptor() ([]byte, []int) {
	return file_traceability_proto_rawDescGZIP(), []int{0}
}

func (x *GetJobTraceRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobTraceRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type GetJobTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TraceEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobTraceResponse) Reset() {
	*x = GetJobTraceResponse{}
	mi := &file_traceability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobTraceResponse) ProtoMessage() {}

func (x *GetJobTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_traceability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobTraceResponse.ProtoReflect.Descriptor instead.
func (*GetJobTraceResponse) Descriptor() ([]byte, []int) {
	return file_traceability_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobTraceResponse) GetEvents() []*TraceEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetCorrelationTraceRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CorrelationId string                  `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Identity      *InfrastructureIdentity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCorrelationTraceRequest) Reset() {
	*x = GetCorrelationTraceRequest{}
	mi := &file_traceability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCorrelationTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCorrelationTraceRequest) ProtoMessage() {}

func (x *GetCorrelationTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traceability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCorrelationTraceRequest.ProtoReflect.Descriptor instead.
func (*GetCorrelationTraceRequest) Descriptor() ([]byte, []int) {
	return file_traceability_proto_rawDescGZIP(), []int{2}
}

func (x *GetCorrelationTraceRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *GetCorrelationTraceRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type GetCorrelationTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TraceEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCorrelationTraceResponse) Reset() {
	*x = GetCorrelationTraceResponse{}
	mi := &file_traceability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCorrelationTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCorrelationTraceResponse) ProtoMessage() {}

func (x *GetCorrelationTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_traceability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCorrelationTraceResponse.ProtoReflect.Descriptor instead.
func (*GetCorrelationTraceResponse) Descriptor() ([]byte, []int) {
	return file_traceability_proto_rawDescGZIP(), []int{3}
}

func (x *GetCorrelationTraceResponse) GetEvents() []*TraceEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TraceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StepId        string                 `protobuf:"bytes,4,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	EventType     string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,6,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      string                 `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Timestamp     string                 `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DocumentType  string                 `protobuf:"bytes,13,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceEvent) Reset() {
	*x = TraceEvent{}
	mi := &file_traceability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceEvent) ProtoMessage() {}

func (x *TraceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_traceability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceEvent.ProtoReflect.Descriptor instead.
func (*TraceEvent) Descriptor() ([]byte, []int) {
	return file_traceability_proto_rawDescGZIP(), []int{4}
}

func (x *TraceEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TraceEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TraceEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TraceEvent) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *TraceEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TraceEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *TraceEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TraceEvent) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *TraceEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TraceEvent) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

type SaveJobStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in traceability.proto.
	JobId           string                      `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	OriginalRequest *ExecuteWorkflowNodeRequest `protobuf:"bytes,2,opt,name=original_request,json=originalRequest,proto3" json:"original_request,omitempty"` // Full config
	Status          string                      `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                          // "PENDING", "COMPLETED", "FAILED"
	Identity        *InfrastructureIdentity     `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaveJobStateRequest) Reset() {
	*x = SaveJobStateRequest{}
	mi := &file_traceability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveJobStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveJobStateRequest) ProtoMessage() {}

func (x *SaveJobStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traceability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveJobStateRequest.ProtoReflect.Descriptor instead.
func (*SaveJobStateRequest) Descriptor() ([]byte, []int) {
	return file_traceability_proto_rawDescGZIP(), []int{5}
}

// Deprecated: Marked as deprecated in traceability.proto.
func (x *SaveJobStateRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SaveJobStateRequest) GetOriginalRequest() *ExecuteWorkflowNodeRequest {
	if x != nil {
		return x.OriginalRequest
	}
	return nil
}

func (x *SaveJobStateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SaveJobStateRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type SaveJobStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveJobStateResponse) Reset() {
	*x = SaveJobStateResponse{}
	mi := &file_traceability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveJobStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveJobStateResponse) ProtoMessage() {}

func (x *SaveJobStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_traceability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveJobStateResponse.ProtoReflect.Descriptor instead.
func (*SaveJobStateResponse) Descriptor() ([]byte, []int) {
	return file_traceability_proto_rawDescGZIP(), []int{6}
}

func (x *SaveJobStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPendingJobsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Identity      *InfrastructureIdentity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingJobsRequest) Reset() {
	*x = GetPendingJobsRequest{}
	mi := &file_traceability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingJobsRequest) ProtoMessage() {}

func (x *GetPendingJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traceability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingJobsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingJobsRequest) Descriptor() ([]byte, []int) {
	return file_traceability_proto_rawDescGZIP(), []int{7}
}

func (x *GetPendingJobsRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type GetPendingJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobStateRecord      `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingJobsResponse) Reset() {
	*x = GetPendingJobsResponse{}
	mi := &file_traceability_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingJobsResponse) ProtoMessage() {}

func (x *GetPendingJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_traceability_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingJobsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingJobsResponse) Descriptor() ([]byte, []int) {
	return file_traceability_proto_rawDescGZIP(), []int{8}
}

func (x *GetPendingJobsResponse) GetJobs() []*JobStateRecord {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type JobStateRecord struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	JobId           string                      `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	OriginalRequest *ExecuteWorkflowNodeRequest `protobuf:"bytes,2,opt,name=original_request,json=originalRequest,proto3" json:"original_request,omitempty"`
	Status          string                      `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Identity        *InfrastructureIdentity     `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobStateRecord) Reset() {
	*x = JobStateRecord{}
	mi := &file_traceability_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStateRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStateRecord) ProtoMessage() {}

func (x *JobStateRecord) ProtoReflect() protoreflect.Message {
	mi := &file_traceability_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStateRecord.ProtoReflect.Descriptor instead.
func (*JobStateRecord) Descriptor() ([]byte, []int) {
	return file_traceability_proto_rawDescGZIP(), []int{9}
}

func (x *JobStateRecord) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStateRecord) GetOriginalRequest() *ExecuteWorkflowNodeRequest {
	if x != nil {
		return x.OriginalRequest
	}
	return nil
}

func (x *JobStateRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStateRecord) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type GetJobStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in traceability.proto.
	JobId         string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Identity      *InfrastructureIdentity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStateRequest) Reset() {
	*x = GetJobStateRequest{}
	mi := &file_traceability_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStateRequest) ProtoMessage() {}

func (x *GetJobStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traceability_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStateRequest.ProtoReflect.Descriptor instead.
func (*GetJobStateRequest) Descriptor() ([]byte, []int) {
	return file_traceability_proto_rawDescGZIP(), []int{10}
}

// Deprecated: Marked as deprecated in traceability.proto.
func (x *GetJobStateRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStateRequest) GetIdentity() *InfrastructureIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type GetJobStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Job           *JobStateRecord        `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStateResponse) Reset() {
	*x = GetJobStateResponse{}
	mi := &file_traceability_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStateResponse) ProtoMessage() {}

func (x *GetJobStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_traceability_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStateResponse.ProtoReflect.Descriptor instead.
func (*GetJobStateResponse) Descriptor() ([]byte, []int) {
	return file_traceability_proto_rawDescGZIP(), []int{11}
}

func (x *GetJobStateResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetJobStateResponse) GetJob() *JobStateRecord {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_traceability_proto protoreflect.FileDescriptor

const file_traceability_proto_rawDesc = "" +
	"\n" +
	"\x12traceability.proto\x12\ftraceability\x1a\x12orchestrator.proto\x1a\fmodels.proto\"s\n" +
	"\x12GetJobTraceRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12F\n" +
	"\bidentity\x18\x02 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"G\n" +
	"\x13GetJobTraceResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.traceability.TraceEventR\x06events\"\x8b\x01\n" +
	"\x1aGetCorrelationTraceRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12F\n" +
	"\bidentity\x18\x02 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"O\n" +
	"\x1bGetCorrelationTraceResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.traceability.TraceEventR\x06events\"\xac\x02\n" +
	"\n" +
	"TraceEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12\x17\n" +
	"\astep_id\x18\x04 \x01(\tR\x06stepId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12\x1f\n" +
	"\vresource_id\x18\x06 \x01(\tR\n" +
	"resourceId\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x1a\n" +
	"\bmetadata\x18\v \x01(\tR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\f \x01(\tR\ttimestamp\x12#\n" +
	"\rdocument_type\x18\r \x01(\tR\fdocumentType\"\xf1\x01\n" +
	"\x13SaveJobStateRequest\x12\x19\n" +
	"\x06job_id\x18\x01 \x01(\tB\x02\x18\x01R\x05jobId\x12_\n" +
	"\x10original_request\x18\x02 \x01(\v24.document.orchestrator.v1.ExecuteWorkflowNodeRequestR\x0foriginalRequest\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12F\n" +
	"\bidentity\x18\x04 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"0\n" +
	"\x14SaveJobStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"_\n" +
	"\x15GetPendingJobsRequest\x12F\n" +
	"\bidentity\x18\x01 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"J\n" +
	"\x16GetPendingJobsResponse\x120\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1c.traceability.JobStateRecordR\x04jobs\"\xe8\x01\n" +
	"\x0eJobStateRecord\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12_\n" +
	"\x10original_request\x18\x02 \x01(\v24.document.orchestrator.v1.ExecuteWorkflowNodeRequestR\x0foriginalRequest\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12F\n" +
	"\bidentity\x18\x04 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"w\n" +
	"\x12GetJobStateRequest\x12\x19\n" +
	"\x06job_id\x18\x01 \x01(\tB\x02\x18\x01R\x05jobId\x12F\n" +
	"\bidentity\x18\x02 \x01(\v2*.document.models.v1.InfrastructureIdentityR\bidentity\"[\n" +
	"\x13GetJobStateResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12.\n" +
	"\x03job\x18\x02 \x01(\v2\x1c.traceability.JobStateRecordR\x03job2\xdb\x03\n" +
	"\x11TraceabilityQuery\x12R\n" +
	"\vGetJobTrace\x12 .traceability.GetJobTraceRequest\x1a!.traceability.GetJobTraceResponse\x12j\n" +
	"\x13GetCorrelationTrace\x12(.traceability.GetCorrelationTraceRequest\x1a).traceability.GetCorrelationTraceResponse\x12U\n" +
	"\fSaveJobState\x12!.traceability.SaveJobStateRequest\x1a\".traceability.SaveJobStateResponse\x12[\n" +
	"\x0eGetPendingJobs\x12#.traceability.GetPendingJobsRequest\x1a$.traceability.GetPendingJobsResponse\x12R\n" +
	"\vGetJobState\x12 .traceability.GetJobStateRequest\x1a!.traceability.GetJobStateResponseBCZ$github.com/AndrewK4758/shared_protos\xaa\x02\x1aTraceabilityService.Protosb\x06proto3"

var (
	file_traceability_proto_rawDescOnce sync.Once
	file_traceability_proto_rawDescData []byte
)

func file_traceability_proto_rawDescGZIP() []byte {
	file_traceability_proto_rawDescOnce.Do(func() {
		file_traceability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_traceability_proto_rawDesc), len(file_traceability_proto_rawDesc)))
	})
	return file_traceability_proto_rawDescData
}

var file_traceability_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_traceability_proto_goTypes = []any{
	(*GetJobTraceRequest)(nil),          // 0: traceability.GetJobTraceRequest
	(*GetJobTraceResponse)(nil),         // 1: traceability.GetJobTraceResponse
	(*GetCorrelationTraceRequest)(nil),  // 2: traceability.GetCorrelationTraceRequest
	(*GetCorrelationTraceResponse)(nil), // 3: traceability.GetCorrelationTraceResponse
	(*TraceEvent)(nil),                  // 4: traceability.TraceEvent
	(*SaveJobStateRequest)(nil),         // 5: traceability.SaveJobStateRequest
	(*SaveJobStateResponse)(nil),        // 6: traceability.SaveJobStateResponse
	(*GetPendingJobsRequest)(nil),       // 7: traceability.GetPendingJobsRequest
	(*GetPendingJobsResponse)(nil),      // 8: traceability.GetPendingJobsResponse
	(*JobStateRecord)(nil),              // 9: traceability.JobStateRecord
	(*GetJobStateRequest)(nil),          // 10: traceability.GetJobStateRequest
	(*GetJobStateResponse)(nil),         // 11: traceability.GetJobStateResponse
	(*InfrastructureIdentity)(nil),      // 12: document.models.v1.InfrastructureIdentity
	(*ExecuteWorkflowNodeRequest)(nil),  // 13: document.orchestrator.v1.ExecuteWorkflowNodeRequest
}
var file_traceability_proto_depIdxs = []int32{
	12, // 0: traceability.GetJobTraceRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	4,  // 1: traceability.GetJobTraceResponse.events:type_name -> traceability.TraceEvent
	12, // 2: traceability.GetCorrelationTraceRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	4,  // 3: traceability.GetCorrelationTraceResponse.events:type_name -> traceability.TraceEvent
	13, // 4: traceability.SaveJobStateRequest.original_request:type_name -> document.orchestrator.v1.ExecuteWorkflowNodeRequest
	12, // 5: traceability.SaveJobStateRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	12, // 6: traceability.GetPendingJobsRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	9,  // 7: traceability.GetPendingJobsResponse.jobs:type_name -> traceability.JobStateRecord
	13, // 8: traceability.JobStateRecord.original_request:type_name -> document.orchestrator.v1.ExecuteWorkflowNodeRequest
	12, // 9: traceability.JobStateRecord.identity:type_name -> document.models.v1.InfrastructureIdentity
	12, // 10: traceability.GetJobStateRequest.identity:type_name -> document.models.v1.InfrastructureIdentity
	9,  // 11: traceability.GetJobStateResponse.job:type_name -> traceability.JobStateRecord
	0,  // 12: traceability.TraceabilityQuery.GetJobTrace:input_type -> traceability.GetJobTraceRequest
	2,  // 13: traceability.TraceabilityQuery.GetCorrelationTrace:input_type -> traceability.GetCorrelationTraceRequest
	5,  // 14: traceability.TraceabilityQuery.SaveJobState:input_type -> traceability.SaveJobStateRequest
	7,  // 15: traceability.TraceabilityQuery.GetPendingJobs:input_type -> traceability.GetPendingJobsRequest
	10, // 16: traceability.TraceabilityQuery.GetJobState:input_type -> traceability.GetJobStateRequest
	1,  // 17: traceability.TraceabilityQuery.GetJobTrace:output_type -> traceability.GetJobTraceResponse
	3,  // 18: traceability.TraceabilityQuery.GetCorrelationTrace:output_type -> traceability.GetCorrelationTraceResponse
	6,  // 19: traceability.TraceabilityQuery.SaveJobState:output_type -> traceability.SaveJobStateResponse
	8,  // 20: traceability.TraceabilityQuery.GetPendingJobs:output_type -> traceability.GetPendingJobsResponse
	11, // 21: traceability.TraceabilityQuery.GetJobState:output_type -> traceability.GetJobStateResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_traceability_proto_init() }
func file_traceability_proto_init() {
	if File_traceability_proto != nil {
		return
	}
	file_orchestrator_proto_init()
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_traceability_proto_rawDesc), len(file_traceability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_traceability_proto_goTypes,
		DependencyIndexes: file_traceability_proto_depIdxs,
		MessageInfos:      file_traceability_proto_msgTypes,
	}.Build()
	File_traceability_proto = out.File
	file_traceability_proto_goTypes = nil
	file_traceability_proto_depIdxs = nil
}
