// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: human_validation.proto

package shared_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTaskRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StepName           string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	FailedAiOutput     string                 `protobuf:"bytes,3,opt,name=failed_ai_output,json=failedAiOutput,proto3" json:"failed_ai_output,omitempty"`
	ExpectedSchema     string                 `protobuf:"bytes,4,opt,name=expected_schema,json=expectedSchema,proto3" json:"expected_schema,omitempty"`
	PromptInstructions string                 `protobuf:"bytes,5,opt,name=prompt_instructions,json=promptInstructions,proto3" json:"prompt_instructions,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TargetFields       []string               `protobuf:"bytes,7,rep,name=target_fields,json=targetFields,proto3" json:"target_fields,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_human_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_human_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_human_validation_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreateTaskRequest) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *CreateTaskRequest) GetFailedAiOutput() string {
	if x != nil {
		return x.FailedAiOutput
	}
	return ""
}

func (x *CreateTaskRequest) GetExpectedSchema() string {
	if x != nil {
		return x.ExpectedSchema
	}
	return ""
}

func (x *CreateTaskRequest) GetPromptInstructions() string {
	if x != nil {
		return x.PromptInstructions
	}
	return ""
}

func (x *CreateTaskRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CreateTaskRequest) GetTargetFields() []string {
	if x != nil {
		return x.TargetFields
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // e.g., "CREATED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_human_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_human_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_human_validation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetPendingTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterStatus  string                 `protobuf:"bytes,1,opt,name=filter_status,json=filterStatus,proto3" json:"filter_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingTasksRequest) Reset() {
	*x = GetPendingTasksRequest{}
	mi := &file_human_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingTasksRequest) ProtoMessage() {}

func (x *GetPendingTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_human_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingTasksRequest.ProtoReflect.Descriptor instead.
func (*GetPendingTasksRequest) Descriptor() ([]byte, []int) {
	return file_human_validation_proto_rawDescGZIP(), []int{2}
}

func (x *GetPendingTasksRequest) GetFilterStatus() string {
	if x != nil {
		return x.FilterStatus
	}
	return ""
}

type PendingTask struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId              string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StepName           string                 `protobuf:"bytes,3,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	FailedAiOutput     string                 `protobuf:"bytes,4,opt,name=failed_ai_output,json=failedAiOutput,proto3" json:"failed_ai_output,omitempty"`
	ExpectedSchema     string                 `protobuf:"bytes,5,opt,name=expected_schema,json=expectedSchema,proto3" json:"expected_schema,omitempty"`
	PromptInstructions string                 `protobuf:"bytes,6,opt,name=prompt_instructions,json=promptInstructions,proto3" json:"prompt_instructions,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TargetFields       []string               `protobuf:"bytes,8,rep,name=target_fields,json=targetFields,proto3" json:"target_fields,omitempty"`
	Status             string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"` // e.g., "PENDING", "RESOLVED"
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PendingTask) Reset() {
	*x = PendingTask{}
	mi := &file_human_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingTask) ProtoMessage() {}

func (x *PendingTask) ProtoReflect() protoreflect.Message {
	mi := &file_human_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingTask.ProtoReflect.Descriptor instead.
func (*PendingTask) Descriptor() ([]byte, []int) {
	return file_human_validation_proto_rawDescGZIP(), []int{3}
}

func (x *PendingTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PendingTask) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PendingTask) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *PendingTask) GetFailedAiOutput() string {
	if x != nil {
		return x.FailedAiOutput
	}
	return ""
}

func (x *PendingTask) GetExpectedSchema() string {
	if x != nil {
		return x.ExpectedSchema
	}
	return ""
}

func (x *PendingTask) GetPromptInstructions() string {
	if x != nil {
		return x.PromptInstructions
	}
	return ""
}

func (x *PendingTask) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PendingTask) GetTargetFields() []string {
	if x != nil {
		return x.TargetFields
	}
	return nil
}

func (x *PendingTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetPendingTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*PendingTask         `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingTasksResponse) Reset() {
	*x = GetPendingTasksResponse{}
	mi := &file_human_validation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingTasksResponse) ProtoMessage() {}

func (x *GetPendingTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_human_validation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingTasksResponse.ProtoReflect.Descriptor instead.
func (*GetPendingTasksResponse) Descriptor() ([]byte, []int) {
	return file_human_validation_proto_rawDescGZIP(), []int{4}
}

func (x *GetPendingTasksResponse) GetTasks() []*PendingTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type SubmitCorrectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CorrectedJson string                 `protobuf:"bytes,2,opt,name=corrected_json,json=correctedJson,proto3" json:"corrected_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCorrectionRequest) Reset() {
	*x = SubmitCorrectionRequest{}
	mi := &file_human_validation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCorrectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCorrectionRequest) ProtoMessage() {}

func (x *SubmitCorrectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_human_validation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCorrectionRequest.ProtoReflect.Descriptor instead.
func (*SubmitCorrectionRequest) Descriptor() ([]byte, []int) {
	return file_human_validation_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitCorrectionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitCorrectionRequest) GetCorrectedJson() string {
	if x != nil {
		return x.CorrectedJson
	}
	return ""
}

type SubmitCorrectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCorrectionResponse) Reset() {
	*x = SubmitCorrectionResponse{}
	mi := &file_human_validation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCorrectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCorrectionResponse) ProtoMessage() {}

func (x *SubmitCorrectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_human_validation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCorrectionResponse.ProtoReflect.Descriptor instead.
func (*SubmitCorrectionResponse) Descriptor() ([]byte, []int) {
	return file_human_validation_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitCorrectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitCorrectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_human_validation_proto protoreflect.FileDescriptor

const file_human_validation_proto_rawDesc = "" +
	"\n" +
	"\x16human_validation.proto\x12\x16document.validation.v1\"\x95\x02\n" +
	"\x11CreateTaskRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12(\n" +
	"\x10failed_ai_output\x18\x03 \x01(\tR\x0efailedAiOutput\x12'\n" +
	"\x0fexpected_schema\x18\x04 \x01(\tR\x0eexpectedSchema\x12/\n" +
	"\x13prompt_instructions\x18\x05 \x01(\tR\x12promptInstructions\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12#\n" +
	"\rtarget_fields\x18\a \x03(\tR\ftargetFields\"E\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"=\n" +
	"\x16GetPendingTasksRequest\x12#\n" +
	"\rfilter_status\x18\x01 \x01(\tR\ffilterStatus\"\xc0\x02\n" +
	"\vPendingTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tstep_name\x18\x03 \x01(\tR\bstepName\x12(\n" +
	"\x10failed_ai_output\x18\x04 \x01(\tR\x0efailedAiOutput\x12'\n" +
	"\x0fexpected_schema\x18\x05 \x01(\tR\x0eexpectedSchema\x12/\n" +
	"\x13prompt_instructions\x18\x06 \x01(\tR\x12promptInstructions\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12#\n" +
	"\rtarget_fields\x18\b \x03(\tR\ftargetFields\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"T\n" +
	"\x17GetPendingTasksResponse\x129\n" +
	"\x05tasks\x18\x01 \x03(\v2#.document.validation.v1.PendingTaskR\x05tasks\"Y\n" +
	"\x17SubmitCorrectionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x0ecorrected_json\x18\x02 \x01(\tR\rcorrectedJson\"N\n" +
	"\x18SubmitCorrectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf2\x02\n" +
	"\x16HumanValidationService\x12m\n" +
	"\x14CreateValidationTask\x12).document.validation.v1.CreateTaskRequest\x1a*.document.validation.v1.CreateTaskResponse\x12r\n" +
	"\x0fGetPendingTasks\x12..document.validation.v1.GetPendingTasksRequest\x1a/.document.validation.v1.GetPendingTasksResponse\x12u\n" +
	"\x10SubmitCorrection\x12/.document.validation.v1.SubmitCorrectionRequest\x1a0.document.validation.v1.SubmitCorrectionResponseB\x1dZ\x1bdoc_processor/shared_protosb\x06proto3"

var (
	file_human_validation_proto_rawDescOnce sync.Once
	file_human_validation_proto_rawDescData []byte
)

func file_human_validation_proto_rawDescGZIP() []byte {
	file_human_validation_proto_rawDescOnce.Do(func() {
		file_human_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_human_validation_proto_rawDesc), len(file_human_validation_proto_rawDesc)))
	})
	return file_human_validation_proto_rawDescData
}

var file_human_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_human_validation_proto_goTypes = []any{
	(*CreateTaskRequest)(nil),        // 0: document.validation.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),       // 1: document.validation.v1.CreateTaskResponse
	(*GetPendingTasksRequest)(nil),   // 2: document.validation.v1.GetPendingTasksRequest
	(*PendingTask)(nil),              // 3: document.validation.v1.PendingTask
	(*GetPendingTasksResponse)(nil),  // 4: document.validation.v1.GetPendingTasksResponse
	(*SubmitCorrectionRequest)(nil),  // 5: document.validation.v1.SubmitCorrectionRequest
	(*SubmitCorrectionResponse)(nil), // 6: document.validation.v1.SubmitCorrectionResponse
}
var file_human_validation_proto_depIdxs = []int32{
	3, // 0: document.validation.v1.GetPendingTasksResponse.tasks:type_name -> document.validation.v1.PendingTask
	0, // 1: document.validation.v1.HumanValidationService.CreateValidationTask:input_type -> document.validation.v1.CreateTaskRequest
	2, // 2: document.validation.v1.HumanValidationService.GetPendingTasks:input_type -> document.validation.v1.GetPendingTasksRequest
	5, // 3: document.validation.v1.HumanValidationService.SubmitCorrection:input_type -> document.validation.v1.SubmitCorrectionRequest
	1, // 4: document.validation.v1.HumanValidationService.CreateValidationTask:output_type -> document.validation.v1.CreateTaskResponse
	4, // 5: document.validation.v1.HumanValidationService.GetPendingTasks:output_type -> document.validation.v1.GetPendingTasksResponse
	6, // 6: document.validation.v1.HumanValidationService.SubmitCorrection:output_type -> document.validation.v1.SubmitCorrectionResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_human_validation_proto_init() }
func file_human_validation_proto_init() {
	if File_human_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_human_validation_proto_rawDesc), len(file_human_validation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_human_validation_proto_goTypes,
		DependencyIndexes: file_human_validation_proto_depIdxs,
		MessageInfos:      file_human_validation_proto_msgTypes,
	}.Build()
	File_human_validation_proto = out.File
	file_human_validation_proto_goTypes = nil
	file_human_validation_proto_depIdxs = nil
}
