// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: processor.proto

package shared_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelChoice int32

const (
	ModelChoice_MODEL_CHOICE_UNSPECIFIED ModelChoice = 0
	ModelChoice_MODEL_CHOICE_LOCAL       ModelChoice = 1
)

// Enum value maps for ModelChoice.
var (
	ModelChoice_name = map[int32]string{
		0: "MODEL_CHOICE_UNSPECIFIED",
		1: "MODEL_CHOICE_LOCAL",
	}
	ModelChoice_value = map[string]int32{
		"MODEL_CHOICE_UNSPECIFIED": 0,
		"MODEL_CHOICE_LOCAL":       1,
	}
)

func (x ModelChoice) Enum() *ModelChoice {
	p := new(ModelChoice)
	*p = x
	return p
}

func (x ModelChoice) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelChoice) Descriptor() protoreflect.EnumDescriptor {
	return file_processor_proto_enumTypes[0].Descriptor()
}

func (ModelChoice) Type() protoreflect.EnumType {
	return &file_processor_proto_enumTypes[0]
}

func (x ModelChoice) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelChoice.Descriptor instead.
func (ModelChoice) EnumDescriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{0}
}

type ProcessDocumentRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FileContent        []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	FileName           string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ModelChoice        ModelChoice            `protobuf:"varint,3,opt,name=model_choice,json=modelChoice,proto3,enum=document.processor.v1.ModelChoice" json:"model_choice,omitempty"`
	DocumentType       string                 `protobuf:"bytes,4,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	TargetFields       []string               `protobuf:"bytes,5,rep,name=target_fields,json=targetFields,proto3" json:"target_fields,omitempty"`
	JsonSchema         string                 `protobuf:"bytes,6,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	CustomInstructions string                 `protobuf:"bytes,7,opt,name=custom_instructions,json=customInstructions,proto3" json:"custom_instructions,omitempty"`
	AppId              string                 `protobuf:"bytes,8,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	CorrelationId      string                 `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProcessDocumentRequest) Reset() {
	*x = ProcessDocumentRequest{}
	mi := &file_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentRequest) ProtoMessage() {}

func (x *ProcessDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentRequest.ProtoReflect.Descriptor instead.
func (*ProcessDocumentRequest) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessDocumentRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *ProcessDocumentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ProcessDocumentRequest) GetModelChoice() ModelChoice {
	if x != nil {
		return x.ModelChoice
	}
	return ModelChoice_MODEL_CHOICE_UNSPECIFIED
}

func (x *ProcessDocumentRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *ProcessDocumentRequest) GetTargetFields() []string {
	if x != nil {
		return x.TargetFields
	}
	return nil
}

func (x *ProcessDocumentRequest) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

func (x *ProcessDocumentRequest) GetCustomInstructions() string {
	if x != nil {
		return x.CustomInstructions
	}
	return ""
}

func (x *ProcessDocumentRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ProcessDocumentRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ProcessDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDocumentResponse) Reset() {
	*x = ProcessDocumentResponse{}
	mi := &file_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentResponse) ProtoMessage() {}

func (x *ProcessDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentResponse.ProtoReflect.Descriptor instead.
func (*ProcessDocumentResponse) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessDocumentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProcessDocumentResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ProcessDocumentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ExtractRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Orchestrator sends the physical PDF chunk
	ChunkPdf []byte `protobuf:"bytes,1,opt,name=chunk_pdf,json=chunkPdf,proto3" json:"chunk_pdf,omitempty"`
	// The Orchestrator passes the exact prompt (e.g., "Find the document boundaries in this chunk")
	Prompt string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Strict JSON Schema to enforce the model's output format
	JsonSchema  string      `protobuf:"bytes,3,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	ModelChoice ModelChoice `protobuf:"varint,4,opt,name=model_choice,json=modelChoice,proto3,enum=document.processor.v1.ModelChoice" json:"model_choice,omitempty"`
	// The Orchestrator sends raw text (if processing raw text instead of a PDF chunk)
	ChunkText     string `protobuf:"bytes,5,opt,name=chunk_text,json=chunkText,proto3" json:"chunk_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractRequest) GetChunkPdf() []byte {
	if x != nil {
		return x.ChunkPdf
	}
	return nil
}

func (x *ExtractRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExtractRequest) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

func (x *ExtractRequest) GetModelChoice() ModelChoice {
	if x != nil {
		return x.ModelChoice
	}
	return ModelChoice_MODEL_CHOICE_UNSPECIFIED
}

func (x *ExtractRequest) GetChunkText() string {
	if x != nil {
		return x.ChunkText
	}
	return ""
}

type ExtractResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// The raw JSON string returned by the LLM
	ExtractedJson string `protobuf:"bytes,3,opt,name=extracted_json,json=extractedJson,proto3" json:"extracted_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_processor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExtractResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExtractResponse) GetExtractedJson() string {
	if x != nil {
		return x.ExtractedJson
	}
	return ""
}

var File_processor_proto protoreflect.FileDescriptor

const file_processor_proto_rawDesc = "" +
	"\n" +
	"\x0fprocessor.proto\x12\x15document.processor.v1\"\xf9\x02\n" +
	"\x16ProcessDocumentRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12E\n" +
	"\fmodel_choice\x18\x03 \x01(\x0e2\".document.processor.v1.ModelChoiceR\vmodelChoice\x12#\n" +
	"\rdocument_type\x18\x04 \x01(\tR\fdocumentType\x12#\n" +
	"\rtarget_fields\x18\x05 \x03(\tR\ftargetFields\x12\x1f\n" +
	"\vjson_schema\x18\x06 \x01(\tR\n" +
	"jsonSchema\x12/\n" +
	"\x13custom_instructions\x18\a \x01(\tR\x12customInstructions\x12\x15\n" +
	"\x06app_id\x18\b \x01(\tR\x05appId\x12%\n" +
	"\x0ecorrelation_id\x18\t \x01(\tR\rcorrelationId\"\x97\x01\n" +
	"\x17ProcessDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xcc\x01\n" +
	"\x0eExtractRequest\x12\x1b\n" +
	"\tchunk_pdf\x18\x01 \x01(\fR\bchunkPdf\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1f\n" +
	"\vjson_schema\x18\x03 \x01(\tR\n" +
	"jsonSchema\x12E\n" +
	"\fmodel_choice\x18\x04 \x01(\x0e2\".document.processor.v1.ModelChoiceR\vmodelChoice\x12\x1d\n" +
	"\n" +
	"chunk_text\x18\x05 \x01(\tR\tchunkText\"w\n" +
	"\x0fExtractResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0eextracted_json\x18\x03 \x01(\tR\rextractedJson*C\n" +
	"\vModelChoice\x12\x1c\n" +
	"\x18MODEL_CHOICE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MODEL_CHOICE_LOCAL\x10\x012\xeb\x01\n" +
	"\x11DocumentProcessor\x12p\n" +
	"\x0fProcessDocument\x12-.document.processor.v1.ProcessDocumentRequest\x1a..document.processor.v1.ProcessDocumentResponse\x12d\n" +
	"\x13ExtractDocumentData\x12%.document.processor.v1.ExtractRequest\x1a&.document.processor.v1.ExtractResponseB\x1dZ\x1bdoc_processor/shared_protosb\x06proto3"

var (
	file_processor_proto_rawDescOnce sync.Once
	file_processor_proto_rawDescData []byte
)

func file_processor_proto_rawDescGZIP() []byte {
	file_processor_proto_rawDescOnce.Do(func() {
		file_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_processor_proto_rawDesc), len(file_processor_proto_rawDesc)))
	})
	return file_processor_proto_rawDescData
}

var file_processor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_processor_proto_goTypes = []any{
	(ModelChoice)(0),                // 0: document.processor.v1.ModelChoice
	(*ProcessDocumentRequest)(nil),  // 1: document.processor.v1.ProcessDocumentRequest
	(*ProcessDocumentResponse)(nil), // 2: document.processor.v1.ProcessDocumentResponse
	(*ExtractRequest)(nil),          // 3: document.processor.v1.ExtractRequest
	(*ExtractResponse)(nil),         // 4: document.processor.v1.ExtractResponse
}
var file_processor_proto_depIdxs = []int32{
	0, // 0: document.processor.v1.ProcessDocumentRequest.model_choice:type_name -> document.processor.v1.ModelChoice
	0, // 1: document.processor.v1.ExtractRequest.model_choice:type_name -> document.processor.v1.ModelChoice
	1, // 2: document.processor.v1.DocumentProcessor.ProcessDocument:input_type -> document.processor.v1.ProcessDocumentRequest
	3, // 3: document.processor.v1.DocumentProcessor.ExtractDocumentData:input_type -> document.processor.v1.ExtractRequest
	2, // 4: document.processor.v1.DocumentProcessor.ProcessDocument:output_type -> document.processor.v1.ProcessDocumentResponse
	4, // 5: document.processor.v1.DocumentProcessor.ExtractDocumentData:output_type -> document.processor.v1.ExtractResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_processor_proto_init() }
func file_processor_proto_init() {
	if File_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_processor_proto_rawDesc), len(file_processor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_processor_proto_goTypes,
		DependencyIndexes: file_processor_proto_depIdxs,
		EnumInfos:         file_processor_proto_enumTypes,
		MessageInfos:      file_processor_proto_msgTypes,
	}.Build()
	File_processor_proto = out.File
	file_processor_proto_goTypes = nil
	file_processor_proto_depIdxs = nil
}
