// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: processor.proto

package shared_protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentProcessor_ProcessDocument_FullMethodName     = "/document.processor.v1.DocumentProcessor/ProcessDocument"
	DocumentProcessor_ExtractDocumentData_FullMethodName = "/document.processor.v1.DocumentProcessor/ExtractDocumentData"
)

// DocumentProcessorClient is the client API for DocumentProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentProcessorClient interface {
	// Existing Async method (keeps current NATS architecture intact for legacy)
	ProcessDocument(ctx context.Context, in *ProcessDocumentRequest, opts ...grpc.CallOption) (*ProcessDocumentResponse, error)
	// NEW: Synchronous method for the Orchestrator to use for fast, blocking chunk processing
	ExtractDocumentData(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
}

type documentProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentProcessorClient(cc grpc.ClientConnInterface) DocumentProcessorClient {
	return &documentProcessorClient{cc}
}

func (c *documentProcessorClient) ProcessDocument(ctx context.Context, in *ProcessDocumentRequest, opts ...grpc.CallOption) (*ProcessDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentProcessor_ProcessDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentProcessorClient) ExtractDocumentData(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, DocumentProcessor_ExtractDocumentData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentProcessorServer is the server API for DocumentProcessor service.
// All implementations must embed UnimplementedDocumentProcessorServer
// for forward compatibility.
type DocumentProcessorServer interface {
	// Existing Async method (keeps current NATS architecture intact for legacy)
	ProcessDocument(context.Context, *ProcessDocumentRequest) (*ProcessDocumentResponse, error)
	// NEW: Synchronous method for the Orchestrator to use for fast, blocking chunk processing
	ExtractDocumentData(context.Context, *ExtractRequest) (*ExtractResponse, error)
	mustEmbedUnimplementedDocumentProcessorServer()
}

// UnimplementedDocumentProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentProcessorServer struct{}

func (UnimplementedDocumentProcessorServer) ProcessDocument(context.Context, *ProcessDocumentRequest) (*ProcessDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessDocument not implemented")
}
func (UnimplementedDocumentProcessorServer) ExtractDocumentData(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractDocumentData not implemented")
}
func (UnimplementedDocumentProcessorServer) mustEmbedUnimplementedDocumentProcessorServer() {}
func (UnimplementedDocumentProcessorServer) testEmbeddedByValue()                           {}

// UnsafeDocumentProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentProcessorServer will
// result in compilation errors.
type UnsafeDocumentProcessorServer interface {
	mustEmbedUnimplementedDocumentProcessorServer()
}

func RegisterDocumentProcessorServer(s grpc.ServiceRegistrar, srv DocumentProcessorServer) {
	// If the following call panics, it indicates UnimplementedDocumentProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentProcessor_ServiceDesc, srv)
}

func _DocumentProcessor_ProcessDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentProcessorServer).ProcessDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentProcessor_ProcessDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentProcessorServer).ProcessDocument(ctx, req.(*ProcessDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentProcessor_ExtractDocumentData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentProcessorServer).ExtractDocumentData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentProcessor_ExtractDocumentData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentProcessorServer).ExtractDocumentData(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentProcessor_ServiceDesc is the grpc.ServiceDesc for DocumentProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "document.processor.v1.DocumentProcessor",
	HandlerType: (*DocumentProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessDocument",
			Handler:    _DocumentProcessor_ProcessDocument_Handler,
		},
		{
			MethodName: "ExtractDocumentData",
			Handler:    _DocumentProcessor_ExtractDocumentData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "processor.proto",
}
